chore: new 'types' module
defenseunicorns/leapfrogai pull request #1009
Opened 2024-09-09 16:00 UTC by alekst23

## Description
(replaces PR https://github.com/defenseunicorns/leapfrogai/pull/963)

We need a better way to organize our type definitions. Currently we have the following issues:
- One file with a lot of definitions: `src/leapfrogai_api/backend/types.py`. Very long file with many types for different purposes defined together. Difficult to analyze and find code.
- Some types mix data models and complex function implementations in one class
- Types are not defined in a consistent manner

Good format to follow is the OpenAI types module:
https://github.com/openai/openai-python/tree/main/src/openai/types

### BREAKING CHANGES
All changes to type definitions should be applied to all relevant files as part of the PR.

### CHANGES
- A new module for `leapfrogai_api` is created: `types`.
- Python Module format allows for complex type hierarchy and selective importing of objects. 
- Creates a standardized way for application to define and use types.
- Consolidates types defined inline and in `src/leapfrogai_api/backend/types` to the new `types` module
- Consolidates constants to `src/leapfrogai_api/types/constants.py`

## Related Issue

Precursor to: 
https://github.com/defenseunicorns/leapfrogai/issues/948

## Checklist before merging

- [ ] Tests, documentation, ADR added or updated as needed
- [ ] Followed the [Contributor Guide Steps](https://github.com/defenseunicorns/leapfrogai/blob/main/.github/CONTRIBUTING.md)

2024-09-09 23:55 UTC, justinthelaw requested changes
Two integration tests are currently failing in this refactor; 1 related to runs and 1 related to auth, and both of them are based on imports: https://github.com/defenseunicorns/leapfrogai/actions/runs/10782682964/job/29903199093#step:12:53

Everything else looks good, now that the comments from the team are addressed! This is a great refactor - love the organization.

2024-09-13 16:22 UTC, alekst23 commented
@justinthelaw Fixed and updated from main. Waiting for the tests to run again.

2024-09-13 18:46 UTC, justinthelaw commented
> @justinthelaw Fixed and updated from main. Waiting for the tests to run again.

Looks like there is still 1 failing integration test, but the debug info might be in-cluster.

2024-09-14 17:34 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/runs.py
> +            request=request,
Typing conflict ThreadRunCreateParamsRequest RunCreateParamsRequest.

2024-09-14 17:34 UTC, gphorvath commented on src/leapfrogai_api/backend/composer.py
> +                    query=query_message.content,
Type conflict `list[TextContentBlockParam]` vs `str`.

2024-09-18 13:13 UTC, justinthelaw submitted a review, later dismissed
Super minor nit that can be accomplished in a separate branch (so you don't have to run tests again). Looks great!

2024-09-18 13:13 UTC, justinthelaw commented on .github/workflows/pytest.yaml
> -            **/src/leapfrogai_api
Make sure to remove these lines from the original cache-ing action in the previous job too!

2024-09-18 13:13 UTC, justinthelaw commented on src/leapfrogai_api/backend/constants.py
> +
Should we also put the default K in here just to centralize the similarity search variable?

2024-09-18 15:14 UTC, gphorvath commented on src/leapfrogai_api/backend/constants.py
> +
I added this!

2024-09-18 15:18 UTC, gphorvath commented on .github/workflows/pytest.yaml
> -            **/src/leapfrogai_api
done

2024-09-18 15:43 UTC, jalling97 approved these changes
Presuming the remaining tests pass, this looks good to me!

2024-09-18 15:46 UTC, justinthelaw approved these changes

2024-09-18 17:21 UTC, CollectiveUnicorn approved these changes

2024-09-18 22:21 UTC, merged