bug(api): best_of in completions was an int and should be a string
defenseunicorns/leapfrogai pull request #1031
Opened 2024-09-13 18:25 UTC by lemonprogis

## Description

### BREAKING CHANGES

### CHANGES

## Related Issue

Fixes #

Relates to #

## Checklist before merging

- [ ] Tests, documentation, ADR added or updated as needed
- [ ] Followed the [Contributor Guide Steps](https://github.com/defenseunicorns/leapfrogai/blob/main/.github/CONTRIBUTING.md)

2024-09-13 19:10 UTC, gphorvath commented on src/leapfrogai_sdk/audio/audio_pb2.py
It appears the lint is change tab size from 4 to 2 spaces. 4 should be the default for Python

2024-09-13 19:17 UTC, gphorvath requested changes
I would like to clear up the linting issues before merging. There is a lot of this that is a no-op diff in generated proto code, due to some difference in linting config. I am also curious why our linting workflow didn't catch this.

2024-09-13 19:17 UTC, gphorvath commented on src/leapfrogai_sdk/audio/audio_pb2.pyi
In this file it seems like somebody's linter config is undoing the line length limit and removing trailing whitespace.

2024-09-13 19:17 UTC, gphorvath commented on src/leapfrogai_sdk/audio/audio_pb2_grpc.py
Double quotes changing to single quotes - check linter config.

2024-09-15 16:27 UTC, lemonprogis commented on src/leapfrogai_sdk/proto/leapfrogai_sdk/completion/completion.proto
Interesting, I'll take a look but I ran 'make gen-python'. Should there be more granularity added where one would only generate a specific module?

2024-09-15 16:28 UTC, lemonprogis commented on src/leapfrogai_sdk/audio/audio_pb2.py
You are correct, I didn't have pre-commits setup on the repo yet. I reverted the initial commit, setup pre-commit, and then made the changes.

2024-09-15 21:23 UTC, gphorvath commented on src/leapfrogai_sdk/proto/leapfrogai_sdk/completion/completion.proto
I'm not sure, but with the linter tweaks this looks better!

2024-09-15 21:24 UTC, gphorvath approved these changes

2024-09-16 11:57 UTC, jalling97 approved these changes
Thanks for pushing these fixes!

2024-09-16 12:05 UTC, justinthelaw approved these changes
@lemonprogis feel free to smash that merge button!

2024-09-16 12:31 UTC, merged