feat(api): reranking backend integrated in with rag
defenseunicorns/leapfrogai pull request #1090
Opened 2024-09-20 22:21 UTC by CollectiveUnicorn

## Description

### BREAKING CHANGES

### CHANGES

## Related Issue

Fixes #

Relates to #

## Checklist before merging

- [ ] Tests, documentation, ADR added or updated as needed
- [ ] Followed the [Contributor Guide Steps](https://github.com/defenseunicorns/leapfrogai/blob/main/.github/CONTRIBUTING.md)

2024-09-27 13:16 UTC, justinthelaw approved these changes
The MVP implementation logic is sound to me - my only worry is a mix of a) our evals being skewed (too easy, too hard, for certain techniques, etc.) and, b) this re-ranking actually making our eval results worse with a noticable performance hit for the end-user. Not for this PR to solve, just my thoughts!

2024-09-27 16:00 UTC, CollectiveUnicorn commented
Yeah the way the eval results are atm makes things a bit hard to interpret. But performance I think isn't as different as it seems. The baseline was from @jalling97's machine vs mine. The actual time difference between the version without reranking and with reranking is between 7 and 10 seconds over a 51 minute test. Would be better if we got an average per request but I suppose that could be evaluated separately.

2024-09-27 19:30 UTC, jalling97 commented
The `Annotation Relevancy` metric is what I was initially concerned with when I saw the results. I would have expected it to change (in either direction) after reranking was implemented. However, from what I can tell, the top_k chunks (with or without reranking) correspond to the same documents either way, resulting in no practical difference in annotations. Since the `Annotation Relevancy` metric isn't concerned with the order of the documents (just that the ones you expect are in the list of annotations),  the results are pretty much unchanged. 

This is good to note, as the next stage of evals will incorporate the chunk data thanks to #870, so we can better evaluate the rank of the chunks themselves. 

Overall I think this is a net gain and we'll have to see with the next wave of evals what practical difference the reranker has.

2024-09-30 13:36 UTC, jalling97 submitted a review, later dismissed

2024-10-01 17:02 UTC, justinthelaw requested changes

2024-10-01 17:02 UTC, justinthelaw commented on tests/utils/client.py
> +OPENAI_MODEL = "gpt-4o-mini"
Similarly, this should use the `get_openai_model()` method on line 35.

2024-10-01 17:02 UTC, justinthelaw commented on tests/utils/client.py
> +ROOT_URL = "https://leapfrogai-api.uds.dev"
Similarly, this should use the `get_leapfrogai_api_url()` method on line 64.

2024-10-01 17:03 UTC, CollectiveUnicorn commented on tests/utils/client.py
> +ROOT_URL = "https://leapfrogai-api.uds.dev"
Can't use the `get_leapfrogai_api_url` because that's the full url with `openai/v1` at the end

2024-10-01 17:05 UTC, justinthelaw commented on tests/utils/client.py
> +ROOT_URL = "https://leapfrogai-api.uds.dev"
Sorry, my bad! I meant `get_leapfrogai_api_url_base()`

2024-10-01 17:11 UTC, CollectiveUnicorn commented on tests/utils/client.py
> +ROOT_URL = "https://leapfrogai-api.uds.dev"
I actually think its already switched, I just need to get rid of this.

2024-10-01 17:39 UTC, jalling97 submitted a review, later dismissed

2024-10-01 18:21 UTC, justinthelaw commented on tests/integration/api/test_rag_files.py
> +from tests.utils.client import ROOT_URL, client_config_factory
This import should be changed over to the `get_leapfrogai_api_url_base()` method

2024-10-01 18:42 UTC, justinthelaw approved these changes

2024-10-01 19:32 UTC, jalling97 approved these changes

2024-10-01 19:34 UTC, merged