chore: Add workflow badges to README.md
defenseunicorns/leapfrogai pull request #1152
Opened 2024-09-26 10:28 UTC by ChinoUkaegbu

## Description
Adds README badges for workflows that run automatically

### BREAKING CHANGES
None

Relates to #1147

## Checklist before merging

- [X] Tests, documentation, ADR added or updated as needed
- [X] Followed the [Contributor Guide Steps](https://github.com/defenseunicorns/leapfrogai/blob/main/.github/CONTRIBUTING.md)

2024-09-26 16:41 UTC, justinthelaw requested changes
Please see comments made in the original issue #1147 and track status of #1050 before bringing the PR out of draft. Thank you!

2024-10-01 14:18 UTC, justinthelaw commented
#1101 and #1149 _should_ be merged in by today. Those will be the main workflow files that are missing in this branch for badging.

2024-10-01 22:02 UTC, justinthelaw approved these changes

2024-10-01 22:11 UTC, jalling97 approved these changes

2024-10-01 22:48 UTC, merged