refactor: consolidate llama into the monorepo
defenseunicorns/leapfrogai pull request #275
Opened 2024-03-21 03:17 UTC by YrrepNoj

This PR consolidates the functional bits from the following repositories:

https://github.com/defenseunicorns/leapfrogai-backend-llama-cpp-python

2024-03-25 15:33 UTC, gerred approved these changes

2024-03-25 17:47 UTC, jalling97 commented on Makefile
> +	cp build/leapfrogai_api-*.whl packages/llama/
do we need to `pip wheel` the llama-cpp-python dependency listed in `pyproject.toml`? Like we do with the other backends?

2024-03-25 17:53 UTC, YrrepNoj commented on Makefile
> +	cp build/leapfrogai_api-*.whl packages/llama/
Yes. For here and Whisper.


Would you want to push a commit for that?

2024-03-25 17:56 UTC, jalling97 commented on Makefile
> +	cp build/leapfrogai_api-*.whl packages/llama/
Can do!

2024-03-25 19:25 UTC, jalling97 submitted a review, later dismissed

2024-03-26 14:33 UTC, justinthelaw reviewed
All comments are nitpicks for my own understanding! Only made 2 comments on general organizational stuff. Otherwise here is my 3rd and final comment: 

Not sure if I love that the API is a package that is separate from the `src/` (see my other review comment), but I am late to the game. I got an explanation from @jalling97 yesterday and it sounds like there are still some organizational/architectural decisions to be made.

2024-03-26 14:39 UTC, justinthelaw commented on pyproject.toml
>      "llama-cpp-python == 0.2.28",
Additionally, I think `CODEOWNERS.md` should reflect a more granular approach to source code like the `pyproject.toml`'s that live across the repository. For example, the API, API types and their dependencies should have a higher level of control from the core team than additional packages surrounding the API.

2024-03-26 14:44 UTC, justinthelaw commented on pyproject.toml
>      "llama-cpp-python == 0.2.28",
Finally, if we use automated dependency bots to check for vulnerabilities, or to check for code quality and smells, we can add more granular configuration to target each package as wholly separate entities. Understanding we can still attempt the same with a unified `.toml`, and that's probably the whole point of the mono-repo, but a mono-repo can still just be a sum of completely separated components.

2024-03-26 15:31 UTC, jalling97 commented on pyproject.toml
>      "llama-cpp-python == 0.2.28",
agree that we should split the `pyproject.toml` across each package. I've been messing around with that a little bit and can open a PR soon.

Unless I'm mistaken, does dependabot  not monitor `pyproject.toml`? I'm sure there's a way to direct changes there and the requirements.txts instead of just the latter.

2024-03-26 15:32 UTC, justinthelaw commented on pyproject.toml
>      "llama-cpp-python == 0.2.28",
Dependabot does have configuration to look at different `pyproject.toml`'s and other dependency files from what I remember.

2024-03-26 15:35 UTC, gerred commented on pyproject.toml
>      "llama-cpp-python == 0.2.28",
I've noticed in other monorepo approaches the split pyproject.toml between subproject-specific dependencies and optional dev/test dependencies. One of the "ideal" benefits of the monorepo is putting dependencies we write close together and any drift is visible before anything hits main.

I think we lose a lot of the meaning of the monorepo by putting dev/test dependencies that are relevant across every project into their own pyproject.toml files and versioned separately - it feels like we're taking one of the problems we had with many repos before and moved it into the monorepo instead of using the monorepo to alleviate the issue.

2024-03-26 17:31 UTC, YrrepNoj commented on packages/llama/README.md
> +# LeapfrogAI llama-cpp-python Backend
As we discussed in person, we can make this adjustment in a later PR as we cleanup a handful of other things <3

2024-03-26 22:08 UTC, gphorvath requested changes
We should avoid using llama naming convention for shortening llama-cpp-python as this suggests a reference to the model that we aren't using due to licensing restrictions. Propose we fix this before we merge to main.

2024-03-26 22:16 UTC, gphorvath requested changes
Is there a reason we dropped the Dockerfile.gpu file?

2024-03-27 07:20 UTC, jeff-mccoy reviewed
Recommend dropping package variables, considering component composability if needed or a single chart with value overrides per-package since things are so simple. You might also consider just one package with source components as UDS Core does. Helm charts have a few oddities, nothing major, but left comments. 

Big thing for me coming into this was I couldnt get anything to build fully (on a mac), even the make targets with docker had issues. Docs / build setup really has a ways to go. Didnt get to go through the actual python code very much due to all the build/dep issues.

2024-03-27 14:31 UTC, gerred commented on pyproject.toml
> +requires-python = "~=3.11"
@jeff-mccoy This is for dev environments and isn't what gets built into the image (which is 3.11.8 currently, but depends on what's in wolfi for python-3.11). Various pip tools will force the virtualenv to be in that requires-python block and having it soft pinned to 3.11.x keeps us off of 3.12 (no PyTorch support as of today) while allowing us to swap to other 3.11.x venv versions for tests before updating to new 3.11.x versions.

We just had this happen with 3.11.6 and needing to bump to 3.11.8.

2024-03-27 14:34 UTC, andrewrisse commented on packages/llama/chart/values.yaml
> +  # We usually recommend not to specify default resources and to leave this as a conscious
I believe this phrase comes from all the Bitnami charts, although I also disagree and think reasonable defaults should be specified.
There was some discussion about it here: https://github.com/bitnami/charts/issues/11555#issuecomment-1204948641

2024-03-27 14:36 UTC, gerred commented on packages/llama/chart/templates/deployment.yaml
> +  replicas: {{ .Values.replicaCount }}
yes, llama.cpp does not support concurrency as of today and we haven't implemented any intelligent load balancing/request queueing. Having that will enable HA.

2024-03-27 14:42 UTC, justinthelaw commented on pyproject.toml
> +requires-python = "~=3.11"
In our past deployments and testing (cc: @CollectiveUnicorn), we've had Python pinned at 3.11.6 (venv, pyenv, etc.), per our own hardened 3.11.6 python image. @gerred @YrrepNoj can you explain further why we are loosening the 3.11.6 pin?

2024-03-27 14:44 UTC, justinthelaw commented on packages/whisper/zarf.yaml
> +    value: "###ZARF_PKG_TMPL_IMAGE_VERSION###"
We have a release-please configuration example elsewhere that will be implemented later on. Additionally, we should be removing the `IMAGE_VERSION` (and `NAME`, where applicable) out of the zarf.yaml since it really only needs to be controlled in the zarf-config.yaml using release-please's manifest.

2024-03-27 14:45 UTC, justinthelaw commented on packages/llama/chart/templates/NOTES.txt
> +Please enjoy your model! - Defense Unicorns
I added / modified this originally during my helm templataing tests in the model skeleton. Agree that this should be removed.

2024-03-27 14:51 UTC, justinthelaw commented on packages/llama/chart/templates/configmap.yaml
> +apiVersion: v1
I believe that these are picked up by kiwigrid k8s-sidecar and then placed into the `leapfrogai-api`'s pre-defined config folder so that the API is aware of what models/modalities are in the cluster.

2024-03-27 14:53 UTC, justinthelaw commented on packages/llama/chart/values.yaml
> +  # We usually recommend not to specify default resources and to leave this as a conscious
We had this discussion while @CollectiveUnicorn and I were at BeastCode, and as a team as well. There should be defaults taken in from the zarf values, but delivery engineers ultimately decide what resources are required depending on factors such as the model size, model architecture, and backend inferencing engine capabilities.

2024-03-27 14:55 UTC, gerred commented on packages/llama/chart/templates/configmap.yaml
> +apiVersion: v1
This being the TOML file though means it's out of date, I think we can get rid of this.

2024-03-27 14:58 UTC, justinthelaw commented on packages/whisper/whisper-values.yaml
> +# NOTE: This is not a typo, the request and limit values NEED to be the same
These should probably be `NVIDIA_GPU_REQUESTS` and `NVIDIA_GPU_LIMITS`. Delivery engineers like myself should know what this means, and if not, then there can be a zarf variable description field to further clarify.

2024-03-27 15:01 UTC, justinthelaw commented on packages/llama/chart/templates/deployment.yaml
> +    type: Recreate
Recreate is likely a holdover (and still useful) for smoother dev deployments. We can change the type later on in production via variable or something? Not an expert on best pattern to switch this at deploy time with Zarf or UDS, or whether that is even allowed/good idea.

2024-03-27 15:15 UTC, YrrepNoj commented on packages/whisper/zarf.yaml
> +    value: "###ZARF_PKG_TMPL_IMAGE_VERSION###"
I wasn't keeping this as a PKG_TMPL to make releasing easier on myself, I was keeping it as a PKG_TMPL as a way to build & test local changes without having to either
1) Manually change versions in the zarf.yaml/values.yaml
OR
2) Creating a new version of the image/package that are distinctly different from the upstream versions with the same tag.

@jeff-mccoy I'll find some time to bother you more on how to do this better.

2024-03-27 15:19 UTC, YrrepNoj commented on packages/llama/chart/templates/configmap.yaml
> +    leapfrogai: sparkle
The label key is used by [kiwigrid](https://github.com/defenseunicorns/leapfrogai/blob/70e0bdfd659169174d6e6dfb7864faded7ab0d00/packages/api/chart/templates/api/deployment.yaml#L26) to find relevant configmaps for the API.

2024-03-27 15:24 UTC, YrrepNoj commented on packages/whisper/whisper-values.yaml
> +# NOTE: This is not a typo, the request and limit values NEED to be the same
@justinthelaw I left the comment there because I explicitly want them to be the same. The pod enter a crashloop if the request & limit for GPUs is not the same value.

I don't hate `GPU_CAPACITY` but I don't love it either. I'll noodle on a name that can potentially make this less confusing.

2024-03-27 15:32 UTC, justinthelaw commented on packages/whisper/whisper-values.yaml
> +# NOTE: This is not a typo, the request and limit values NEED to be the same
Yes, you are right! Although, we should probably just specify `limits` then because `requests` are actually not necessary - it'd reduce confusion and extra lines of code everywhere: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

2024-03-27 15:39 UTC, YrrepNoj commented on pyproject.toml
> +requires-python = "~=3.11"
@justinthelaw 

In this specific case it is because the `vLLM` Dockerfile does not actually have python `3.11.6` installed. Somehow we were getting away with using python `3.10.12` before but now that we are installing leapfrogai as a build from the pyproject instead of as a dep that we download from pypi the `requires-python==3.11.6` was actually taking affect.

2024-03-27 15:41 UTC, gerred commented on packages/llama/chart/templates/deployment.yaml
> +    type: Recreate
we probably could/should go rollingupdate here with the right surge/unavailable settings and make it configurable, but we were finding more often than not in deployments there's no GPUs to rolling update to.

2024-03-27 15:42 UTC, YrrepNoj commented on packages/llama/chart/templates/configmap.yaml
> +apiVersion: v1
These configmaps are being used and are still relevant. They are not directly mounted but are consumed via sidecar into our API deployment. [Here](https://github.com/defenseunicorns/leapfrogai/blob/70e0bdfd659169174d6e6dfb7864faded7ab0d00/packages/api/chart/templates/api/deployment.yaml#L19) is where that sidecar deployment is specified.

2024-03-27 15:46 UTC, YrrepNoj commented on packages/llama/chart/templates/deployment.yaml
> +      imagePullSecrets:
No it's not needed. I will remove.

2024-03-28 04:46 UTC, YrrepNoj commented on pyproject.toml
> +requires-python = "~=3.11"
Created this issue so that we can resolve this conversation for now.

2024-03-28 05:01 UTC, YrrepNoj commented on packages/whisper/zarf.yaml
> +    value: "###ZARF_PKG_TMPL_IMAGE_VERSION###"
Creating this issue so that we can resolve this conversation for now.

https://github.com/defenseunicorns/leapfrogai/issues/326

2024-03-28 05:04 UTC, YrrepNoj commented on packages/whisper/zarf.yaml
> +  version: 0.0.1
I resolved this nit by updating the version to `0.1.0` and created this issue so we can resolve the overall issue of better version updating.

https://github.com/defenseunicorns/leapfrogai/issues/326

2024-03-28 05:23 UTC, YrrepNoj commented on packages/llama/chart/templates/serviceaccount.yaml
> +{{- if .Values.serviceAccount.create -}}
I don't believe there was a purpose, these have been removed.

2024-03-28 05:23 UTC, YrrepNoj commented on packages/llama/chart/templates/hpa.yaml
> +{{- if .Values.autoscaling.enabled }}
These have been removed.

2024-03-28 05:48 UTC, YrrepNoj commented on packages/llama/chart/templates/deployment.yaml
> +    type: Recreate
Updated this to `RollingUpdate` for now

2024-03-28 05:50 UTC, YrrepNoj commented on packages/llama/chart/values.yaml
> +  # We usually recommend not to specify default resources and to leave this as a conscious
https://github.com/defenseunicorns/leapfrogai/issues/327

2024-03-28 14:47 UTC, gphorvath approved these changes

2024-03-28 14:48 UTC, merged