Monorepo local UDS deployment and README Updates
defenseunicorns/leapfrogai pull request #322
Opened 2024-03-26 21:13 UTC by jalling97

- Adds uds bundles specifically for deploying locally created zarf packages
- Updates the README to direct people to deploy via the standard uds deployments or how to build the zarf packages locally

2024-03-27 00:01 UTC, barronstone reviewed
Asking questions and making a few recommendations based on my understanding. Don't consider them "must do's" just because I said something... Please let me know where I'm wrong or missing context :-)

2024-03-27 00:22 UTC, gphorvath commented on uds/cpu/uds-config.yaml
> +    requests_cpu: 0
The 0 values actually are important because they allow the controller to decide how much to allocate to the workload.

2024-03-27 00:22 UTC, gphorvath commented on uds/cpu/uds-bundle.yaml
> +  # Text Embeddings Model
text embeddings will be required when we reintroduce RAG.

2024-03-27 00:22 UTC, gphorvath commented on uds/cpu/uds-config.yaml
> +  text-embeddings:
text embeddings will be required when we reintroduce RAG.

2024-03-27 00:22 UTC, gphorvath commented on uds/cpu/uds-config.yaml
> +    gpu_enabled: "false"
This was done to minimize drift between our CPU and GPU configurations and ensure that a change in the underlying default doesn't cause a CPU package to inadvertently become a GPU package.

2024-03-27 00:22 UTC, gphorvath commented on uds/cpu/uds-config.yaml
> +  # rag:
Ideally we would keep these values somewhere obvious so when we add RAG back in we can easily reproduce the configuration.

2024-03-27 00:22 UTC, gphorvath commented on uds/cpu/uds-bundle.yaml
> +  # RAG Backend
Ideally we would keep these values somewhere obvious so when we add RAG back in we can easily reproduce the configuration.

2024-03-27 00:22 UTC, gphorvath commented on uds/gpu/uds-config.yaml
> +  vllm: # default is synthia-7b
This comment should be removed since it's not set in this config file.

2024-03-28 14:25 UTC, gerred commented on uds/cpu/uds-config.yaml
> +    requests_cpu: 0
@barronstone yes this just allows it to expand for Kubernetes scheduling without getting OOM/resource killed.

2024-04-01 19:00 UTC, jalling97 commented
There are a lot of extra commits now that I've rebased this branch. This was done so it could be merged directly to `main` instead of the `consolidate-workflows` branch.

2024-04-03 14:23 UTC, justinthelaw reviewed
I know this is a WIP, but figured I should provide some pointers since the GPU deployment may not function nor perform as intended with any of these published packages.

2024-04-03 14:23 UTC, justinthelaw commented on uds-bundles/dev/gpu/uds-config.yaml
> +  leapfrogai-ui:
The UI will crash vLLM on summarization (due to an error in the API) and also underperform severely on RAG (due to an incorrect prompt setup). Fixes that are merged into the UI in the following branch fix those things: https://github.com/defenseunicorns/leapfrogai-ui

2024-04-03 14:23 UTC, justinthelaw commented on uds-bundles/dev/gpu/uds-config.yaml
> +  rag:
Reminder to bring in the following RAG fixes from this branch: https://github.com/defenseunicorns/leapfrogai-backend-rag/tree/pre-uds-beast-code-deploy

2024-04-03 14:44 UTC, jalling97 commented on uds-bundles/dev/gpu/uds-config.yaml
> +  leapfrogai-ui:
Do we need to cut a new release of the UI then? At the moment since the UI isn't pulled into the monorepo I'm still pulling release `0.3.5` from ghcr instead of building it locally. The same goes for RAG since it's not a part of this repo yet.

2024-04-03 14:50 UTC, jalling97 commented on uds-bundles/dev/gpu/uds-config.yaml
> +  vllm:
Could a short-term fix be as simple as removing the `tensor_parallel_size` parameter for the time being? Since there are a number of vllm changes to pull in, I'm wondering if it makes sense to have that be a separate PR. What are your thoughts?

2024-04-03 15:44 UTC, gerred commented on uds-bundles/dev/gpu/uds-config.yaml
> +  leapfrogai-ui:
Alternately if we know when the new UI will move to the monorepo, we leave the code in but disable the UI and RAG by default as these variables (and for sure the RAG ones) will get deprecrated anyway.

RAG is a little more of a drawn out story since it's being replaced with assistants.

2024-04-03 15:56 UTC, gerred commented on uds-bundles/dev/gpu/uds-config.yaml
> +  rag:
This will eventually get deprecated correct?

2024-04-03 16:36 UTC, gerred submitted a review, later dismissed

2024-04-05 16:32 UTC, YrrepNoj requested changes

2024-04-05 16:32 UTC, YrrepNoj commented on .gitignore
> +packages/*/.model
We should just ignore every `.model/` directory.
```suggestion
.model/
```

2024-04-05 16:32 UTC, YrrepNoj commented on Makefile
> +LOCAL_VERSION ?= dev
I would suggest reverting this back to what it was before and adding extra details in the README.md to set the local_version to dev if they are trying to build the dev bundles.

2024-04-05 16:32 UTC, YrrepNoj commented on uds-bundles/dev/cpu/uds-bundle.yaml
> +    path: ../../../packages/api/
Double check that the instructions in the README or Makefile change the output of the zarf packages to this directory.

At the moment I think they would exist at the root of the repo.

2024-04-05 16:32 UTC, YrrepNoj commented on packages/llama-cpp-python/chart/templates/deployment.yaml
> +              value: {{ (quote .Values.gpuEnabled) | default "false"}}
Our llama package is not GPU enablable right now.
```suggestion

```

2024-04-05 16:32 UTC, YrrepNoj commented on packages/llama-cpp-python/chart/values.yaml
> +gpuEnabled: false
```suggestion

```

2024-04-05 20:09 UTC, jalling97 commented on .gitignore
> +packages/*/.model
changed :+1:

2024-04-05 20:09 UTC, jalling97 commented on Makefile
> +LOCAL_VERSION ?= dev
reverted :+1:

2024-04-05 20:10 UTC, jalling97 commented on uds-bundles/dev/cpu/uds-bundle.yaml
> +    path: ../../../packages/api/
I accidentally removed the `-o` flag from the zarf create commands in `Makefile` during my last merge; those have been added back in.

2024-04-05 20:10 UTC, jalling97 commented on packages/llama-cpp-python/chart/values.yaml
> +gpuEnabled: false
removed :+1:

2024-04-08 18:15 UTC, YrrepNoj requested changes
Mostly small changes, this is looking really good!

2024-04-08 18:15 UTC, YrrepNoj commented on uds-bundles/dev/cpu/uds-config.yaml
> +variables:
The variables here for `leapfrogai-ui` and `rag` make sense since we are using the other zarf packages for them.

`llama-cpp-python` does not require any variables.

`whisper`, `text-embeddings`, and `vllm` only have the `GPU_LIMIT` variable and can be setup like this:
```
  whisper:
    gpu_limit: [0 OR 1]
  text-embeddings:
    gpu_limit: [0 OR 1]
  vllm:
    gpu_limit: 1
```

Let me know if this doesn't make sense and we can talk through it more.

2024-04-08 18:55 UTC, YrrepNoj approved these changes
LGTM!

2024-04-08 19:58 UTC, merged