UDS Documentation Updates
defenseunicorns/leapfrogai pull request #328
Opened 2024-03-28 15:54 UTC by jalling97

Quick PR to update some the documentation:
- Point people to use UDS to deploy LFAI
- Deprecate instructions for k8s deployment that doesn't use UDS
- Minor other doc fixes

2024-03-29 15:31 UTC, justinthelaw commented on README.md
> +UDS is the preferrred method for a full local deployment of LeapfrogAI. Instructions can be found on the [LeapfrogAI Documentation Site](https://docs.leapfrog.ai/docs/).
Might be a good idea to mention that this is a Kubernetes deployment, even if our linked docs website mentions it later on.

2024-03-29 15:45 UTC, jalling97 commented on README.md
> +UDS is the preferrred method for a full local deployment of LeapfrogAI. Instructions can be found on the [LeapfrogAI Documentation Site](https://docs.leapfrog.ai/docs/).
Updated!

2024-03-29 16:28 UTC, YrrepNoj requested changes

2024-03-29 16:28 UTC, YrrepNoj commented on README.md
> +  - [Tadpole](#tadpole)
We should remove the tadpole subsection, Tadpole is something we won't be supporting for a while.

2024-03-29 16:28 UTC, YrrepNoj commented on README.md
> +> Available Backends:
We should update these to link to their place within the monorepo

2024-03-29 16:28 UTC, YrrepNoj commented on website/content/en/docs/local deploy guide/quick_start.md
> +- [K3D](https://k3d.io/)
k3d implies Docker but their instructions don't have you install docker. we can list `Docker` here to be explicit.

I wouldn't hate it if we didn't though.

2024-03-29 16:28 UTC, YrrepNoj commented on website/content/en/docs/local deploy guide/quick_start.md
> +It is recommended to run UDS as root.
Hmm? I don't think this is true?

2024-03-29 16:28 UTC, YrrepNoj commented on website/content/en/docs/local deploy guide/quick_start.md
> +`whisper` can run without without GPU scheduling - just turn off the `GPU_ENABLED` boolean.
```suggestion
`whisper` can run without GPU scheduling - just set the `GPU_LIMIT` value to `0`.
```

2024-03-29 16:28 UTC, YrrepNoj commented on website/content/en/docs/local deploy guide/quick_start.md
> +It is recommended to run UDS as root.
As far as I know, the only time root is recommended (required) is when you are installing a `k3s` cluster when running the `zarf init` command.

2024-03-29 16:28 UTC, YrrepNoj commented on website/content/en/docs/local deploy guide/quick_start.md
> +uds deploy k3d-core-istio-dev:0.14.1
Maybe add a comment to check if a newer version exists.

2024-03-29 16:38 UTC, gphorvath commented on website/content/en/docs/local deploy guide/quick_start.md
> +- [K3D](https://k3d.io/)
yeah we probably should list it

2024-03-29 20:29 UTC, CollectiveUnicorn submitted a review, later dismissed

2024-03-29 20:56 UTC, jalling97 commented
As a last minute edit, I removed references to Tadpole from the deploy instructions in the docs and moved the Tadpole specific instructions to a draft so that it won't render on the site. This way if we do support Tadpole again the instructions will still be there but not actually visible. Let me know if that's a sufficient approach for the time being.

2024-03-29 21:13 UTC, CollectiveUnicorn approved these changes

2024-03-29 21:21 UTC, YrrepNoj commented on website/content/en/docs/local deploy guide/quick_start.md
> +uds deploy k3d-core-istio-dev:0.14.1      # be sure to check if a newer version exists
This is a public image so that shouldn't be a hard requirement. We could always suggest it as a best practice still.

2024-03-29 21:34 UTC, justinthelaw commented on website/content/en/docs/local deploy guide/quick_start.md
> +uds deploy k3d-core-istio-dev:0.14.1      # be sure to check if a newer version exists
Hm, I actually tried it out and I wasn't able to pull it without logging in with a valid PAT.

2024-04-01 13:36 UTC, jalling97 commented on website/content/en/docs/local deploy guide/quick_start.md
> +uds deploy k3d-core-istio-dev:0.14.1      # be sure to check if a newer version exists
I personally haven't run into that issue, but I can add some text. I'm assuming the PAT needs at least `read:packages` access?

2024-04-01 13:41 UTC, justinthelaw commented on website/content/en/docs/local deploy guide/quick_start.md
> +uds deploy k3d-core-istio-dev:0.14.1      # be sure to check if a newer version exists
Hm, I realized my PAT had expired on Friday and I had to make a new PAT and re-login via CLI in order to pull packages from GHCR. It is possible an expired PAT will cause a 403 error purely because it tries to authorize if a PAT is available in cred store. I think this is fine without the PAT!

2024-04-01 13:42 UTC, justinthelaw approved these changes

2024-04-01 14:22 UTC, YrrepNoj approved these changes

2024-04-01 14:51 UTC, merged