ADR: Database ADR (0003)
defenseunicorns/leapfrogai pull request #335
Opened 2024-04-02 17:01 UTC by gphorvath

2024-04-17 17:50 UTC, gerred approved these changes

2024-04-17 19:14 UTC, gerred approved these changes

2024-04-17 19:22 UTC, YrrepNoj requested changes

2024-04-17 19:22 UTC, YrrepNoj commented on .github/workflows/e2e.yaml
> +      - "!adr/**"
The `.github/workflow/e2e-shim.yaml` needs to be updated with the inverse of this path.

2024-04-17 19:29 UTC, gphorvath commented on .github/workflows/e2e.yaml
> +      - "!adr/**"
fixed

2024-04-18 15:04 UTC, gerred submitted a review, later dismissed

2024-04-18 18:13 UTC, closed without merging