chore: bring ui into monorepo
defenseunicorns/leapfrogai pull request #349
Opened 2024-04-03 19:04 UTC by andrewrisse

Integrates the "new UI (lfaiui) into the monorepo.

New naming convention is "leapfrogai-ui" 

Includes Keycloak code that will not work until Supabase is deployed in our clusters.

We will leave leapfrog-demo deployed as is since it does not use Keycloak yet.

2024-04-04 00:15 UTC, gerred requested changes
doing some initial change requests since this is gonna be a chonky review

2024-04-04 00:15 UTC, gerred commented on packages/ui/chart/templates/ui/deployment.yaml
> +              memory: '5Gi'
5gb RAM req/limits seems high esp. with a 0.5/1 vCPU req for the UI, has this been benchmarked? Don't want resource exhaustion if it's unnecessary.

2024-04-04 00:15 UTC, gerred commented on packages/ui/chart/templates/ui/service.yaml
> +kind: ServiceAccount
SA should be unnecessary here

2024-04-04 00:17 UTC, gerred commented on src/leapfrogai_ui/package.json
> +	"type": "module",
i might be out of date here, but does this still force the mjs extension on entrypoints? if it does I'm only seeing that in husky, does vite just work?

2024-04-04 14:11 UTC, andrewrisse commented on packages/ui/chart/templates/ui/deployment.yaml
> +              memory: '5Gi'
This was a copy paste from the previous UI, agree it seems high. I'll lower it, but no it has not been benchmarked (at least with the new UI). How about 1Gi/2Gi?

2024-04-04 14:12 UTC, andrewrisse commented on packages/ui/chart/templates/ui/service.yaml
> +kind: ServiceAccount
Copy paste from previous UI, removing.

2024-04-04 14:16 UTC, andrewrisse commented on src/leapfrogai_ui/package.json
> +	"type": "module",
btw husky no longer works now that this is moved into the monorepo, we may want to create a new story to integrate at the monorepo version (if we want husky as a team): https://dev.to/mimafogeus2/enforce-git-hooks-in-monorepos-with-husky-but-how-3fma

I was using it for Trufflehog checks, linting/prettier, tests, and commitlint.

2024-04-04 14:52 UTC, gphorvath commented on packages/ui/chart/templates/ui/deployment.yaml
> +              memory: '5Gi'
should we just set to 0 for now?

2024-04-04 16:11 UTC, andrewrisse commented
> If Supabase is a resource we are sharing between the API DB and UI, do we need to move the Supabase directory up a level? Not totally sure how that works. @andrewrisse

That directory is for running Supabase locally with the UI although it does contain some migrations the frontend needs when setting up Supabase. I wonder if these could be moved up to a parent directory.

2024-04-04 18:10 UTC, andrewrisse commented
also closes #307

2024-04-04 18:12 UTC, andrewrisse commented on packages/ui/chart/templates/ui/deployment.yaml
> +              memory: '5Gi'
why 0? wouldn't it not run then?

2024-04-04 18:19 UTC, gphorvath commented on packages/ui/chart/templates/ui/deployment.yaml
> +              memory: '5Gi'
I think 0 means no limit

https://kubesphere.io/blogs/understand-requests-and-limits-in-kubernetes/#:~:text=If%20it%20is%20set%20to,that%20of%20limits%20by%20default.

2024-04-04 20:12 UTC, andrewrisse commented on packages/ui/chart/templates/ui/deployment.yaml
> +              memory: '5Gi'
I like to live dangerously

2024-04-05 12:37 UTC, gerred commented
> > If Supabase is a resource we are sharing between the API DB and UI, do we need to move the Supabase directory up a level? Not totally sure how that works. @andrewrisse
> 
> That directory is for running Supabase locally with the UI although it does contain some migrations the frontend needs when setting up Supabase. I wonder if these could be moved up to a parent directory.
> 
> @gerred I'm thinking consolating the supabase migrations and setup should be a separate issue once we have a sucessful deployment. I still need this in my section of the repo until that's in place

Agreed on migrations later.

2024-04-05 14:17 UTC, andrewrisse commented on packages/ui/chart/templates/ui/deployment.yaml
> +              memory: '5Gi'
@gerred do you have an opinion on the limits here?

2024-04-05 14:19 UTC, gerred commented on packages/ui/chart/templates/ui/deployment.yaml
> +              memory: '5Gi'
This is really just eligibility for limits killing w/ pods - I'm fine with setting it to 0 until we have some Prometheus metrics to help dial it in.

2024-04-05 17:54 UTC, YrrepNoj commented on src/leapfrogai_ui/.github/workflows/ISSUE_TEMPLATE/bug.md
Here and else-where: These files should be moved to the root `.github` or removed completely.

2024-04-05 17:54 UTC, YrrepNoj commented on src/leapfrogai_ui/.husky/commit-msg
> +npx --no -- commitlint --edit $1
Could the husky pre-commit things be merged into the existing `.pre-commit-config.yaml`?

2024-04-08 22:28 UTC, andrewrisse commented on src/leapfrogai_ui/.husky/commit-msg
> +npx --no -- commitlint --edit $1
I can make that a separate story and attempt

2024-04-08 22:31 UTC, andrewrisse commented on src/leapfrogai_ui/.github/workflows/ISSUE_TEMPLATE/bug.md
deleted for now, we should have a separate discussion to decide how we want to integrate a release pipeline.

2024-04-09 15:32 UTC, gerred approved these changes

2024-04-09 15:32 UTC, gerred commented
Read through all the Svelte parts, looks like a really good start. We should consider something a little more robust for migrations.

2024-04-09 15:46 UTC, YrrepNoj commented on src/leapfrogai_ui/.husky/pre-commit
> +    npm run test
Is this something we can create a workflow for that triggers on PRs?

2024-04-10 16:01 UTC, andrewrisse commented on src/leapfrogai_ui/.husky/pre-commit
> +    npm run test
Removed husky, will re-attack pre-commit checks for monorepo in separate story

2024-04-11 15:43 UTC, gerred approved these changes

2024-04-15 15:36 UTC, merged