Pyproject refactor
defenseunicorns/leapfrogai pull request #361
Opened 2024-04-05 15:47 UTC by jalling97

- Breaks up the `pyproject.toml` at the root of the monorepo into multiple pyprojects. This way, each component of LFAI can be more easily built as its own package. It also minimizes the number of dependencies needed per package which should make them a little bit lighter weight.

2024-04-10 13:54 UTC, gerred commented
Took a quick early review, some new stuff to merge in from main for you, generally looking good.

2024-04-15 15:11 UTC, justinthelaw requested changes

2024-04-15 15:11 UTC, justinthelaw commented on packages/vllm/pyproject.toml
> +version = "0.1.0"
Just want to make sure - should this be `0.6.1`? How are we doing versioning for these continuing packages as compared ot our latest `0.6.1` release? @jalling97 @YrrepNoj

2024-04-15 15:11 UTC, justinthelaw commented on packages/whisper/Dockerfile
>  RUN ct2-transformers-converter --model ${MODEL_NAME} --output_dir .model --copy_files tokenizer.json --quantization float32
On line 11, above this segment, we install `transformers[torch]` and `ctranslate2` from outside of a pinned (with hashes generated) requirements file. I think we should keep these `dev` requirements within the `pyproject.toml` and use them here too. Both for consistency in case of breaking changes and slightly better supply chain control. This comment applies to any other Dockerfiles where we do this.

**Reference:**
```
9   # download and covnert OpenAI's whisper base
10  ARG MODEL_NAME=openai/whisper-base
11  RUN pip install transformers[torch]
12  RUN pip install ctranslate2
```

2024-04-15 15:11 UTC, justinthelaw commented on src/leapfrogai_api/pyproject.toml
> +version = "0.6.0"
Update version.

2024-04-16 12:59 UTC, jalling97 commented on packages/vllm/pyproject.toml
> +version = "0.1.0"
Good point. I believe @YrrepNoj did tell me that everything should be bumped to `0.6.1`, so I'll set up dynamic versioning so they can all be the same.

2024-04-16 20:14 UTC, jalling97 commented on packages/whisper/Dockerfile
>  RUN ct2-transformers-converter --model ${MODEL_NAME} --output_dir .model --copy_files tokenizer.json --quantization float32
So what I ended up doing was pinning versions for `transformers[torch]` and `ctranslate2` in the whisper `pyproject.toml` and within the  `Dockerfile` pull those versions in and build the wheels locally. Instead of installing the model download dependencies outside of the venv, I just uninstalled them after downloading the model and before installing the `lfai-whisper` wheel. This is because I was having trouble with the pathing. It gets us the same outcome albeit slightly slower (by a few seconds, so I wasn't too concerned about it).

2024-04-16 21:07 UTC, jalling97 commented on src/leapfrogai_sdk/chat/__init__.py
As we discussed earlier, since we make the switch to an `src` structure, we technically should have needed them in order to be able to properly handle imports in the API. I'm still trying to figure out why it has been working despite the few missing `__init__.py` files. It may have something to do with the API being treated like a namespace, but I'm still figuring that one out. Ultimately, if we're installing each component as a standard Python package, then these `__init__.py` should be present.

2024-04-16 22:46 UTC, justinthelaw approved these changes

2024-04-18 14:50 UTC, gphorvath approved these changes

2024-04-18 15:12 UTC, gerred approved these changes

2024-04-18 15:20 UTC, merged