Add supabase deployment
defenseunicorns/leapfrogai pull request #380
Opened 2024-04-10 23:58 UTC by CollectiveUnicorn

2024-04-15 22:24 UTC, YrrepNoj commented on packages/supabase/supabase-kubernetes/charts/supabase/README.md
> +# Supabase for Kubernetes with Helm 3
@CollectiveUnicorn The [upstream chart](https://github.com/supabase-community/supabase-kubernetes/blob/main/charts/supabase/README.md) that this was taken from seems very customizable, is there any way for us to benefit from the team of devs maintaining the upstream chart and customize everything we need with the `values.yaml` and `uds override` features?

2024-04-27 00:51 UTC, CollectiveUnicorn commented on packages/supabase/supabase-kubernetes/charts/supabase/README.md
> +# Supabase for Kubernetes with Helm 3
Done

2024-04-27 17:55 UTC, justinthelaw reviewed
Just some initial questions for my own understanding - looks great so far!

2024-04-27 17:55 UTC, justinthelaw commented on packages/supabase/zarf.yaml
> +variables:
For the variables that start with `ENABLE_`, are those picked up automatically somewhere? I don't see `###ZARF_VAR_` anywhere in the values file, especially the storage section for persistence volumes and volume claims.

2024-04-27 17:55 UTC, justinthelaw commented on packages/supabase/manifests/declarative-conf-configmap.yaml
> +        password: {{SUPABASE_DASHBOARD_PASSWORD}}
When do these `SUPABASE_` prefixed variables get created? At application time or do they get produced somewhere else for consumption here?

I see that the `DASHBOARD` has a Secret resource we can apply, but what about the others? This also sort of ties into my comment later on about the Zarf variables that don't map to any of the values keys. If we, for say, enable REST, wouldn't that mean a Secret would need to be generated?

2024-04-29 16:54 UTC, CollectiveUnicorn commented on packages/supabase/manifests/declarative-conf-configmap.yaml
> +        password: {{SUPABASE_DASHBOARD_PASSWORD}}
`###ZARF_CONST_DASHBOARD_USERNAME###` is created at creation, as its a const. `{{SUPABASE_DASHBOARD_PASSWORD}}` is randomly generated at deployment via the secret config `supabase-dashboard-secret.yaml` and picked up in `bitnami-values.yaml` under `kong`

2024-04-29 17:56 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +variables:
They should be in `bitnami-values.yaml` for each component. They were added after the initial commit so maybe they weren't in there when you checked. But each component should have some variable of `ENABLE_` under their `enabled: ` property like `###ZARF_VAR_ENABLE_KONG###`.

2024-04-29 17:57 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +variables:
They aren't configurable in `bitnami-values-basic.yaml` because that's for bootstrapping particular pieces of Supabase that will break without this step.

2024-04-29 18:05 UTC, justinthelaw submitted a review, later dismissed

2024-04-29 20:07 UTC, justinthelaw approved these changes

2024-04-29 21:40 UTC, andrewrisse commented
closes #306

2024-04-30 18:20 UTC, YrrepNoj requested changes

2024-04-30 18:35 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +    default: "lfaiui"
Need to change this to leapfrogai, all leapfrog apps will fall under this client id.

2024-04-30 18:35 UTC, CollectiveUnicorn commented on packages/supabase/manifests/declarative-conf-configmap.yaml
> +        username: ###ZARF_CONST_DASHBOARD_USERNAME###
Need to move into values.

2024-04-30 18:37 UTC, CollectiveUnicorn commented on .github/workflows/e2e.yaml
> +            uds zarf tools kubectl create secret generic supabase-keycloak-secret --from-literal=secret='YOUR_KEYCLOAK_CLIENT_SECRET' -n leapfrogai
It is a secret that is supposed to already exist in keycloak at startup. This should not be a dependency on running tests, will remove.

2024-04-30 18:41 UTC, CollectiveUnicorn commented on packages/supabase/bitnami-values-basic.yaml
It is a values file for the same chart. Its not the same as everything is disabled but the jwt token generation job and the service account creation that it depends on.

There's a PR to shrink this down further https://github.com/defenseunicorns/leapfrogai/issues/456 that goes into more detail into why this exists.

2024-04-30 18:42 UTC, CollectiveUnicorn commented on packages/supabase/bitnami-values-basic.yaml
Will try modifying this to use the main values file.

2024-04-30 18:43 UTC, CollectiveUnicorn commented on packages/supabase/README.md
> +- `https://lfaiui.uds.dev/`
@andrewrisse Going to remove this from here, so it'll need to go into the UI

2024-04-30 18:44 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +    default: "lfaiui"
@andrewrisse this val will need to be used in the UI instead of `lfaiui`

2024-04-30 19:12 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +  - name: IMAGE_VERSION
I have removed this

2024-04-30 19:13 UTC, CollectiveUnicorn commented on .github/workflows/e2e.yaml
> +            uds zarf tools kubectl create secret generic supabase-keycloak-secret --from-literal=secret='YOUR_KEYCLOAK_CLIENT_SECRET' -n leapfrogai
This has been removed.

2024-04-30 19:17 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +    default: "lfaiui"
This has been updated.

2024-04-30 19:18 UTC, CollectiveUnicorn commented on packages/supabase/README.md
> +- `https://lfaiui.uds.dev/`
Removed references to UI will try to use more generic communication that is not specific to the UI but applicable to applications in general integrating with Supabase.

2024-04-30 19:19 UTC, CollectiveUnicorn commented on Makefile
> +	uds zarf package create packages/supabase -o packages/supabase --registry-override=ghcr.io=localhost:5000 --insecure --set IMAGE_VERSION=${LOCAL_VERSION} --confirm
Opted to still use the local registry and make use of the `initial-push.sh` for that purpose. @YrrepNoj let me know if this is an acceptable solution.

2024-04-30 19:20 UTC, CollectiveUnicorn commented on packages/supabase/scripts/clean-cluster.sh
This has been deleted.

2024-04-30 19:21 UTC, CollectiveUnicorn commented on packages/supabase/scripts/initial-push.sh
This is now use during the make `build-supabase` step

2024-04-30 19:28 UTC, CollectiveUnicorn commented on packages/supabase/manifests/declarative-conf-configmap.yaml
> +        username: ###ZARF_CONST_DASHBOARD_USERNAME###
The const is now used for env vars in the values file instead of in the configmap directly.

2024-04-30 20:19 UTC, CollectiveUnicorn commented on packages/supabase/uds-package.yaml
> +kind: Package
Added templating and new values to `bitnami-values.yaml` under `Values.leapfrogai`

2024-04-30 20:53 UTC, CollectiveUnicorn commented on packages/supabase/bitnami-values.yaml
It now contains only the things that we're modifying and overlays on top of the original values file.

Resolving this: https://github.com/defenseunicorns/leapfrogai/issues/456

2024-05-01 16:22 UTC, YrrepNoj requested changes
A few more comments & observations. I will pull this down and follow the README shortly so I may have a few more comments on that file later.

2024-05-01 16:22 UTC, YrrepNoj commented on packages/ui/chart/templates/ui/deployment.yaml
> +                  name: supabase-bootstrap-jwt
Question; what changed for secretKeyRef to change?

2024-05-01 16:22 UTC, YrrepNoj commented on uds-bundles/dev/cpu/uds-config.yaml
> +        component: kong
This config is to set Zarf package variables but these variables don't exist in the `supabase/zarf.yaml`.
This looks to be the pathing of a manifest, were you intending this to be an 'UDS override`?

NOTE: Same comment for the other `uds-config.yaml`

2024-05-01 16:22 UTC, YrrepNoj commented on packages/supabase/bitnami-values.yaml
Are you still intending on slimming this values file down?

2024-05-01 16:22 UTC, YrrepNoj commented on packages/supabase/chart/templates/supabase-dashboard-secret.yaml
> +{{- if .Values.leapfrogai.testing }}
Let's pair up on this and see if we can come up with a way to abuse Zarf to do this better 🤔

2024-05-01 16:53 UTC, CollectiveUnicorn commented on packages/ui/chart/templates/ui/deployment.yaml
> +                  name: supabase-bootstrap-jwt
Prevents crashing in the UI due to the helm chart name change

2024-05-01 16:54 UTC, CollectiveUnicorn commented on uds-bundles/dev/cpu/uds-config.yaml
> +        component: kong
These are no longer needed, they are in the `bitnami-values.yaml`

2024-05-01 16:59 UTC, CollectiveUnicorn commented on packages/supabase/bitnami-values.yaml
Will look into doing this for the main bitnami-values file.

2024-05-01 18:23 UTC, CollectiveUnicorn commented on Makefile
> +	uds zarf package create packages/supabase -o packages/supabase --registry-override=ghcr.io=localhost:5000 --insecure --set IMAGE_VERSION=${LOCAL_VERSION} --confirm
Removed this script, opted to pull from remote for the build

2024-05-01 18:24 UTC, CollectiveUnicorn commented on packages/supabase/scripts/initial-push.sh
Deleted this script

2024-05-01 18:24 UTC, CollectiveUnicorn commented on Makefile
> +	uds zarf package create packages/supabase -o packages/supabase --registry-override=ghcr.io=localhost:5000 --insecure --set IMAGE_VERSION=${LOCAL_VERSION} --set TESTING=${TESTING:"false"} --confirm
I have removed this and the script

2024-05-01 18:25 UTC, CollectiveUnicorn commented on packages/supabase/scripts/initial-push.sh
> +docker pull supabase/studio:20230127-6bfd87b
With the local registry no longer being used, its just a dev script and I've removed it.

2024-05-01 18:25 UTC, CollectiveUnicorn commented on uds-bundles/dev/cpu/uds-config.yaml
> +        component: kong
These have been removed

2024-05-01 18:26 UTC, CollectiveUnicorn commented on packages/supabase/bitnami-values-basic.yaml
That worked, using this as an overlay

2024-05-01 19:20 UTC, CollectiveUnicorn commented on packages/supabase/chart/templates/supabase-dashboard-secret.yaml
> +{{- if .Values.leapfrogai.testing }}
Replace this with an env variable that is set before the test is run. The env variable contains the testing password by pulling it out of the cluster. The python test will then use that environment variable to do the health check.

2024-05-01 20:38 UTC, CollectiveUnicorn commented on packages/supabase/bitnami-values.yaml
I've slimmed this one down as well.

2024-05-01 22:04 UTC, YrrepNoj commented on .github/workflows/e2e.yaml
> +            DASHBOARD_PASSWORD=$(uds zarf tools kubectl get secret supabase-dashboard-secret -n leapfrogai -o jsonpath='{.data.password}' | base64 -d)
I think this is what you're trying to do?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable

2024-05-01 22:21 UTC, CollectiveUnicorn commented on .github/workflows/e2e.yaml
> +            DASHBOARD_PASSWORD=$(uds zarf tools kubectl get secret supabase-dashboard-secret -n leapfrogai -o jsonpath='{.data.password}' | base64 -d)
Ah yeah, I ended up doing it a little bit differently after realizing that what I had wasn't going to work in a single step.

2024-05-01 22:25 UTC, CollectiveUnicorn commented on .github/workflows/e2e.yaml
> +            DASHBOARD_PASSWORD=$(uds zarf tools kubectl get secret supabase-dashboard-secret -n leapfrogai -o jsonpath='{.data.password}' | base64 -d)
Updated it based on those docs.

2024-05-03 14:47 UTC, justinthelaw commented on packages/supabase/bitnami-values-bootstrap.yaml
> +postgresql:
How does this value relate to the one in the `bitnami-values.yaml`, `line 176`? Are these bootstrap values merged or overwritten by the other values during the helm deployment?

2024-05-03 14:53 UTC, justinthelaw commented on packages/supabase/bitnami-values-bootstrap.yaml
> +## @param global.imageRegistry Global Docker image registry
Recommend using Zarf air-gap patterns using `imagePullSecrets.name: private-registry`, and (optional) also specifying each `image`'s repository with the `###ZARF_REGISTRY###` prefix. Without the pull secret,, the container will fail to pull images in an air-gap even with the mutating hook.

2024-05-03 15:14 UTC, YrrepNoj requested changes

2024-05-03 15:14 UTC, YrrepNoj commented on packages/ui/chart/templates/ui/deployment.yaml
> +                  name: supabase-bootstrap-jwt
I don't understand, how does this prevent crashing in the UI? Where did the helm charts name get changed?

2024-05-03 15:14 UTC, YrrepNoj commented on packages/supabase/chart/templates/uds-package.yaml
> +spec:
We should be using the `sso` key for this CRD.

2024-05-03 15:14 UTC, YrrepNoj commented on packages/supabase/zarf.yaml
> +          - cmd: kubectl rollout restart deployment supabase-kong -n leapfrogai
Restarting a deployment right after it gets deployed feels like a code smell. Why do we need to restart this deployment? Could this be solved by reordering how we deploy things?

2024-05-03 15:21 UTC, YrrepNoj commented on packages/supabase/manifests/declarative-conf-configmap.yaml
> +      - name: realtime-v1
Our `packages/supabase/zarf.yaml` has a variable for `ENABLE_REALTIME`. It looks like this configmap is not templating itself depending on those variables.

Are there any potential issues we might run into if this configmap has this configuration for realtime when the person deploying sets `ENABLE_RELTIME` == false?

2024-05-03 16:00 UTC, YrrepNoj commented on packages/supabase/zarf.yaml
> +          - "bitnami-values.yaml"
This `bitnami-values.yaml` values file is being used by 3 different helm charts. This amount of overloading seems like it can get confusing and hard to maintain very quickly.

Can we please simplify this more?

2024-05-03 16:03 UTC, justinthelaw commented on packages/supabase/bitnami-values-bootstrap.yaml
> +## @param global.imageRegistry Global Docker image registry
NVM! Only needed pre-init!

2024-05-03 20:58 UTC, YrrepNoj commented on packages/supabase/chart/templates/uds-package.yaml
> +spec:
The Package CRD is [defined here](https://github.com/defenseunicorns/uds-core/blob/main/src/pepr/operator/crd/sources/package/v1alpha1.ts) and [here is an example of it being used](https://github.com/defenseunicorns/uds-core/blob/6e56b2afec8f54f8c0a4aa4b89fef1d1c754b627/src/grafana/chart/templates/uds-package.yaml#L7).

According to the documentation you have in the README of the PR and [this issue](https://github.com/defenseunicorns/leapfrogai/issues/448) I think the manifest should include something like this.

```yaml
spec:
  sso:
    - clientId: "supabase"
      name: "supabase"
      redirectUris:
        - "https://supabase-kong.uds.dev/auth/v1/callback"
        - "https://lfaiui.uds.dev/"
      webOrigins:
        - "https://supabase-kong.uds.dev"
        - "https://lfaiui.uds.dev"
```


NOTE: I followed the documentation in the issue you created but the `redirectUris` and `webOrigins` being the same lists feels a little wrong. Are we sure both of paths are needed in both those fields?

2024-05-06 16:14 UTC, CollectiveUnicorn commented on packages/supabase/README.md
> +```bash
There's a plan to automate this in https://github.com/defenseunicorns/leapfrogai/issues/448 I know the secret is named `supabase-keycloak-secret` but most of the automation is focused around keycloak itself. Then this will be a minor addition as a crd.

2024-05-06 16:25 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +          - cmd: kubectl rollout restart deployment supabase-kong -n leapfrogai
We restart it because kong starts before the new declarative config is applied, meaning that it has the wrong configuration when it first starts. When the new configuration is applied kong must be restarted so that it can pick up the new config and load it into the container.

2024-05-06 16:30 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +          - cmd: kubectl rollout restart deployment supabase-kong -n leapfrogai
Will add comments and todo for this.

2024-05-06 16:39 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +          - "bitnami-values.yaml"
There's a difference in how the chart deploys with helm vs Zarf/uds. Will create a ticket to investigate this further.

2024-05-06 16:49 UTC, CollectiveUnicorn commented
Will look into removing declarative config and requiring port forwarding to access the studio. Will need to update the test.

2024-05-06 17:44 UTC, CollectiveUnicorn commented on .github/workflows/e2e.yaml
> +            uds zarf package remove supabase -l=trace --confirm
Created an issue for this here: https://github.com/defenseunicorns/leapfrogai/issues/479

2024-05-06 17:45 UTC, CollectiveUnicorn commented on packages/supabase/README.md
> +```bash
This may be resolved even earlier by the UDS SSO configs that @YrrepNoj has suggested using

2024-05-06 17:50 UTC, CollectiveUnicorn commented on packages/supabase/bitnami-values-bootstrap.yaml
> +    enabled: false
This is just for the bootstrap of the jwt token, it creates a job, that job creates the secret and it ends so there's no need for persistence. The `bitnami-values.yaml` does have storage enabled and persistence by default. The default configs don't specify any storage-class in particular so it should be falling back to the default which is `local-path` I think atm. Here's the underlying values file just so you can see where this is happening: https://github.com/bitnami/charts/blob/8568db0ec0b217adb7ed53d615af3bfdb5de22f6/bitnami/supabase/values.yaml#L2458

2024-05-06 17:53 UTC, CollectiveUnicorn commented on packages/supabase/bitnami-values-bootstrap.yaml
> +postgresql:
The base values file [here](https://github.com/bitnami/charts/blob/8568db0ec0b217adb7ed53d615af3bfdb5de22f6/bitnami/supabase/values.yaml#L2458) from the chart are applied first, the our changes in bitnami-values.yaml just so we can get resource configs and any other little changes that may also affect the jwt token job, then the `bitnami-values-bootstrap.yaml` is applied on top of that. This values file disables everything but the jwt token job so that it can be bootstrapped. This has to occur due to lifecycle issues. Namely that the original helm chart relies the jwt token job running during/before other parts of Supabase and when we do a Zarf deploy it does not occur until after everything has successfully started up.

2024-05-06 17:56 UTC, CollectiveUnicorn commented on packages/supabase/chart/templates/supabase-keycloak-secret.yaml
Will do this and confirm that it works with everything else

2024-05-06 17:57 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +  - name: ENABLE_EXTERNAL_KEYCLOAK
The word `external` is not used consistently in the upstream helm chart. There's no internal keycloak provided AFAIK, but there is an internal Postgres option. Its dependent on what part of Supabase we're talking about how `external` is interpreted.

2024-05-06 18:00 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +  - name: ENABLE_EXTERNAL_KEYCLOAK
In this case it has more to do with gotrue then anything else. That's what kong is using under the covers I believe.

2024-05-06 18:00 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +  - name: ENABLE_EXTERNAL_KEYCLOAK
https://github.com/netlify/gotrue

2024-05-06 18:02 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +    description: 'Should the kong component be enabled'
I'll refine the descriptions

2024-05-06 18:24 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +          - cmd: kubectl delete cm supabase-kong-declarative-config -n leapfrogai
Its a lifecycle issue, if we make `supabase-studio` not accessible by any means other than through port-forwarding then this may not be necessary.

2024-05-06 18:40 UTC, CollectiveUnicorn commented on packages/supabase/manifests/declarative-conf-configmap.yaml
> +      - name: realtime-v1
If you try to hit `http://supabase-kong.uds.dev/realtime/v1/*` it'll just throw an error if its disabled.

2024-05-06 21:23 UTC, CollectiveUnicorn commented on packages/supabase/chart/templates/uds-package.yaml
> +spec:
Will validate the redirectUris and webOrigins are both needed once an initial working config is setup. If some of these are not necessary I'll strip them out.

2024-05-06 22:03 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +          - "bitnami-values.yaml"
Not sure if there's more that you'd potentially want with this. But the `bitnami-values.yaml` and `bitnami-values-bootstrap.yaml` files have been streamlined about as much as they can be. I could probably duplicate some things from bitnami-values to bitnami-values-bootstrap if we want to only have one values file but other then that its about as small as its going to get atm.

2024-05-06 23:09 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +    description: 'Should the kong component be enabled'
The descriptions should now better represent the individual pieces being enabled and disabled

2024-05-07 00:24 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +          - cmd: kubectl rollout restart deployment supabase-kong -n leapfrogai
Added comments, will look into removing if we can get the studio accessible through some other means

2024-05-07 16:26 UTC, CollectiveUnicorn commented on packages/ui/chart/templates/ui/deployment.yaml
> +                  name: supabase-bootstrap-jwt
The name of the token is autogenerated from the chart name. The chart is named `supabase-bootstrap` so the name no longer matches. If we leave it `supabase-jwt` it'll fail since the secret is no longer called that.

2024-05-07 18:36 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +          - cmd: kubectl rollout restart deployment supabase-kong -n leapfrogai
Removed all of this code in favor of port forwarding

2024-05-09 17:01 UTC, YrrepNoj commented on packages/ui/chart/templates/ui/deployment.yaml
> +                  name: supabase-bootstrap-jwt
If the secret name is autogenerated from the chart name, could we template this line here?

2024-05-09 17:05 UTC, YrrepNoj commented on tests/e2e/test_supabase.py
> +anon_api_key = os.environ["API_KEY"]
nit; could we leave a comment that explains what this key is (the anon-key for supabase?) so that people can read this file and know how to run the test locally?

People can figure this out if they read the `.github/workflows/e2e.yaml` so I will not block the merge on this comment so feel empowered to auto-resolve this comment if you don't think it's worth it.

2024-05-09 17:11 UTC, YrrepNoj commented on packages/supabase/chart/templates/uds-package.yaml
> +      clientId: uds-supabase
The `zarf.yaml` has a `###ZARF_CONST_ EXTERNAL_KEYCLOAK_CLIENT_ID###` constant. 

We should make sure that const has field for it set in the `bitnami-values.yaml` and then use that values template here.

2024-05-09 17:17 UTC, CollectiveUnicorn commented on tests/e2e/test_supabase.py
> +anon_api_key = os.environ["API_KEY"]
Will update this

2024-05-09 17:19 UTC, CollectiveUnicorn commented on packages/supabase/chart/templates/uds-package.yaml
> +      clientId: uds-supabase
I am confused as to what this means? Its used in the values file for `GOTRUE_EXTERNAL_KEYCLOAK_CLIENT_ID`.

2024-05-09 17:22 UTC, YrrepNoj commented on packages/supabase/chart/templates/uds-package.yaml
> +      clientId: uds-supabase
This file is hardcoding the clientId to uds-supabase. Someone can updating the `zarf.yaml.EXTERNAL_KEYCLOAK_CLIENT_ID` to be something different.

This would mean that the GOTRUE things that supabase directs to will be different than the client that Pepr created in Keycloak.

2024-05-09 17:31 UTC, justinthelaw approved these changes

2024-05-09 17:42 UTC, CollectiveUnicorn commented on packages/supabase/chart/templates/uds-package.yaml
> +      clientId: uds-supabase
Got it, will add it to values and use it in both places.

2024-05-09 18:07 UTC, CollectiveUnicorn commented on packages/supabase/zarf.yaml
> +          - cmd: kubectl rollout restart deployment supabase-kong -n leapfrogai
Added this back after our conversation

2024-05-09 21:17 UTC, YrrepNoj approved these changes
LGTM. This was a big effort so appreciate you working on this @CollectiveUnicorn!

2024-05-10 05:55 UTC, merged