Feat: sidenav redesign with import and export
defenseunicorns/leapfrogai pull request #398
Opened 2024-04-15 17:29 UTC by andrewrisse

closes #381 
closes #334 

Combining these two stories since they touch related code and merging them together while also trying to sign previous commits since we are now post ui-> monorepo was getting messy.

I can attempt to split them up if needed, but it will likely just cause more delays and complications getting future PRs approved.

This should reset the UI and make future PRs easy and normal.

2024-04-18 21:07 UTC, andrewrisse commented
[sidenav-demo.webm](https://github.com/defenseunicorns/leapfrogai/assets/52644157/a932d1d5-7a65-4342-85ac-1042c8aff928)

2024-04-19 00:38 UTC, YrrepNoj requested changes
A few misc change requests & questions.

2024-04-19 00:40 UTC, YrrepNoj commented on src/leapfrogai_ui/.env.example
>  # PUBLIC DYNAMIC
I think I learned this more as I went though the code changes. This seems to tie to the difference between importing from `$env/dynamic/private` and `$env/dynamic/public`. TIL!

2024-04-19 14:49 UTC, andrewrisse commented on uds-bundles/latest/gpu/uds-bundle.yaml
> +    ref: 0.1.8
I intended to push an image for 0.1.8 once this PR was accepted, but we can switch to old UI if that's the plan.

2024-04-19 14:52 UTC, andrewrisse commented on packages/ui/zarf-config.yaml
> +      image_version: 0.1.8
no, was building the image locally to test the PR out. Intent was to push out this image once PR was accepted, although I am not familiar with how we actually want to handle updating tags in PRs, so if you need me to set this to something else, totally fine.

2024-04-19 14:57 UTC, andrewrisse commented on packages/ui/zarf.yaml
> +    default: 'https://supabase.uds.dev'
@CollectiveUnicorn , I don't remember why we changed this? Can we leave it as http://supabase.leapfrogai.svc.cluster.local:8080?

We are overriding this in the uds-bundle config to use SAAS Supabase right now.

2024-04-19 14:59 UTC, andrewrisse commented on uds-bundles/dev/cpu/uds-config.yaml
> +    SUPABASE_URL: https://xemtkzebcveqpikvpyuz.supabase.co
Didn't realize this is an example config. Will remove these variables and update readme. I was using this file to deploy the PR into lf-04, will discuss new strategy offline.

2024-04-19 15:05 UTC, andrewrisse commented on uds-bundles/latest/gpu/uds-config.yaml
> -    domain: https://ai.uds.dev
added vars back in and standardized accross all configs

2024-04-19 15:06 UTC, andrewrisse commented on uds-bundles/latest/cpu/uds-config.yaml
> -    domain: https://ai.uds.dev
added back in and standardized

2024-04-19 15:06 UTC, andrewrisse commented on src/leapfrogai_ui/src/lib/helpers/dates.test.ts
> +			const currentDate = new Date(today.getFullYear(), today.getMonth(), 10);
removed

2024-04-19 16:39 UTC, andrewrisse commented on uds-bundles/latest/gpu/uds-bundle.yaml
> +    ref: 0.1.8
switched to old ui and added back in old variables (only for latest folder, dev remains setup for new ui)

2024-04-19 16:40 UTC, andrewrisse commented on packages/ui/zarf-config.yaml
> +      image_version: 0.1.8
set to 'dev', will need to remember to use ```--registry-override``` flag until we have workflow that pushes new dev tag. Not going to delete existing dev tag on ghcr right now.

2024-04-19 16:41 UTC, andrewrisse commented on uds-bundles/dev/cpu/uds-config.yaml
> +    SUPABASE_URL: https://xemtkzebcveqpikvpyuz.supabase.co
changed to example values

2024-04-19 20:28 UTC, andrewrisse commented on packages/ui/zarf.yaml
> +    default: 'https://supabase.uds.dev'
update: re-updated to use the dns address because the request to login to supabase will come from the user's browser, not from within the cluster. We also adjusted the anon key to pull from the supabase secret (supabase is now working in lf-04) by default, while still allowing an override with the UDS bundle config.

2024-04-22 15:30 UTC, merged