feat(api): assistants endpoints
defenseunicorns/leapfrogai pull request #424
Opened 2024-04-19 21:31 UTC by gphorvath

2024-05-03 16:44 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/assistants.py
> +        raise HTTPException(
return exception vs raise exception

2024-05-03 16:53 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/assistants.py
> +            tool_resources=ToolResources.model_validate(request.tool_resources),
Might not need to double validate

2024-05-03 16:53 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/assistants.py
> +        raise HTTPException(status_code=404, detail="No assistants found") from exc
Error would be something other than "no assistants found"

2024-05-03 16:56 UTC, gphorvath commented on src/leapfrogai_api/data/crud_assistant_object.py
> +    async def delete(self, client: AsyncClient, assistant_id: str) -> AssistantDeleted:
add check that this can't overwrite ID

2024-05-03 17:13 UTC, gphorvath commented on tests/integration/api/test_assistants.py
> +    assert get_modified_response.status_code == 200
use status code object type

2024-05-03 17:13 UTC, gphorvath commented on tests/integration/api/test_assistants.py
> +    assert modify_response.json()["model"] == "test1", "Should be modified."
convert to variable

2024-05-09 06:28 UTC, YrrepNoj reviewed
PR is looking like it's going in the right direction. Left a few comments on some thoughts/questions I had.

2024-05-09 06:28 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/files.py
> +async def list_files(session: Session) -> ListFilesResponse | None:
Learning question; 

The `ListFilesResponse` class seems pretty bare only really only holds a `data` member that is typed to be a `list[FileObject]`. What benefit do we gain from using that Class instead of just returning a `list[FileObject]`?

2024-05-09 06:28 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/files.py
> +    return {
If we are going to declare that this function returns a `ListFilesResponse` can we return an actual instance of the `ListFilesResponse` Class instead of returning a dict that matches its current fields?

2024-05-09 06:28 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/files.py
> +        return None
What are your thoughts on returning a `ListFilesResponse` where it's data member is set to None instead of returning None itself?

2024-05-09 13:29 UTC, gphorvath commented on src/leapfrogai_api/Makefile
> +	cd ../../ && python -m pytest tests/integration/api
I do think that would make sense

2024-05-09 13:38 UTC, gphorvath commented on src/leapfrogai_api/utils/openai_util.py
> +    if len(data) > 128:
This just follow the arbitrary limit OpenAI set: https://platform.openai.com/docs/api-reference/assistants/createAssistant#assistants-createassistant-tools

I wasn't sure where to set our limit so I stuck to OpenAI's - although I'm sure theirs accounts for the other possible tool types.

2024-05-09 13:48 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/files.py
> +async def list_files(session: Session) -> ListFilesResponse | None:
OpenAI returns a typed dict in the form:

``` python
{
    object: str
    data: list[FileObject]
}
```

I originally tried just returning `list[FileObject]`, but the OpenAI client library throws errors on that.

2024-05-09 15:50 UTC, gphorvath commented on src/leapfrogai_api/utils/openai_util.py
> +    if len(data) > 128:
It is now a named variable

2024-05-09 15:51 UTC, gphorvath commented on src/leapfrogai_api/utils/openai_util.py
> +    for tool_data in data:
Nope, good catch!

2024-05-09 15:56 UTC, gphorvath commented on src/leapfrogai_api/utils/openai_util.py
> +    "function_tool": FunctionTool,
I kept it intentionally inline with the OpenAI spec here and tried to catch it in the response: https://github.com/defenseunicorns/leapfrogai/blob/9c4d013fb8e4917d9131a910ac764f80749627f9/src/leapfrogai_api/backend/types.py#L253

2024-05-09 15:56 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/files.py
> +    return {
Yes

2024-05-09 15:57 UTC, gphorvath commented on src/leapfrogai_api/utils/openai_util.py
> +    if tool_instance is None:
Fixed via other comments

2024-05-15 16:22 UTC, CollectiveUnicorn commented on src/leapfrogai_api/Makefile
> +	cd ../../ && python -m pytest tests/integration/api
That's the way I've seen it in the past, have test folders that are co-located with the tested code

2024-05-15 16:27 UTC, gphorvath commented on src/leapfrogai_api/Makefile
> +	cd ../../ && python -m pytest tests/integration/api
moving this into an issue so it can be a standalone PR

https://github.com/defenseunicorns/leapfrogai/issues/514

2024-05-15 16:32 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/files.py
> +        return None
Good idea, made the change.

2024-05-15 16:38 UTC, gphorvath commented on src/leapfrogai_api/README.md
> +Integration tests require a Supbase instance and environment variables configured.
I made a reference to the Local Development section since that is how I'm doing it for now.

2024-05-15 17:17 UTC, CollectiveUnicorn requested changes

2024-05-15 17:49 UTC, gphorvath commented on tests/pytest/leapfrogai_api/test_api.py
> +        "/openai/v1/assistants": ["POST"],
The problem is it doesn't test "all" because of the need for unique keys in the dictionary. So it isn't actually giving us that certainty.

2024-05-15 17:50 UTC, gphorvath commented on .gitignore
> +src/leapfrogai_api/config.yaml
I'm happy to ignore them all, but I only knew with certainty that I wanted to ignore this one.

2024-05-15 17:53 UTC, gphorvath commented on src/leapfrogai_api/data/crud_assistant_object.py
> +        if assistant_object_dict.get("id") == "":
Done

2024-05-15 17:56 UTC, gphorvath commented on .gitignore
> +src/leapfrogai_api/config.yaml
Done

2024-05-15 17:57 UTC, alekst23 commented on src/leapfrogai_api/Makefile
> +	cd ../../ && python -m pytest tests/integration/api
I am not sure if it's a good idea to mix the two. Normally you would have a `tests` directory at root level, and organize all testing there, something like this:
```
├── src/
├── tests/
│   ├── unit/
│   │   ├── ui/
│   │   ├── api/
│   │   ├── ...
│   ├── integration/
│   │   ├── ui/
│   │   ├── api/
│   │   ├── ...
│   ├── functional/
```

2024-05-15 18:40 UTC, CollectiveUnicorn commented on tests/pytest/leapfrogai_api/test_api.py
> +        "/openai/v1/assistants": ["POST"],
Which endpoints are you referring to? For the assistants endpoint can't we add something like this?
- "/openai/v1/assistants": ["GET", "POST"]
- "/openai/v1/assistants/": ["GET", "POST", "DELETE"]

2024-05-15 18:43 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/assistants.py
> +            tool_resources=ToolResources.model_validate(request.tool_resources)
You're right, I missed that

2024-05-15 19:10 UTC, gphorvath commented on tests/pytest/leapfrogai_api/test_api.py
> +        "/openai/v1/assistants": ["POST"],
I could rewrite the test a bit to support that, but it doesn't right now. Also it still wouldn't necessarily support something in the form `POST vector_stores/{vector_store_id}/files` (https://platform.openai.com/docs/api-reference/vector-stores-files/createFile)

2024-05-15 21:57 UTC, gphorvath commented on tests/pytest/leapfrogai_api/test_api.py
> +        "/openai/v1/assistants": ["POST"],
We found a way

2024-05-15 21:57 UTC, andrewrisse commented on src/leapfrogai_api/data/crud_assistant_object.py
> +    async def list(self, client: AsyncClient) -> list[Assistant] | None:
Should this only list assistants that belong to the user?
I think this might break once we add authentication unless our assistants table has "allow all" read permissions on it.
If we do only return a user's specific assistants, would this be a deviation from OpenAI? 

Maybe we should have our own endpoint that gets assistants by user. That's what the frontend currently does, I'm worried about performance issues if I have to pull all assistants in from the database, then filter to only that user's assistants

2024-05-15 22:17 UTC, andrewrisse reviewed
Final comment is just for error handling. Can we log out the errors so we can see them in the pods? I like modifying error responses returned to the caller for security reasons, but it's nice to see the actual error response in the logs where it's safe (ex. exactly what the supabase error was, not just 500 "Internal Error" or something.)

2024-05-15 22:17 UTC, andrewrisse commented on src/leapfrogai_api/routers/openai/assistants.py
> +            created_at=int(time.time()),
does supabase add the created_at field for us?

2024-05-15 22:17 UTC, andrewrisse commented on src/leapfrogai_api/routers/openai/assistants.py
> +            status_code=405, detail="Unable to parse assistant request"
405 is method not allowed (ex. GET vs POST), should this be a 400 maybe?

2024-05-15 22:17 UTC, andrewrisse commented on src/leapfrogai_api/routers/openai/assistants.py
> +            status_code=405, detail="Unable to create assistant"
return a 500 instead of 405?

2024-05-15 22:17 UTC, andrewrisse commented on src/leapfrogai_api/routers/openai/assistants.py
> +        raise HTTPException(status_code=404, detail="Assistant not found") from exc
Up for debate, but should we return a 200 or 204 with empty data when it's not found? 404 implies several possible conditions (ex. website down, proxy issues, etc). The request was successful but there was no data so 200 is what I've seen several backends do.

2024-05-15 22:17 UTC, andrewrisse commented on src/leapfrogai_api/routers/openai/assistants.py
> +        raise HTTPException(status_code=404, detail="Assistant not found")
same 404 comment as above, assumed for the rest of the 404s too

2024-05-15 22:17 UTC, andrewrisse commented on supabase/migrations/20240419164109_init-assistant.sql
> +  );
Adding in my version of this for the frontend migrations for reference. Big differences are:
1. limiting the name, description, and model text lengths with VARCHAR to what openai limits them too
2. typed the created_at field differently
3.  "object" is type checked to be "assistant".
4. response_object can be a string or json. 
5. Specified not null fields.
```
create table assistants (
    id uuid primary key DEFAULT uuid_generate_v4(),
    object text check (object in ('assistant')),
    name varchar(255),
    description varchar(512),
    model varchar(255) not null,
    instructions TEXT,
    tools jsonb,
    tool_resources jsonb,
    metadata jsonb,
    temperature float,
    top_p float,
    response_format jsonb,
created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
```

2024-05-15 22:17 UTC, andrewrisse commented on tests/integration/api/test_assistants.py
> +    assert create_response.status_code is status.HTTP_200_OK
can we also use these status code constants in the main code (not just tests)?
status.HTTP_200_OK

2024-05-15 22:41 UTC, gphorvath commented on tests/integration/api/test_assistants.py
> +    """Test creating an assistant. Requires a running Supabase instance."""
Broken up!

2024-05-15 22:47 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/assistants.py
> +            created_at=int(time.time()),
Good point, I bet I could set a default via the schema, I'll have to check in the AM

2024-05-16 03:34 UTC, gphorvath commented on tests/integration/api/test_files.py
> +    """Test creating a file. Requires a running Supabase instance."""
I modified this to be broken up similarly to the assistants tests.

2024-05-16 16:59 UTC, gphorvath commented on src/leapfrogai_api/data/crud_assistant_object.py
> +    async def list(self, client: AsyncClient) -> list[Assistant] | None:
@andrewrisse I added two tickets to cover this:

Authenticating user and returning relevant data: https://github.com/defenseunicorns/leapfrogai/issues/483

Pagination of OpenAI endpoints: https://github.com/defenseunicorns/leapfrogai/issues/530

Let's discuss more at Backlog grooming, but think maybe this is a 0.8.0 requirement, not necessarily a blocker for this PR.

2024-05-16 17:17 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/files.py
>      return file_object
yes

2024-05-16 17:24 UTC, gphorvath commented on src/leapfrogai_api/data/crud_assistant_object.py
> +        data, _count = (
This is handled by the Modify Assistant route. I added some detail there to specify what can be updated.

2024-05-16 17:44 UTC, CollectiveUnicorn submitted a review, later dismissed

2024-05-16 17:56 UTC, CollectiveUnicorn approved these changes

2024-05-16 23:09 UTC, CollectiveUnicorn submitted a review, later dismissed

2024-05-17 16:56 UTC, alekst23 commented on src/leapfrogai_api/utils/openai_util.py
> +    "function_tool": FunctionTool,
We should add a unit test to make sure this value is validated

2024-05-17 17:05 UTC, justinthelaw commented on src/leapfrogai_api/routers/openai/assistants.py
> +            tools=validate_tools_typed_dict(request.tools),
It seems like the OpenAI Python library does have a set of Pydantic classes built-in as sub-fields for the Assistant Pydantic model. If you use the Assistant pydantic model from the 1.21.1 OpenAI Python lib, you don't need to build a custom validator.

Assistant model: https://github.com/openai/openai-python/blob/bb95fe35ad4b480ebce57aa5b48df620df8d761b/src/openai/types/beta/assistant.py#L78

AssistantTool model: https://github.com/openai/openai-python/blob/v1.21.1/src/openai/types/beta/assistant_tool.py

and

Example tool's model: https://github.com/openai/openai-python/blob/v1.21.1/src/openai/types/beta/code_interpreter_tool.py

2024-05-17 17:10 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/assistants.py
> +            temperature=request.temperature or old_assistant.temperature,
Edge case: If temperature = 0, it might inadvertently default to old_assistant.temperature

`request.get("temperature", old_assistant.temperature)`

2024-05-17 17:11 UTC, justinthelaw commented on src/leapfrogai_api/routers/openai/assistants.py
> +            tools=validate_tools_typed_dict(request.tools),
An exmaple of when you may want to build your own Pydantic class (model) and want to build a validator for a particular field:

```python
class Input(BaseModel):
    input: str

    @validator("input")
    def max_token_length(cls, v):
        """
        The `max_token_length` function is a validator in Python that checks if the tokenized length of the
        input exceeds a maximum length and raises a `ValueError` if it does.

        :param cls: The `cls` parameter refers to the class that the `max_token_length` method is defined
        in. In this case, it is a class that contains the `max_token_length` method
        :param v: The parameter `v` represents the input value that is being validated. In this case, it is
        the `input` value that is being passed to the `max_token_length` function
        :return: The variable `v` is being returned.
        """
        tokenizer = T5Tokenizer.from_pretrained(
            TOKENIZER,
            legacy=False,
        )
        tokenized_length = len(tokenizer.tokenize(v))

        if tokenized_length > MAX_INPUT_TOKEN_LENGTH:
            max_length_error = f"The maximum token length is {MAX_INPUT_TOKEN_LENGTH}"
            raise ValueError(max_length_error)

        if tokenized_length < MIN_INPUT_TOKEN_LENGTH:
            min_length_error = f"The minimum token length is {MIN_INPUT_TOKEN_LENGTH}"
            raise ValueError(min_length_error)

        return v
```

2024-05-17 17:11 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/assistants.py
> +            status_code=status.HTTP_400_BAD_REQUEST, detail="Assistant not found"
Internal server error

2024-05-17 17:12 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/files.py
> +            created_at=123,  # This is set by the database to prevent conflicts
0

2024-05-17 20:20 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/assistants.py
> +            temperature=request.temperature or old_assistant.temperature,
found a way to do this!

2024-05-17 20:20 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/assistants.py
> +            status_code=status.HTTP_400_BAD_REQUEST, detail="Assistant not found"
Fixed

2024-05-17 20:21 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/assistants.py
> +            tools=validate_tools_typed_dict(request.tools),
We worked together to kill this code and do it better

2024-05-17 20:36 UTC, CollectiveUnicorn approved these changes

2024-05-17 20:47 UTC, justinthelaw submitted a review, later dismissed
Was IRL witness, can confirm new tests/types work haha

2024-05-17 21:29 UTC, andrewrisse approved these changes

2024-05-20 17:07 UTC, alekst23 commented on src/leapfrogai_api/routers/openai/files.py
> +async def list_files(session: Session) -> ListFilesResponse:
@gphorvath Why do we need to return an object here instead of a list? It seems to have one other member besides the `data` list, which is `object` . Are we envisioning something processing this list differently based on the `object` value that is returned? Seems like it's defaulting to `list`. How are we planning to use that value?

2024-05-20 17:10 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/files.py
> +async def list_files(session: Session) -> ListFilesResponse:
This is directly inherited from the OpenAI spec.

2024-05-20 17:19 UTC, YrrepNoj approved these changes

2024-05-20 17:27 UTC, alekst23 commented on .gitignore
> +config.yaml
Are we trying to omit all `config.yaml` files in the project? We have some files like `src/leapfrogai_sdk/config.py`, `src/leapfrogai_api/utils/config.py`, and others which would be affected and no longer be tracked for changes. Are these local dev configs?

2024-05-20 17:44 UTC, gphorvath commented on .gitignore
> +config.yaml
config.py should be fine, but I double checked and there are config.yaml's in some of packages, so I should probably specify just the API. I think I had it that way initially actually, then changed it.

2024-05-20 17:49 UTC, gphorvath commented on .gitignore
> +config.yaml
I changed it back!

2024-05-20 18:17 UTC, CollectiveUnicorn submitted a review, later dismissed

2024-05-20 20:42 UTC, alekst23 commented on src/leapfrogai_api/routers/openai/assistants.py
> +                    )
There are a few issues in this block. One is the use of `is` keyword, which is generally used for checking object instances, not for type checking. The other is `is not None`, which will fail for empty lists ([] != None)

We should use a pattern similar to this:
```python
    if request.tool_resources:
        if list(filter(lambda resource: isinstance(resource, ToolResourcesCodeInterpreter) and resource.get("file_ids"), request.tool_resources)):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Code interpreter tool is not supported",
            )
```

This will properly handle type checking and truthiness validation for properties.

2024-05-20 21:01 UTC, alekst23 commented on src/leapfrogai_api/routers/openai/assistants.py
> +                )
Similar comment to the one below (going bottom up because why not)
```python
    SUPPORTED_TOOLS = ["file_search"]
    if request.tools and (unsupported_tool := next((tool for tool in request.tools if tool.type not in SUPPORTED_TOOLS), None)):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unsupported tool type: {unsupported_tool.type}",
        )
```

This will properly check empty values

2024-05-20 21:15 UTC, alekst23 commented on src/leapfrogai_api/routers/openai/assistants.py
> +                if tool_resource["file_ids"] is not None:
Same comment as above here. We should use `isinstance` and `get` functions

2024-05-20 21:17 UTC, alekst23 commented on src/leapfrogai_api/routers/openai/assistants.py
> +    if old_assistant is None:
Might be safer to avoid `is None` like this:
```python
    if old_assistant := await crud_assistant.get(db=session, id_=assistant_id):
```

2024-05-20 21:59 UTC, alekst23 commented on src/leapfrogai_api/routers/openai/assistants.py
> +        )
We will have issues with this code in the following instances:
1. Empty property values in `request` will be ignored. So you will not be able to clear any existing values.
2. If the property is missing from the object, it will thrown an error

We should use the following pattern:
```python
new_assistant = Assistant(
    id=assistant_id,
    created_at=old_assistant.created_at,
    name=getattr(request, 'name', old_assistant.name),
    description=getattr(request, 'description', old_assistant.description),
    instructions=getattr(request, 'instructions', old_assistant.instructions),
    model=getattr(request, 'model', old_assistant.model),
    object="assistant",
    tools=getattr(request, 'tools', old_assistant.tools),
    tool_resources=ToolResources.model_validate(getattr(request, 'tool_resources', None)) or old_assistant.tool_resources,
    temperature=float(getattr(request, 'temperature', old_assistant.temperature)),
    top_p=getattr(request, 'top_p', old_assistant.top_p),
    metadata=getattr(request, 'metadata', old_assistant.metadata),
    response_format=getattr(request, 'response_format', old_assistant.response_format),
)

```

2024-05-20 22:17 UTC, alekst23 approved these changes
👍

2024-05-20 22:38 UTC, CollectiveUnicorn approved these changes

2024-05-21 16:19 UTC, YrrepNoj approved these changes

2024-05-21 16:27 UTC, merged