407 Add test workflow for leapfrogai_ui
defenseunicorns/leapfrogai pull request #439
Opened 2024-04-24 20:24 UTC by jalling97

- Adds a workflow for running the existing unit tests within the new UI.
- Adds a workflow to scan for active secrets using trufflehog
- Adds UI-focused linting checks to the existing lint workflow
- Adds eslint and prettier to pre-commit checks

After the workflows were added, linting changes were applied to this PR to get the UI compliant with the linter/formatter

2024-04-25 20:09 UTC, jalling97 commented on .github/workflows/secret-scan.yaml
> +      - "**"
Is there anytime we don't want to run this workflow? At the moment it runs on all PRs always.

2024-04-25 21:58 UTC, andrewrisse commented
I disabled the 'no-unde' rule for eslint because Typescript is already checking for this and gives no errors. 
Docs Reference: https://typescript-eslint.io/troubleshooting/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors

2024-04-26 13:27 UTC, justinthelaw reviewed
Just a question and some minor things!

2024-04-26 13:27 UTC, justinthelaw commented on .github/workflows/lint.yaml
> +      - uses: actions/setup-node@v4
Need hash pinning instead

2024-04-26 13:27 UTC, justinthelaw commented on .github/workflows/lint.yaml
> +          node-version: 18
Recommend pinning using ASoT, e.g., `package.json` or other similar method.

2024-04-26 13:27 UTC, justinthelaw commented on .github/workflows/secret-scan.yaml
> +      - "**"
I think it's good to always run this, because anything could be accidentally pasted or added.

2024-04-26 13:27 UTC, justinthelaw commented on .github/workflows/secret-scan.yaml
> +      uses: trufflesecurity/trufflehog@main
Recommend pinning via hash.

2024-04-26 13:27 UTC, justinthelaw commented on .github/workflows/ui-test.yaml
> +      - uses: actions/setup-node@v4
Need hash pinning instead

2024-04-26 13:27 UTC, justinthelaw commented on .github/workflows/ui-test.yaml
> +          node-version: 18
Same comment as before about node version pinning

2024-04-26 13:27 UTC, justinthelaw commented on .pre-commit-config.yaml
> +  - repo: https://github.com/pre-commit/mirrors-eslint
Recommend added deps, not sure if ESLint pre-commit actually uses the local config...

```yaml
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.56.0
      hooks:
          - id: eslint
            name: ESLint and Prettier
            files: \.([jt]sx?|svelte)$ # *.js, *.jsx, *.ts, *.tsx and *.svelte
            types: [file]
            additional_dependencies:
                - eslint@8.44.0
                - eslint-plugin-prettier@5.0.0
                - eslint-plugin-svelte@2.35.1
            args: [--fix]
```

2024-04-26 14:17 UTC, gerred approved these changes

2024-04-26 14:17 UTC, andrewrisse commented on .github/workflows/lint.yaml
> +        run: npm --prefix src/leapfrogai_ui install
I think we should be using ```npm ci``` instead of ```npm install``` for a workflow.
https://stackoverflow.com/a/53325242/11761227

2024-04-26 14:17 UTC, gerred commented on .pre-commit-config.yaml
> +  - repo: https://github.com/pre-commit/mirrors-eslint
lgtm pending checking this

2024-04-26 14:18 UTC, gerred commented
all lgtm pending @justinthelaw's feedback being resolved.

2024-04-26 14:19 UTC, andrewrisse commented on .github/workflows/ui-test.yaml
> +        run: npm --prefix src/leapfrogai_ui install
same comment as above about npm install vs npm ci

2024-04-26 14:21 UTC, jalling97 commented on .github/workflows/lint.yaml
> +      - uses: actions/setup-node@v4
Why hash pinning? Does it have to do with pointing us directly to a specific commit instead of a release tag that could be overridden?

2024-04-26 14:24 UTC, andrewrisse commented on .pre-commit-config.yaml
> +  - repo: https://github.com/pre-commit/mirrors-eslint
there's also a prettierrc file we would want it to use. Can we confirm it does pull those?

2024-04-26 14:43 UTC, jalling97 commented on .github/workflows/secret-scan.yaml
> +      uses: trufflesecurity/trufflehog@main
Why for trufflehog? Wouldn't we want to always keep these kinds of scans as current as possible?

2024-04-26 14:50 UTC, justinthelaw commented on .github/workflows/lint.yaml
> +      - uses: actions/setup-node@v4
Oh, I'm talking about the node setup action, not trufflehog

2024-04-26 14:52 UTC, andrewrisse commented on .github/workflows/lint.yaml
> +        run: npm --prefix src/leapfrogai_ui install
ya and it uses the package-lock.json to do a "clean install", it's what I've always seen used in pipelines. If there issues with the dependencies (missing or mismatched) it will error out instead of installing. It will just result in a consistent build process, no surprises from cache issues

2024-04-26 14:56 UTC, gerred commented on .github/workflows/secret-scan.yaml
> +      uses: trufflesecurity/trufflehog@main
Is trufflehog's scanning self contained into the container or is it calling out to an external service for secret scanning?

2024-04-26 14:58 UTC, jalling97 commented on .github/workflows/lint.yaml
> +      - uses: actions/setup-node@v4
I see the reason for pinning the `setup-node` version, I think my trufflehog question was in another comment thread

2024-04-26 14:59 UTC, gerred commented on .github/workflows/secret-scan.yaml
> +      uses: trufflesecurity/trufflehog@main
disregard, my GH isn't updating new comments.

2024-04-26 16:16 UTC, gerred commented on .pre-commit-config.yaml
> +        files: \.(js|jsx|ts|tsx|svelte)$ # apply prettier to the provided filetypes
do we need .cjs and .mjs here?

2024-04-26 19:35 UTC, andrewrisse commented on .pre-commit-config.yaml
> +  - repo: https://github.com/pre-commit/mirrors-eslint
replacing prettier with eslint-plugin-prettier resolves this conversation

2024-04-26 19:39 UTC, jalling97 commented on .pre-commit-config.yaml
> +  - repo: https://github.com/pre-commit/mirrors-eslint
I also confirmed that the ESlint precommit hook does use our local `eslint` and `prettierrc` configs.

2024-04-29 17:46 UTC, jalling97 commented on .pre-commit-config.yaml
> +        files: \.(js|jsx|ts|tsx|svelte)$ # apply prettier to the provided filetypes
Added :+1:

2024-04-29 17:48 UTC, jalling97 commented on .github/workflows/lint.yaml
> +          node-version: 18
Pinned the node version in `package.json` and changed the checks to reference that version :+1:

2024-04-29 18:03 UTC, justinthelaw commented on .github/workflows/secret-scan.yaml
> +      uses: trufflesecurity/trufflehog@main
@jalling97 I think I mistakenly added this comment to this job. I am good here! Seems like @gerred still has a question though.

2024-04-29 19:08 UTC, jalling97 commented on .github/workflows/secret-scan.yaml
> +      uses: trufflesecurity/trufflehog@main
Unless I missed something obvious, I couldn't really find anything concrete as to whether or not the scanning reaches out to an external service, but I did test the scans without being connected to the internet and they still worked so maybe?

2024-04-29 23:27 UTC, gerred commented
fix conflicts then lgtm

2024-04-29 23:27 UTC, gerred approved these changes

2024-04-30 16:13 UTC, gerred submitted a review, later dismissed

2024-04-30 16:22 UTC, YrrepNoj requested changes
Two small change requests.

2024-04-30 16:22 UTC, YrrepNoj commented on .github/workflows/secret-scan.yaml
> +      - "**"
This doesn't hurt to keep, but it is a little confusing because it's overriding the default behavior with a catchall that does the same thing. 

Let's just remove this if we aren't going to actually be restricting on specific paths.

2024-04-30 16:22 UTC, YrrepNoj commented on .github/workflows/ui-test.yaml
> +    paths:
I would like to make this test be a blocker for PRs, if we have the `paths` we will need a 'shim' workflow.

2024-04-30 16:29 UTC, jalling97 commented on .github/workflows/secret-scan.yaml
> +      - "**"
I thought about taking it out for that reason, but part of me thought this was actually more clear about when and where the secret-scanner gets ran. Happy to remove it if that doesn't make sense/isn't worth it though.

2024-04-30 16:31 UTC, jalling97 commented on .github/workflows/ui-test.yaml
> +    paths:
Good point. I can add a `ui-test-shim.yaml` workflow

2024-04-30 17:44 UTC, jalling97 commented on .github/workflows/secret-scan.yaml
> +      - "**"
Ended up removing it.

2024-04-30 18:34 UTC, YrrepNoj approved these changes
LGTM.

2024-04-30 18:45 UTC, merged