408 ci update publish workflow w leapfrogai UI artifacts
defenseunicorns/leapfrogai pull request #464
Opened 2024-04-30 19:33 UTC by jalling97

- Adds the UI zarf build process to the release workflow
- Updates the Makefile with new ui target
- Updates UI zarf package yamls

2024-05-02 22:41 UTC, YrrepNoj requested changes
Thanks for the PR. Just one single change request!

2024-05-02 22:41 UTC, YrrepNoj commented on Makefile
> +build-ui: ## Build the leapfrogai_ui container and Zarf package
With this new make target, I tthink  it make sense to remove the Makefile at `src/leapfrogai_ui/Makefile`.

2024-05-03 13:49 UTC, jalling97 commented on Makefile
> +build-ui: ## Build the leapfrogai_ui container and Zarf package
Good catch. I'll remove the old one and update any documentation referencing it

2024-05-03 14:09 UTC, jalling97 commented on Makefile
> +build-ui: ## Build the leapfrogai_ui container and Zarf package
Removed :+1:

2024-05-03 14:41 UTC, YrrepNoj approved these changes

2024-05-06 14:25 UTC, merged