feat(api): vector store endpoints
defenseunicorns/leapfrogai pull request #468
Opened 2024-05-02 20:35 UTC by gphorvath

closes #421

2024-05-03 18:25 UTC, gphorvath commented on supabase/migrations/20240502193159_init-vector-store.sql
> +  query_embedding vector (768), -- Instructor-XL produces 4096-dimensional embeddings
768 length

2024-05-08 22:14 UTC, gphorvath commented
Starting to work on storing and querying across vectors. Noticed that vecs and Langchain's Supabase client don't support async calls. Might need to use something like psycopg.

2024-05-15 16:53 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/files.py
>  async def upload_file(
Do we want file size limits on upload?

2024-05-15 16:56 UTC, gphorvath commented on src/leapfrogai_api/backend/rag/document_loader.py
> +from langchain_text_splitters import RecursiveCharacterTextSplitter
Follow-on work would be to use semantic splitting with our LLM backend.

2024-05-21 15:33 UTC, alekst23 commented on src/leapfrogai_api/README.md
> +- Libreoffice ([Unstructured dependency via LangChain](https://python.langchain.com/docs/integrations/providers/unstructured/) for docx parsing)
Do we actually implement this somewhere, or is it just a dependency library?

2024-05-21 15:37 UTC, alekst23 commented on src/leapfrogai_api/backend/leapfrogai_embeddings.py
> +            raise ValueError("Embeddings model not found.")
```suggestion
        if not model := get_model_config().get_model_backend(model=model_name)
            raise ValueError("Embeddings model not found.")
```

2024-05-21 19:51 UTC, gphorvath commented on src/leapfrogai_api/README.md
> +- Libreoffice ([Unstructured dependency via LangChain](https://python.langchain.com/docs/integrations/providers/unstructured/) for docx parsing)
This is a dependency of Unstructured a library included in Langchain for parsing various types to document.

2024-05-22 21:34 UTC, alekst23 requested changes

2024-05-22 21:34 UTC, alekst23 commented on src/leapfrogai_api/data/crud_base.py
> +        if dict_["id"] == "":  # for some endpoints an id may be provided
If this property is not always present, and we want to remove it regardless of it's value, we should use this pattern:
```python
if "id" in dict_:
    del dict_["id"]
```

2024-05-23 16:16 UTC, alekst23 commented on supabase/migrations/20240502193159_init-vector-stores.sql
> +    1 - (vector_store.embedding <=> query_embedding) as similarity
Depending on how the query management is handled for the `<=>` operator, it is quite possible that this SQL will perform the cosine similarity search twice, once for the column data, and once for the order by operation. 

There's a couple ways we can solve this. One is rewriting the query with a common table expression. The other is making sure that the query is index and only runs once per call. I think we may need to create a new index for this operator regardless, actually. Still doing some research into this now. 

Given that a lot of example have this type of syntax without CTE, I imagine the indexing step resolves this issue.

2024-05-23 19:37 UTC, alekst23 commented on supabase/migrations/20240502193159_init-vector-stores.sql
> +    1 - (vector_store.embedding <=> query_embedding) as similarity
I am 80% sure that postgres will optimize this query. However, I want to follow up with some testing later.

2024-05-23 19:56 UTC, gphorvath commented on src/leapfrogai_api/backend/rag/document_loader.py
> +        raise ValueError("Embeddings model not found.")
fixed.

2024-05-23 19:57 UTC, gphorvath commented on src/leapfrogai_api/data/crud_base.py
> +        if dict_["id"] == "":  # for some endpoints an id may be provided
I think that makes sense. In the case of vector_store_file I discovered the need to provide the ID, so I changed this.

2024-05-28 18:17 UTC, CollectiveUnicorn commented on src/leapfrogai_api/data/supabase_vector_store.py
> +        query_name: str = "match_vectors",
I've hardcoded these, so they should be good now

2024-05-28 23:42 UTC, alekst23 commented on src/leapfrogai_api/backend/rag/leapfrogai_embeddings.py
> +    async def aembed_query(self, text: str) -> list[float]:
We should try to avoid duplicate code like in functions `aembed_query` and `aembed_document`, which perform similar functionality. Maybe `aembed_documents` should call `aembed_query` iteratively?

2024-05-31 17:01 UTC, CollectiveUnicorn commented
Set to debug log level by default

2024-05-31 17:06 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/rag/document_loader.py
> +async def supported_mime_type(mime_type: str) -> bool:
Make not async

2024-05-31 17:28 UTC, CollectiveUnicorn requested changes
Set to debug log-level by default wherever uvicorn is used

2024-06-03 20:09 UTC, YrrepNoj requested changes

2024-06-03 20:09 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +        data=crud_response or [],
Does your IDE give warnings on the type hinting here for you?

The `ListVectorStoresResponse.data` object is defined as `list[VectorStore]` but the list we're passing in here is a `list[AuthVectorStore]`

2024-06-03 20:09 UTC, YrrepNoj commented on src/leapfrogai_api/backend/rag/index.py
> +                    vector_store_file.status = "failed"
Can we make the status string values an ENUM or statically defined somewhere in this file/class instead of using magic-strings?

This way, the places validating the status can compare against the static types instead of validating against more magic-strings.

2024-06-03 20:09 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +        new_vector_store.status = "completed"
Nit; We should probably be checking against static variables for the status instead of comparing/setting them to string literals.

2024-06-03 20:09 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +        deleted=bool(vector_store_deleted),
Question; `vector_store_deleted` was already a `bool` type. Are we trying to do something here that I might be missing?

2024-06-03 20:34 UTC, YrrepNoj commented on src/leapfrogai_api/data/crud_vector_store_file.py
> +    async def delete(self, vector_store_id: str, file_id: str) -> bool:  # pylint: disable=arguments-differ
The pylint annotations here feels like a smell. We are overloading an inherited method with different arguments. Is there a different we can architect this?

At the very least, we should leave a descriptive comment justifying why we are overloading these methods in this way.

2024-06-03 20:45 UTC, gphorvath commented on src/leapfrogai_api/data/crud_base.py
>          del dict_["created_at"]  # Ensure this is created by the database
done

2024-06-03 20:45 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/files.py
> +            status_code=405,
agreed, fixed.

2024-06-03 20:46 UTC, gphorvath commented on src/leapfrogai_api/backend/rag/document_loader.py
> +def supported_mime_type(mime_type: str) -> bool:
changed

2024-06-03 21:09 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +        deleted=bool(vector_store_deleted),
This was holdover from when these endpoints return something other than a bool. We simplified that, so removing this bool check.

2024-06-03 21:10 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +        new_vector_store.status = "completed"
changed to enum

2024-06-03 21:10 UTC, gphorvath commented on src/leapfrogai_api/backend/rag/index.py
> +                    vector_store_file.status = "failed"
changed to enum

2024-06-03 21:19 UTC, gphorvath commented on src/leapfrogai_api/backend/rag/index.py
> +                    vector_store_file.status = "failed"
now this enummed

2024-06-03 21:23 UTC, gphorvath commented on packages/api/zarf.yaml
> +  - name: DEFAULT_EMBEDDINGS_MODEL
This prevents the need for the caller to provide a field not specified in the OpenAI request model. When files are added to the Vector Store, the request type doesn't require an embeddings model be provided, but it will need to calculate the embeddings. For reference: https://platform.openai.com/docs/api-reference/vector-stores-files/createFile

I'll let you resolve this comment if you think this acceptable.

2024-06-03 21:27 UTC, gphorvath commented on src/leapfrogai_api/backend/rag/document_loader.py
> +    model = get_model_config().get_model_backend(os.getenv("DEFAULT_EMBEDDINGS_MODEL"))
This function was moved to indexing, removed the redundant function here.

2024-06-03 21:37 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +        data=crud_response or [],
In theory this would pare down anything from the superclass that wasn't needed. That said, I change crud_vector_store to return regular VectorStore object since we aren't using the additional user data anywhere.

2024-06-03 21:41 UTC, gphorvath commented on src/leapfrogai_api/data/crud_vector_store_file.py
> +    async def delete(self, vector_store_id: str, file_id: str) -> bool:  # pylint: disable=arguments-differ
I added a little more commentary here. The base class doesn't allow for two ids (vector_store and file) to be passed, so we needed to make an exception here.

2024-06-03 21:54 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/embeddings.py
> +        request = lfai.EmbeddingRequest(inputs=req.input)
fixed.

2024-06-03 22:00 UTC, gphorvath commented on src/leapfrogai_api/data/crud_base.py
> +            del dict_["id"]
In some cases the ID is provided, so we only delete the empty ID

2024-06-03 22:18 UTC, gphorvath commented on tests/integration/api/test_files.py
> +    with pytest.raises(HTTPException):
fixed

2024-06-04 14:57 UTC, YrrepNoj commented on src/leapfrogai_api/data/crud_vector_store_file.py
> +    async def delete(self, vector_store_id: str, file_id: str) -> bool:  # pylint: disable=arguments-differ
We control the base class we're using here though right? We could add an optional parameter of `eqMap: typing.Dict[str, str]` where the dictionary key is the name of the column and the value is the value we are setting the "equal to" clause to.

2024-06-04 15:05 UTC, YrrepNoj commented on packages/api/zarf.yaml
> +  - name: DEFAULT_EMBEDDINGS_MODEL
Hmm, I see we're trying to conform to the OpenAI request model, but we might need to do something different here. Our API should be as stateless as possible, it shouldn't have to know what other things exist or will exist later. The only caveat to this is that our API is watching for configmaps to see what valid model names are, but that is done in a way that is fully dynamic and not 'built into' the deployment.


The way this is currently implemented, you can only set the embeddings_model during the deploy time of the API. Users (or apps) would not be able to specify a different model, they would instead have to wait for someone to change the environment variable in their deployment manifest and redeploy the deployment.

2024-06-05 17:26 UTC, CollectiveUnicorn requested changes

2024-06-05 17:26 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +    return await crud_vector_store_file.get(filters={"vector_store_i": vector_store_id})
```suggestion
    return await crud_vector_store_file.get(filters={"vector_store_id": vector_store_id})
```

2024-06-06 17:46 UTC, YrrepNoj commented on src/leapfrogai_api/backend/rag/document_loader.py
> +        chunk_size=500,
Is there anything specifically relevant to the `500` value? 'Just to show' what?

2024-06-06 17:46 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +            status="in_progress",
Could this use the new `VectorStoreStatus` enum?

2024-06-06 17:57 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +            status="in_progress",
Good catch. Fixed.

2024-06-06 17:59 UTC, gphorvath commented on src/leapfrogai_api/backend/rag/document_loader.py
> +        chunk_size=500,
I updated the comment. Really what I mean is that these parameters are just some defaults suggested by Langchain and we may need to tune these once we start getting an idea how they perform

2024-06-06 20:04 UTC, alekst23 commented on src/leapfrogai_api/backend/rag/index.py
> +            raise FileAlreadyIndexedError("File already indexed")
How necessary is this custom exception class? It's a little redundant and counter-pattern to what we have elsewhere.

Would it be better to do something like this:
```python
raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail="File already indexed"
        ) 
```

2024-06-06 20:09 UTC, gphorvath commented on src/leapfrogai_api/backend/rag/index.py
> +            raise FileAlreadyIndexedError("File already indexed")
That is totally fair. I changed it!

2024-06-06 20:41 UTC, alekst23 commented on src/leapfrogai_api/backend/rag/index.py
> +                return await crud_vector_store_file.create(object_=vector_store_file)
Is there a reason we want to store an empty file that failed to process?

It feels like we can raise an error here.

2024-06-06 20:49 UTC, alekst23 commented on src/leapfrogai_api/backend/rag/index.py
> +                    vector_store_file.status = VectorStoreFileStatus.FAILED.value
Should we raise an exception here as well?

2024-06-07 15:17 UTC, alekst23 commented on src/leapfrogai_api/pyproject.toml
> +    "langchain >= 0.2.1",
Is there something we use langchain for besides `from langchain_core.embeddings.fake import FakeEmbeddings`?

We may want to rethink that approach if that's the case. Langchain has, in my past experience, caused huge dependency chain issues. It will attempt to download all sorts of libs and maybe models unpredictably.

2024-06-07 15:28 UTC, gphorvath commented on src/leapfrogai_api/pyproject.toml
> +    "langchain >= 0.2.1",
The short answer is yes.

We use it in the document loader and indexing service right now. We aren't currently using any features that should pull in models, but we are aware of some of them (like the context splitter).

2024-06-07 16:28 UTC, gphorvath commented on packages/api/zarf.yaml
> +  - name: DEFAULT_EMBEDDINGS_MODEL
@CollectiveUnicorn put in some issues to cover this, resolving for now.

2024-06-07 20:02 UTC, alekst23 commented on tests/pytest/leapfrogai_api/test_api.py
> +        ("/openai/v1/vector_stores", "list_vector_stores", ["GET"]),
Duplicate?

2024-06-07 20:04 UTC, alekst23 commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +@router.post("/{vector_store_id}")
Should the update/modify methods be "PATCH"? I think that's the more RESTFUL practice.

2024-06-07 20:04 UTC, gphorvath commented on tests/pytest/leapfrogai_api/test_api.py
> +        ("/openai/v1/vector_stores", "list_vector_stores", ["GET"]),
yes!

2024-06-07 20:08 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +@router.post("/{vector_store_id}")
That makes sense but the OpenAI spec specifies POST. Do you think we'll end up with a mismatch when using OpenAI libraries if we switch to PATCH?

2024-06-07 21:17 UTC, alekst23 commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +@router.post("/{vector_store_id}")
Yeah if we end up trying to do any sort of procedural comparison between the two, as you had suggested, we would end up with issues.

2024-06-07 21:20 UTC, alekst23 approved these changes

2024-06-07 23:02 UTC, CollectiveUnicorn approved these changes

2024-06-10 14:51 UTC, YrrepNoj approved these changes

2024-06-10 16:47 UTC, merged