Return finish reason field
defenseunicorns/leapfrogai pull request #493
Opened 2024-05-09 23:45 UTC by CollectiveUnicorn

When performing a completion or chat completion return the `finish_reason` according to the api spec.

2024-05-09 23:49 UTC, CollectiveUnicorn commented
Conforming to the specs for token length will require updating all of the backends. It assumes that there's the token counting function. TBD if doing that in this commit.

2024-05-16 15:05 UTC, justinthelaw reviewed
Just a nit, but are there any additional tests to check the token count field using the repeater model? If this should wait for other components to implement the consumption and display of the resulting token count, then recommend adding another issue to track that, if not done already.

2024-05-16 17:31 UTC, justinthelaw approved these changes
Minor nitpick for future LFAI members: we should add release-please or use renovate to change version numbers in our CI workflows and artifacts (Makefile, or in the future UDS tasks and task runner)

2024-05-16 19:31 UTC, justinthelaw submitted a review, later dismissed

2024-05-20 17:36 UTC, YrrepNoj requested changes

2024-05-20 17:36 UTC, YrrepNoj commented on src/leapfrogai_sdk/llm.py
> +        finish_reason: str = None,
I'm a little surprised our linter isn't catching this, but a `str` is not an object and therefor cannot be assigned `None`.

I think this might make more sense as an empty string for the zero-value?

2024-05-20 17:36 UTC, YrrepNoj commented on src/leapfrogai_sdk/llm.py
>          ) -> Generator[CompletionResponse, Any, Any]:
I'm noticing that this is an async (streamed) response but we're using `Generator` instead of `AsyncGenerator`.


Does `AsyncGenerator` make more sense here? Does now seem like a good time to update that?

2024-05-20 17:36 UTC, YrrepNoj commented on src/leapfrogai_sdk/llm.py
> +                finish_reason = "stop"
What are your thoughts on turning these finish_reasons into an Enum class instead of evaluating them as magic strings?

2024-05-20 17:36 UTC, YrrepNoj commented on src/leapfrogai_sdk/llm.py
> +            response.choices[0].finish_reason = finish_reason
Question; Why put this assignment behind the conditional? 

From my understanding, `responses.choices[0].finish_reason` will always be the 0-value at this point right?

2024-05-20 20:51 UTC, YrrepNoj commented on tests/pytest/leapfrogai_api/test_api.py
> +                    assert completion_tokens == 2
We discussed this in person; The repeater model just returns hardcoded values for the purpose of testing. 👍

2024-05-20 21:06 UTC, CollectiveUnicorn commented on src/leapfrogai_sdk/llm.py
> +        finish_reason: str = None,
It just converts it into an empty string, I'll replace it with an explicit empty string.

2024-05-20 21:27 UTC, CollectiveUnicorn commented on packages/repeater/chart/Chart.yaml
> +version: 0.7.3
Alright, I will go through the standard release channels prior to updating test dependencies. I can decrement these and do that separately.

2024-05-20 21:31 UTC, CollectiveUnicorn commented on src/leapfrogai_sdk/llm.py
> +                finish_reason = "stop"
That's fine, I replaced them with an enum containing the following values:
- NONE
- STOP
- LENGTH

2024-05-20 21:33 UTC, CollectiveUnicorn commented on src/leapfrogai_sdk/llm.py
> +            response.choices[0].finish_reason = finish_reason
You're right, this is unnecessary and have removed the conditional.

2024-05-20 21:43 UTC, CollectiveUnicorn commented on src/leapfrogai_sdk/llm.py
>          ) -> Generator[CompletionResponse, Any, Any]:
I'll test it and see if it works. If it does then I'll leave the references as AsyncGenerators

2024-05-20 22:30 UTC, CollectiveUnicorn commented on src/leapfrogai_sdk/llm.py
>          ) -> Generator[CompletionResponse, Any, Any]:
The async change appears to work

2024-05-20 22:33 UTC, CollectiveUnicorn commented on packages/repeater/chart/Chart.yaml
> +version: 0.7.3
All the version have been reverted back to 0.7.2 and the pipeline workflow now builds a dev version of repeater for the test

2024-05-21 01:29 UTC, CollectiveUnicorn commented on src/leapfrogai_sdk/llm.py
>          ) -> Generator[CompletionResponse, Any, Any]:
I take that back, there appears to be some issue

2024-05-21 17:06 UTC, CollectiveUnicorn commented on src/leapfrogai_sdk/llm.py
>          ) -> Generator[CompletionResponse, Any, Any]:
The issues has been resolved, it was just a mismatch in the number of parameters the AsyncGenerator was expecting vs the Generator. It works fine now.

2024-05-22 14:02 UTC, justinthelaw approved these changes

2024-05-22 17:59 UTC, YrrepNoj approved these changes

2024-05-22 18:14 UTC, gphorvath approved these changes

2024-05-22 18:18 UTC, merged