Add RAG Evals ADR
defenseunicorns/leapfrogai pull request #529
Opened 2024-05-16 15:55 UTC by jalling97

Adds an ADR for what framework we will use to handle RAG evaluations.

2024-05-16 18:19 UTC, CollectiveUnicorn requested changes

2024-05-16 18:19 UTC, CollectiveUnicorn commented on adr/0004-rag-eval-framework.md
> +  - [Background](#background)
This doesn't go anywhere

2024-05-16 19:46 UTC, CollectiveUnicorn approved these changes

2024-05-17 20:59 UTC, gphorvath commented on adr/0004-rag-eval-framework.md
> +This ADR will eventually influence the ADR for overall LLM evaluations.
Might be worth adding any additional context you have here in case it's a while before we start that ADR.

2024-05-17 20:59 UTC, gphorvath commented on adr/0004-rag-eval-framework.md
> +## Alternatives
Are there other alternatives that we should list, even if we didn't have time or think it necessary to evaluate them?

2024-05-17 20:59 UTC, gphorvath commented on adr/0004-rag-eval-framework.md
> +LeapfrogAI uses RAG to provide context-aware responses to users who have specific data they need to reference. In order to make sure RAG is operating at the levels we need it to, we need to get measu
I think this ADR should propose more than a framework. Ideally we would propose a few starting metrics and dataset(s) as well so that the next issue could be the MVP implementation.

2024-05-17 20:59 UTC, gphorvath commented on adr/0004-rag-eval-framework.md
> +## Decision
I would include some starting metrics and open source dataset(s) that we could use in our MVP implementation.

2024-05-17 20:59 UTC, gphorvath commented on adr/0004-rag-eval-framework.md
> +    - What internal tools are used to track evals over time?
I would remove mission hero specific language here. As far as LeapfrogAI as a product, we should have a generally applicable set of evals, probably derived from open source, as an example for how to properly use this evaluation framework and show/demonstrate the performance of LeapfrogAI against common benchmarks/metrics. Delivery can then create additional custom tests to target mission hero specific use cases.

2024-05-17 21:37 UTC, jalling97 commented on adr/0004-rag-eval-framework.md
> +This ADR will eventually influence the ADR for overall LLM evaluations.
Additional context as in what specifically made it feel more limited? Or were you thinking something else?

2024-05-17 21:38 UTC, jalling97 commented on adr/0004-rag-eval-framework.md
> +## Alternatives
A thread came up asking about LangChain, which it may be worthwhile to mention as it technically has an evaluation framework, but each of these can plug into LangChain if/when we want better traceability. Other than that nothing comes to mind for me.

2024-05-17 21:42 UTC, jalling97 commented on adr/0004-rag-eval-framework.md
> +## Decision
Based on the couple conversations I've had on the topic, I can definitely add some specific metrics we'll likely care about, but I'm hesitant to include any datasets, mostly because I think in order to reach MVP we'll need to curate a custom dataset from the start. That's just my opinion though and am happy to discuss further.

2024-05-17 21:45 UTC, barronstone requested changes
Good start! Thanks for pulling this together

2024-05-17 21:45 UTC, barronstone commented on adr/0004-rag-eval-framework.md
> +LeapfrogAI uses RAG to provide context-aware responses to users who have specific data they need to reference. In order to make sure RAG is operating at the levels we need it to, we need to get measu
IMO, this ADR recommends an evaluation `tool` rather than a `framework`. To me, a `framework` will be more holistic and encompass all of the things listed in the **Decision** section: metrics, dataset, integration into e2e, tracking and conveying results, etc. Deciding on which `tool` we use for evals is an important steps towards that end goal, but I'd backoff on calling this a `framework`.

2024-05-17 21:45 UTC, barronstone commented on adr/0004-rag-eval-framework.md
> +    - What internal tools are used to track evals over time?
I think I disagree with @gphorvath (or maybe I'm misunderstanding his comment). If the product team is only using common open-source datasets to evaluate models, how does that differentiate what we're doing from existing model scorecards and things that are already out there using those datasets? I think we need to generate "generally representative of DoD-things" datasets, for example doing RAG with NIST controls, Joint Pubs, DFARS, etc.

I agree with @gphorvath that Delivery can then create additional tests for specific mission heroes' use cases, utilizing actual mission data.

2024-05-17 21:45 UTC, barronstone commented on adr/0004-rag-eval-framework.md
> +## Alternatives
It would be good to mention Langsmith and why it wasn't included in your evaluation; some of the stuff in your Slack convo with Marshall earlier today

2024-05-17 21:45 UTC, barronstone commented on adr/0004-rag-eval-framework.md
> +**Arize Phoenix**: [Phoenix](https://phoenix.arize.com/) is another framework focused on both evaluation and observability. Phoenix has a lot to offer in terms of visualizations and LLM tracing, but
I would clarify that the visualization provided by Arize Phoeniz are very developer-centric. (At least that's how I interpreted them from the demo.) I don't think they will be super-helpful for communicating our eval results/decisions with mission heroes.

2024-05-17 21:45 UTC, barronstone commented on adr/0004-rag-eval-framework.md
> +The major RAG evaluation frameworks all revolve around LLM-enabled evaluations. While these are fast to get running and offer a lot of flexibility, our use case will likely demand custom evaluation m
The parenthetical statement "llm-based and non-llm" is confusing. Clarify what that means.

2024-05-20 16:36 UTC, gphorvath commented on adr/0004-rag-eval-framework.md
> +This ADR will eventually influence the ADR for overall LLM evaluations.
Just any details about how this related to the LLM Eval ADR so we know how it might influence it. A couple thoughts -

1. Did we pick a framework that works for both LLM and RAG?
2. Is there overlap between certain metrics?

2024-05-20 16:40 UTC, gphorvath commented on adr/0004-rag-eval-framework.md
> +## Decision
As Barron suggested above, I think if we pivot this PR to be the RAG Evaluation tool, then we can get away with not raising any datasets. That said, I think we should adopt some open source datasets in our evals in addition to custom dataset so we have some basis of comparison to other literature published by those without access to our data.

2024-05-20 16:43 UTC, gphorvath commented on adr/0004-rag-eval-framework.md
> +    - What internal tools are used to track evals over time?
I agree we will need some custom tests, but having some of the same baseline evals used in open source gives us a basis for comparison against literature on other tools published by those who don't have access to our data.

2024-05-20 16:45 UTC, gphorvath commented on adr/0004-rag-eval-framework.md
> +The major RAG evaluation frameworks all revolve around LLM-enabled evaluations. While these are fast to get running and offer a lot of flexibility, our use case will likely demand custom evaluation m
I think the differentiator here is that LLM-based implies an Evaluation LLM is used and non-LLM is more just raw math.

2024-05-20 19:02 UTC, jalling97 commented on adr/0004-rag-eval-framework.md
> +This ADR will eventually influence the ADR for overall LLM evaluations.
I added a note about how DeepEval can be used for general LLM evaluations and the section on RAGAS mentions that RAGAS-specific metrics are implemented directly in DeepEval.

2024-05-20 19:02 UTC, jalling97 commented on adr/0004-rag-eval-framework.md
> +## Alternatives
I added a section on LangChain/LangSmith :+1:

2024-05-20 19:08 UTC, jalling97 commented on adr/0004-rag-eval-framework.md
> +LeapfrogAI uses RAG to provide context-aware responses to users who have specific data they need to reference. In order to make sure RAG is operating at the levels we need it to, we need to get measu
I changed the references from `framework` to `toolset` to help make a better distinction :+1:

2024-05-20 19:10 UTC, jalling97 commented on adr/0004-rag-eval-framework.md
> +## Decision
That's fair. There will definitely be a lot of research to be done on a good representative open source dataset (i.e not just using the first one I could find :sweat_smile:), but since I changed references from `framework` to `toolset`, I think that can be a follow-up decision post `0.8.0`. How does that sound?

2024-05-20 19:14 UTC, jalling97 commented on adr/0004-rag-eval-framework.md
> +    - What internal tools are used to track evals over time?
Using a baseline open source dataset (TBD which one) certainly doesn't harm us in our evals goals, but I feel like even on the product side we should make a custom dataset that is more representative of the types of tasks we'll need to do RAG on in a delivery context. My high-level looks into dataset options didn't provide much, so I think we'll benefit from a custom dataset approach. And in that case, we can even potentially provide it to HuggingFace.

2024-05-20 19:14 UTC, jalling97 commented on adr/0004-rag-eval-framework.md
> +The major RAG evaluation frameworks all revolve around LLM-enabled evaluations. While these are fast to get running and offer a lot of flexibility, our use case will likely demand custom evaluation m
I added a statement defining the two directly :+1:

2024-05-24 20:01 UTC, merged