feat(ui): Utilize OpenAI for backend
defenseunicorns/leapfrogai pull request #553
Opened 2024-05-22 14:32 UTC by andrewrisse

closes #540 
closes #528 
closes #414 

1. Changes naming convention to use threads instead of conversations
2. Refactor to use OpenAI types for threads, messages, and assistants
3.  No longer saves threads, messages, and assistants directly to Supabase, but instead uses OpenAI endpoints

2024-05-22 18:44 UTC, BillyFigueroa commented on src/leapfrogai_ui/src/lib/components/ChatSidebar.svelte
> +    await goto('/chat');
Is the await needed here?

2024-05-22 18:54 UTC, BillyFigueroa commented on src/leapfrogai_ui/src/lib/helpers/dates.test.ts
> +      const todayOverride = new Date('2024-03-01T00:00');
Has anyone here at the company discussed using a date library? date-fns or something?

Dates can be a PITA

2024-05-23 20:21 UTC, andrewrisse commented on src/leapfrogai_ui/src/lib/components/ChatSidebar.svelte
> +    await goto('/chat');
I get a lint error if no await

2024-05-23 20:32 UTC, andrewrisse commented on src/leapfrogai_ui/src/lib/helpers/dates.test.ts
> +      const todayOverride = new Date('2024-03-01T00:00');
haven't had that discussion, but haven't had a need for one yet, although not opposed to bringing it up sometime

2024-05-23 23:05 UTC, CollectiveUnicorn requested changes

2024-05-24 15:53 UTC, andrewrisse commented on src/leapfrogai_ui/src/lib/components/ChatSidebar.svelte
> +  $: activeThread = $threadsStore.threads.find((thread) => thread.id === $page.params.thread_id);
it would just create a new thread once you created a message. I tested this out and confirmed the app does not crash

2024-05-24 15:58 UTC, andrewrisse commented on packages/supabase/migrations/20240522135041_drop_tables_0.8_migration.sql
> +            -- do nothing, fail silently
confirmed it works with those and removed

2024-05-24 16:11 UTC, CollectiveUnicorn commented on src/leapfrogai_ui/src/lib/components/ChatSidebar.svelte
> +  $: activeThread = $threadsStore.threads.find((thread) => thread.id === $page.params.thread_id);
Ok cool, just wanted to make sure that there wasn't a potential large failure lurking in the background.

2024-05-24 19:06 UTC, BillyFigueroa commented on src/leapfrogai_ui/src/routes/api/threads/update/label/+server.ts
> +  try {
I have noticed these 400 responses seem common and can probably be turned into a utility function. This is a suggestion however, so I will still approve the PR

from something like this...
```JavaScript
  try {
    requestData = await request.json();
    const isValid = await updateThreadLabelSchema.isValid(requestData);
    if (!isValid) error(400, 'Bad Request');
  } catch {
    error(400, 'Bad Request');
  }
```

to something like...

```JavaScript
   // one liner to check if isValid
   await checkSchemaValidity(request);
   
   // Inside utility file
   const checkSchemaValidity = async (request: { id: string; label: string }) => {
      try {
         requestData = await request.json();
         const isValid = await updateThreadLabelSchema.isValid(requestData);

         if (!isValid) error(400, 'Bad Request');
       } catch {
         error(400, 'Bad Request');
       }

       return isValid;
   }
```

2024-05-24 19:07 UTC, BillyFigueroa submitted a review, later dismissed
Big PR but great work

2024-05-24 19:24 UTC, andrewrisse commented on src/leapfrogai_ui/src/routes/api/threads/new/server.test.ts
> +import { getFakeThread } from '../../../../../testUtils/fakeData';
note - can't do alias imports in playwright, so did not change those

2024-05-24 19:24 UTC, andrewrisse commented on src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.server.ts
> +    console.log(
updated

2024-05-24 20:38 UTC, BillyFigueroa approved these changes

2024-05-24 21:42 UTC, CollectiveUnicorn approved these changes

2024-05-25 02:12 UTC, merged