feat(api): Threads Endpoints
defenseunicorns/leapfrogai pull request #554
Opened 2024-05-22 21:09 UTC by CollectiveUnicorn

Closes: https://github.com/defenseunicorns/leapfrogai/issues/417

2024-06-05 17:09 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/types.py
> +    metadata: Optional[dict] = Field(default=None)
I had these initially as object but was running into issues with FastAPI serialization when trying to use object instead of dict. Is vscode suggesting using Optional[object]?

2024-06-05 17:11 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/types.py
> +    metadata: Optional[dict] = Field(default=None)
But some issues may have gotten conflated together, I'll try the object again.

2024-06-05 17:14 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/threads.py
> +        new_thread: Thread = await crud_thread.create(object_=thread)
Fixed this

2024-06-11 03:32 UTC, gphorvath requested changes

2024-06-11 03:32 UTC, gphorvath commented on src/leapfrogai_api/.gitignore
I have another comment below on the .jwt file. Depending on how you resolve that you may not need this .gitignore. 

If you do need it, I would move this to the root .gitignore so we don't accidently push the .jwt file if it gets generated anywhere in the project hierarchy.

2024-06-11 03:32 UTC, gphorvath commented on src/leapfrogai_api/Makefile
> +new-api-user:
nit - maybe just call this `user` instead of `new-api-user`

2024-06-11 03:32 UTC, gphorvath commented on src/leapfrogai_api/backend/types.py
> +from typing import Literal, Optional, List
Minor nit, but In a previous PR we had discussed switch to `list` and `| None` instead of `List` and `Optional`. It's a little bit of a break from the convention of the rest of this file to bring them back.

2024-06-11 03:32 UTC, gphorvath commented on src/leapfrogai_api/data/crud_run.py
> +    async def create(self, object_: Run) -> AuthRun | None:
I think we decided to switch to return the base object instead of the Auth object. It looks like you return the base object for Threads, but the Auth object for runs/messages. Any reason for the delta?

2024-06-11 03:32 UTC, gphorvath commented on supabase/migrations/20240522141100_threads_runs_messages_steps.sql
> +    REFERENCES run_objects (id);
Minor nit, but can't these be declared on table creation instead of altering the table since we are adding all these in the same PR?

2024-06-11 03:32 UTC, gphorvath commented on src/leapfrogai_api/Makefile
> +	echo "SUPABASE_ANON_KEY=$$SUPABASE_ANON_KEY" >> .jwt; \
I've actually been thinking about this one... The testing feature in VS Code automatically hooks into the `.env` file in the root of the project and we already gitignore .env... maybe we should be writing to that instead?

2024-06-11 03:32 UTC, gphorvath commented on src/leapfrogai_api/backend/types.py
> +    metadata: Optional[dict] = Field(default=None)
We have this issue in several places object vs dict on the types...we probably should test with an OpenAI client library and update all the types to be consistent.

2024-06-11 16:05 UTC, gphorvath commented on supabase/migrations/20240522141100_threads_runs_messages_steps.sql
this needs to move to `leapfrogai/packages/api/supabase/migrations`

2024-06-11 18:35 UTC, gphorvath commented on src/leapfrogai_api/data/crud_run.py
> +    async def create(self, object_: Run) -> AuthRun | None:
resolved

2024-06-11 18:36 UTC, gphorvath commented on supabase/migrations/20240522141100_threads_runs_messages_steps.sql
moved

2024-06-11 18:36 UTC, gphorvath commented on supabase/migrations/20240522141100_threads_runs_messages_steps.sql
> +    REFERENCES run_objects (id);
done

2024-06-11 18:54 UTC, gphorvath commented on src/leapfrogai_api/backend/types.py
> +from typing import Literal, Optional, List
resolved to be consistent with the rest of types.

2024-06-11 19:07 UTC, gphorvath commented on src/leapfrogai_api/Makefile
> +new-api-user:
done

2024-06-11 19:08 UTC, gphorvath commented on src/leapfrogai_api/Makefile
> +	echo "SUPABASE_ANON_KEY=$$SUPABASE_ANON_KEY" >> .jwt; \
done

2024-06-11 19:08 UTC, gphorvath commented on src/leapfrogai_api/.gitignore
done

2024-06-11 19:24 UTC, gphorvath submitted a review, later dismissed

2024-06-12 00:45 UTC, YrrepNoj commented on tests/integration/api/test_vector_stores.py
> -        expires_after=ExpiresAfter(anchor="last_active_at", days=0),
Question: why not set the `expires_after` field anymore?

2024-06-12 04:42 UTC, gphorvath commented on tests/integration/api/test_vector_stores.py
> -        expires_after=ExpiresAfter(anchor="last_active_at", days=0),
In this particular case we were encounter an issue where the vector store expires before the next step in the test. We also test for expiration still, so this test doesn't need to expire.

2024-06-12 18:51 UTC, gphorvath approved these changes

2024-06-12 19:42 UTC, YrrepNoj approved these changes

2024-06-12 19:50 UTC, merged