486 better database migrations
defenseunicorns/leapfrogai pull request #570
Opened 2024-05-29 21:01 UTC by YrrepNoj

TODO: 
- [ ] Update documentation of places that talk about database migration
- [ ] Add some documentation about handling databases that were initialized (and migrated) prior to this PR.
- [ ] So many other things..

2024-06-06 18:18 UTC, jalling97 submitted a review, later dismissed

2024-06-07 18:38 UTC, CollectiveUnicorn requested changes

2024-06-07 18:38 UTC, CollectiveUnicorn commented on packages/api/supabase/migrations/20240422015807_v0.7.0-all.sql
> -  ('file_bucket', 'files', true);
The removal of this code causes the openai files endpoint's upload to fail. As there's no longer an entry in `storage.buckets` for the `files` folder, so it effectively does not exist. There is a query [here](https://github.com/defenseunicorns/leapfrogai/blob/f31f1905f96e5fcaf10cacca88f931384e59a8bc/packages/api/supabase/migrations/20240516152530_enable_rls.sql#L7) that sets it to private, you can probably set it to private within the insert command instead without issue.

2024-06-07 18:43 UTC, CollectiveUnicorn requested changes

2024-06-07 18:43 UTC, CollectiveUnicorn commented on packages/api/supabase/Dockerfile
> +RUN rm supabase_linux_amd64.tar.gz
Do we need to grab arm releases as well?

2024-06-07 18:43 UTC, CollectiveUnicorn commented on src/leapfrogai_ui/supabase/Dockerfile
> +RUN rm supabase_linux_amd64.tar.gz
Do we need to grab arm releases as well?

2024-06-10 16:07 UTC, YrrepNoj commented on packages/api/supabase/migrations/20240422015807_v0.7.0-all.sql
> -  ('file_bucket', 'files', true);
good catch, added

2024-06-10 16:08 UTC, YrrepNoj commented on src/leapfrogai_ui/supabase/Dockerfile
> +RUN rm supabase_linux_amd64.tar.gz
Yes, good catch. Added logic so this works for arm targets as well

2024-06-10 16:08 UTC, YrrepNoj commented on packages/api/supabase/Dockerfile
> +RUN rm supabase_linux_amd64.tar.gz
Yes, good catch. Added logic so this works for arm targets as well

2024-06-10 17:55 UTC, CollectiveUnicorn approved these changes

2024-06-10 18:31 UTC, jalling97 approved these changes

2024-06-10 18:33 UTC, merged