feat(api): Runs and Run steps endpoints
defenseunicorns/leapfrogai pull request #583
Opened 2024-06-03 18:56 UTC by CollectiveUnicorn

2024-06-13 16:13 UTC, gphorvath requested changes
We have a circular import because we are depending on our own route.

2024-06-13 16:13 UTC, gphorvath commented on src/leapfrogai_api/backend/converters.py
> +from leapfrogai_api.routers.openai.threads import create_message
We should avoid an import from the router. This is causing a circular import. We should pull this into it's own class, similarly to index.py, and have both the router and this take a dependency on it.

2024-06-13 16:13 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/requests/create_thread_request.py
> +from leapfrogai_api.routers.openai.threads import create_message, delete_message
We should avoid an import from the router. This is causing a circular import. We should pull this into it's own class, similarly to index.py, and have both the router and this take a dependency on it.

2024-06-13 16:13 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request.py
> +from leapfrogai_api.routers.openai.threads import create_message
We should avoid an import from the router. This is causing a circular import. We should pull this into it's own class, similarly to index.py, and have both the router and this take a dependency on it.

2024-06-13 18:34 UTC, YrrepNoj commented on make-supabase.mk
> +jwt:
Would it make sense to take advantage of the scriptyness of Python and call something like [this utils function](https://github.com/defenseunicorns/leapfrogai/blob/74911a8a2edeafa82488531e382b1b8c3c9c9bd6/tests/e2e/utils.py#L38-L54) here?

This would have the double benefit of
1) testing our test utils even more
2) have only one overhead function of fetching jwts to maintain instead of two.
3) Not have to install additional dependencies (`xclip` used above is not native to all machines)

2024-06-14 03:09 UTC, CollectiveUnicorn commented on tests/conftest.py
> +def pytest_configure(config):
This has been reverted in expectation of more comprehensive tests coming in another PR.

2024-06-14 14:29 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/threads.py
> +) -> Run | StreamingResponse:
The returned non-streaming Run object contains a user_id.

2024-06-14 14:46 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/threads.py
> +) -> Run | StreamingResponse:
The returned non-streaming Run object contains a user_id.

2024-06-14 14:54 UTC, gphorvath commented on packages/api/supabase/migrations/20240611111500_runs_steps.sql
> +    assistant_id uuid references assistant_objects (id) on delete set null,
I'm starting to think this should be a `cascade` instead of a `set null` so that Runs get cleaned up when an assistant is deleted.

2024-06-14 17:05 UTC, CollectiveUnicorn commented on packages/api/zarf.yaml
> +    default: http://supabase-kong.leapfrogai.svc.cluster.local:80
Will hardcode this in the values file

2024-06-14 17:14 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/requests/create_thread_request.py
> +            message_content = await self.get_message_content()
Issue with this not working

2024-06-14 17:23 UTC, CollectiveUnicorn commented on tests/integration/api/test_threads.py
> +    CreateThreadRequest,
Open for a future refactor will add an issue for this

2024-06-14 17:31 UTC, alekst23 commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
> +        )
```suggestion
        crud_assistant = CRUDAssistant(session)
        assistant: Assistant | None = await crud_assistant.get(filters=FilterAssistant(id=self.assistant_id))
```
You will also need to add this to top:
`from leapfrogai_api.data.crud_assistant import CRUDAssistant, FilterAssistant`

2024-06-14 17:32 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/threads.py
> +) -> Run | StreamingResponse:
Will eliminate

2024-06-14 18:45 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/requests/create_thread_request.py
> +            message_content = await self.get_message_content()
This has been resolved

2024-06-14 18:51 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
> +        )
This has been resolved

2024-06-14 19:40 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/threads.py
> +) -> Run | StreamingResponse:
Done

2024-06-14 19:40 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/threads.py
> +) -> Run | StreamingResponse:
This is has been removed at the runs level

2024-06-14 19:44 UTC, CollectiveUnicorn commented on tests/integration/api/test_threads.py
> +    CreateThreadRequest,
Issue has been added here: https://github.com/defenseunicorns/leapfrogai/issues/633

2024-06-14 19:46 UTC, CollectiveUnicorn commented on make-supabase.mk
> +jwt:
This has been reverted to be included in more comprehensive tests coming in another PR.

2024-06-16 17:56 UTC, gphorvath commented on packages/api/supabase/migrations/20240611111500_runs_steps.sql
> +    assistant_id uuid references assistant_objects (id) on delete set null,
In testing I determined that assistant_id is a required parameter for the Run object to pass schema validation. I think for now, we should cascade delete to prevent an invalid schema.

2024-06-16 19:29 UTC, gphorvath commented on packages/api/supabase/migrations/20240611111500_runs_steps.sql
> +    assistant_id uuid references assistant_objects (id) on delete set null,
fixed

2024-06-17 06:05 UTC, gphorvath submitted a review, later dismissed

2024-06-17 15:38 UTC, gphorvath commented
Latest Updates:
* Removed all run-steps references as we didn't full implement (schema, crud operations, etc.)
* Split up integration tests by route
* Split up threads route into threads/messages/runs
* Removed RAG deployment from UDS bundles (this PR adds it via API)
* Added check for supported tools to threads/assistants endpoints that accept tools and tests to verify.
* Fix: Bug when assistant is deleted and Run remains behind - now run cascade deletes on assistant delete.
* Fix: Modifying run was failing schema check.
* Refactored threads/runs modify endpoints to ensure we aren't overwriting any unmodifiable content.

2024-06-17 16:01 UTC, YrrepNoj commented on src/leapfrogai_api/backend/grpc_client.py
> +async def stream_chat_completion_raw(
Question; when would we call `stream_chat_completion_raw()` vs `stream_chat_completion()`

2024-06-17 16:22 UTC, YrrepNoj commented on src/leapfrogai_api/data/crud_run.py
> +        del run.user_id
We are type hinting that this function is returning a `Run obj`. This `run` variable is technically an `AuthRun`. Deleting the `run.user_id` gives. the RunAuth the same 'shape' as a Run, but it is not a Run.

We should probably make sure we are returning an actual Run type instead of something that has the same 'shape' as a Run.

2024-06-17 19:22 UTC, gphorvath commented on packages/api/supabase/migrations/20240611111500_runs.sql
> +    file_ids uuid[],
Should this be a foreign key?

2024-06-17 19:46 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
> +            random_uuid: UUID = uuid.uuid4()
We probably shouldn't be generating UUIDs in code

2024-06-18 14:33 UTC, YrrepNoj approved these changes
This is a big PR that has been the work of a lot of effort. There are several conversation items that will turn into issues in our backlog. Thanks everyone for their hard work in implementing this feature.

In the future, lets set the goal of maintaining smaller PRs and introducing more testing. I'm sure I could spend another couple working days looking through this PR but I believe it would be more efficient to merge this in now (since it is in a working state where we can iterate on it independently) and start working on adding improvements in separate PRs.

Thanks again for everyones hard work in developing, reviewing, and testing this PR.

2024-06-18 15:08 UTC, jalling97 approved these changes

2024-06-18 15:51 UTC, gphorvath commented on packages/api/supabase/migrations/20240611111500_runs.sql
> +    file_ids uuid[],
Added ticket for this https://github.com/defenseunicorns/leapfrogai/issues/646

2024-06-18 15:57 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
> +            random_uuid: UUID = uuid.uuid4()
Added an issue for this: https://github.com/defenseunicorns/leapfrogai/issues/647

2024-06-18 16:00 UTC, gphorvath commented on src/leapfrogai_api/data/crud_run.py
> +        del run.user_id
Added an issue for this: https://github.com/defenseunicorns/leapfrogai/issues/648

2024-06-18 16:01 UTC, merged