chore(test): Create Testing Strategy ADR
defenseunicorns/leapfrogai pull request #586
Opened 2024-06-03 20:10 UTC by alekst23

# Background
We need to have a consolidated and clearly defined approach to testing our systems. Currently, we don't have a clear definition of what features and functions should be test at each level, and we mix some integration and system testing.

It is also currently difficult for new developers to spin up a test suite in a new environment. We should have tests work out of the box.

# Description
This PR creates an ADR to help us organize our ideas about testing.

# TODO
This file lacks a unified UI testing strategy

2024-06-03 20:19 UTC, CollectiveUnicorn requested changes

2024-06-03 20:19 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy
Its missing the `.md` extension

2024-06-03 20:24 UTC, jalling97 commented on adr/0005-testing-strategy
> +(1) We should clearly define the levels of testing that we want to do, and the featuers that we should test at each one.
misspelling of features

2024-06-03 20:29 UTC, CollectiveUnicorn requested changes

2024-06-03 20:29 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy
> +We need to have a consolidated and clearly defined approach to testing our systems. Currently, we don't have a clear definition of what features and functions should be test at each level, and we mix
```suggestion
We need to have a consolidated and clearly defined approach to testing our systems. Currently, we don't have a clear definition of what features and functions should be tested at each level, and we mix some integration and system testing.
```

2024-06-03 20:29 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy
> +(7) We should use `conftest.py` to set up the dev environment variables, and to create global test fixtures.
Is it necessary to call out specific library functions for tests?

2024-06-03 20:46 UTC, CollectiveUnicorn requested changes

2024-06-03 20:46 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy.md
> +(4) We should be testing for both success and failure cases.
Can we add more detail here, I wouldn't think that its necessary to enumerate all failure cases for instance. But we may need to have a wider discussion about this because I'm sure there's a number of varying perspectives.

2024-06-03 20:46 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy.md
> +### Unit Testing
I believe there was some desire to minimize the amount of unit tests created to avoid the code becoming overly rigid/brittle. Might be worth adding as discussion topic as a team.

2024-06-03 20:46 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy.md
> +We need to integrate UI testing strategy into this document.
Will probably need @andrewrisse to really fill this section out, but the UI tests use Playwright atm and cover at least some e2e and integration tests. The svelte server api should probably have all those endpoints tested as well as all the UI features.

2024-06-03 21:12 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy.md
> +We need to integrate UI testing strategy into this document.
Actually, I'm going to resolve this. Since its a todo.

2024-06-04 14:29 UTC, alekst23 commented on adr/0005-testing-strategy
> +(7) We should use `conftest.py` to set up the dev environment variables, and to create global test fixtures.
I did not want to get too granular, but the `conftest.py` file is specific to implementing `pytest` properly so I wanted to point that out for devs.

2024-06-04 14:46 UTC, alekst23 commented on adr/0005-testing-strategy.md
> +### Unit Testing
We should definitely get the rest of the team's feedback about how much unit testing we want to integrate. 

You are right in principle, but in theory we should be maintaining our tests together with the app code.

It's a bit of a trade off. Your app code is more rigid, but the application itself will be more resilient to failure.

2024-06-04 14:46 UTC, alekst23 commented on adr/0005-testing-strategy
> +(1) We should clearly define the levels of testing that we want to do, and the featuers that we should test at each one.
Ah, spelling. My forteh

2024-06-04 21:01 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy
> +(7) We should use `conftest.py` to set up the dev environment variables, and to create global test fixtures.
The `conftest.py` makes sense to standardize around.

For `unittest.mock.patch` and `pytest.mark.parametrize` I personally would just prefer examples of how to utilize these effectively so they can be easily used where appropriate. As they won't be the best tools for all cases.

2024-06-12 14:00 UTC, alekst23 commented on adr/0005-testing-strategy
> +(7) We should use `conftest.py` to set up the dev environment variables, and to create global test fixtures.
Yeah that might be getting too granular. I definitely want to set up a template for us to follow through some examples of using these decorators and functions, but it's hard to put that in the ADR.

2024-06-12 23:41 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy.md
> +(4) We should be testing for both success and failure cases.
I like the idea of doing it, but I'm worried about its maintanability vs the provided value. There's a lot of overhead involved with trying to enumerate all possible edge cases.

2024-06-12 23:46 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy.md
> +### Unit Testing
Yeah its all a tradeoff, I would prefer that we be diligent in ensuring that we're not just creating tests for the sake of creating test and that they provide clear value in terms of catching regressions, bugs, or serving as documentation.

2024-06-20 15:36 UTC, alekst23 commented on adr/0005-testing-strategy.md
> +(4) We should be testing for both success and failure cases.
That's true, and I don't want to stretch this concept to absurdity. However, if we don't have at least some coverage of edge cases, we are going to see those come up as runtime errors that may be difficult to find and troubleshoot.

CRUDBase is a good example for this purpose. The code base is very simple, but there are some edge cases, like when the DB fails to return a properly formatted response. If we run those through the tests, we see that the system fails with an abstract TypeError or something like that. However, we may choose to return None or an empty set in some cases, instead of throwing an error, indicating that `get` or `list` did not find anything.

2024-06-20 15:38 UTC, alekst23 commented on adr/0005-testing-strategy.md
> +### Unit Testing
Yeah I am not a fan of code coverage just for the sake of code coverage. I do love testing edge conditions though =D

2024-06-20 16:31 UTC, CollectiveUnicorn commented on adr/0005-testing-strategy.md
> +(4) We should be testing for both success and failure cases.
That definitely makes sense, given that I think this is good sense I think we're all aware of not going overboard with this.

2024-06-20 16:31 UTC, CollectiveUnicorn approved these changes

2024-07-08 16:39 UTC, merged