add supabase migrations documentation
defenseunicorns/leapfrogai pull request #592
Opened 2024-06-05 19:52 UTC by jalling97

Adds documentation for the supabase migrations work in #486

2024-06-06 12:31 UTC, barronstone requested changes
Great start! Just a couple of minor nits and a recommendation to add some more context about the what/why/when for migrations.

2024-06-06 12:31 UTC, barronstone commented on packages/supabase/README.md
>  Go to `https://supabase-kong.uds.dev`. The login is `supabase-admin` the password is randomly generated in a cluster secret named `supabase-dashboard-secret`
Add note to clarify the `uds.dev` is the domain for locally deployed LeapfrogAI components, like Supabase.

We've had mission heroes reach out because they saw `uds.dev` referenced in our docs, and tried to hit that on the Internet, not realizing it was only for local deployments. That can cause confusion.

2024-06-06 12:31 UTC, barronstone commented on packages/supabase/README.md
> +Migrations are handled using the [Supabase CLI](https://supabase.com/docs/guides/cli/getting-started?queryGroups=platform&platform=linux). The Supabase CLI automatically handles new migrations and ke
nit: seeing "db" written in lower case feels strange. I know that's how it's used in the CLI command... recommend putting it in a code box, as `db`

2024-06-06 12:31 UTC, barronstone commented on packages/supabase/README.md
> +- Migrations should only update tables that have to do with their associated package. For example, the UI should not have associated migrations that affect the VectorDB, so no migration files doing s
nit: I recommend replacing "VectorDB" with "vector database" because [VectorDB](https://vectordb.com/) is a proper name; however, I think you are referring to a vector database in general here.

2024-06-06 12:31 UTC, barronstone commented on packages/supabase/README.md
> +  - add a migration-job.yaml in the package's template directory
nit: put `migration-job.yaml` in a code text block

2024-06-06 12:31 UTC, barronstone commented on packages/supabase/README.md
> +
I recommend adding a couple of sentences at the start of the **Supabase Migrations** section to explain the what/why/when before going into the **Approach**. As currently written, this section jumps straight into the "how" to do migrations. A database n00b (like me) would benefit from some additional context first:

- Why would I need to go through this migration process?
- What does the migration accomplish?
- When would I need to go through the migration? e.g., Do I migrate every time I update versions of LeapfrogAI?

2024-06-06 14:02 UTC, jalling97 commented on packages/supabase/README.md
>  Go to `https://supabase-kong.uds.dev`. The login is `supabase-admin` the password is randomly generated in a cluster secret named `supabase-dashboard-secret`
Added a note :+1:

2024-06-06 14:03 UTC, jalling97 commented on packages/supabase/README.md
> +Migrations are handled using the [Supabase CLI](https://supabase.com/docs/guides/cli/getting-started?queryGroups=platform&platform=linux). The Supabase CLI automatically handles new migrations and ke
fixed :+1:

2024-06-06 14:03 UTC, jalling97 commented on packages/supabase/README.md
> +- Migrations should only update tables that have to do with their associated package. For example, the UI should not have associated migrations that affect the VectorDB, so no migration files doing s
fixed :+1:

2024-06-06 14:03 UTC, jalling97 commented on packages/supabase/README.md
> +  - add a migration-job.yaml in the package's template directory
fixed :+1:

2024-06-06 14:03 UTC, jalling97 commented on packages/supabase/README.md
> +
Added more context; let me know if that looks good to you :+1:

2024-06-07 17:35 UTC, barronstone approved these changes
Thanks for making those changes!

2024-06-12 00:35 UTC, YrrepNoj submitted a review, later dismissed

2024-06-17 21:07 UTC, jalling97 commented
This is now up to date with https://github.com/defenseunicorns/leapfrogai/pull/630

2024-06-18 16:03 UTC, YrrepNoj approved these changes

2024-06-18 16:04 UTC, gphorvath approved these changes

2024-06-18 16:04 UTC, merged