594 featapi assistants helper function to build vector stores
defenseunicorns/leapfrogai pull request #597
Opened 2024-06-06 20:12 UTC by jalling97

- Adds a helper function to automatically create a vector store when a new assistant is created if files are provided

2024-06-11 19:20 UTC, gphorvath commented on src/leapfrogai_api/data/async_supabase_vector_store.py
This file should be fully moved into index.py now.

2024-06-13 18:19 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +        and tool_resource[1] is not None
This seems pretty complex. Is this effectively the same thing?

```python
if request.tool_resources and request.tool_resources.code_interpreter is not None:
```

2024-06-13 18:19 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +        for tool_resource in request.tool_resources
1) Same comment as above about this being a complex-looking statement.

2) Should we be checking that the instance of ToolResourcesFileSearch is not None?

2024-06-13 18:27 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +        and tool_resource[1] is not None
Yes I believe so, I'll change and test to make sure.

2024-06-13 18:43 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +        for tool_resource in request.tool_resources
Added that and verified that works as a check

2024-06-13 22:20 UTC, jalling97 commented
Proof that all integration tests are passing
![Screenshot from 2024-06-13 18-15-54](https://github.com/defenseunicorns/leapfrogai/assets/44934218/a5a56c8e-395b-4eec-9958-4a01eb868b20)

2024-06-14 20:12 UTC, jalling97 commented
Refactored a few tests so that I'm no longer using the `pytest.mark.xfail` decorator
![Screenshot from 2024-06-14 16-10-04](https://github.com/defenseunicorns/leapfrogai/assets/44934218/5ee6acb2-93da-4a11-8006-9ab86273526b)

2024-06-14 20:47 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +                await crud_vector_store.get(filters=FilterVectorStore(id=ids[0]))
Should we be catching the return of this `get()` call and check if it is None? We are raising an exception if an invalid VectorStore ID is provided, but should an expired VectorStore also raise an exception?

2024-06-14 20:47 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +                None  # remove vector_stores if it's there
I am probably missing something here, but what is the intuition behind setting this to None?

2024-06-14 20:47 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +                await crud_vector_store.get(filters=FilterVectorStore(id=ids[0]))
Same comment as above about what if it makes sense to validate against a `None` return here?

2024-06-14 20:47 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +                file_ids=vector_stores[0]["file_ids"],
I'm having a hard time following the typing here.

I understand that we expect `len(vector_stores) == 1` so `vector_store[0]` makes enough sense to me. But I'm having a hard time determining what _type_ `vector_store[0]` will return and why we are obtaining a field with `vector_stores[0]["file_ids"]` (and what that _type_ will be as an end result).

2024-06-14 20:59 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +                await crud_vector_store.get(filters=FilterVectorStore(id=ids[0]))
Yeah that's a good catch, I didn't think about expiry situations. I can update the check and wherever else that's relevant

2024-06-14 21:04 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +                None  # remove vector_stores if it's there
Based on how Openai does it, it's valid for a createAssistant request to have the `vector_stores` field under `file_search` ([source](https://github.com/openai/openai-python/blob/a33712e161eacdcfead297da3f4a5bc491732e3f/src/openai/types/beta/assistant_create_params.py#L196)), but not after the assistant has been created ([source](https://github.com/openai/openai-python/blob/a33712e161eacdcfead297da3f4a5bc491732e3f/src/openai/types/beta/assistant.py#L22)). 

We're interpreting the reason why to be that once the vector store is created, its `id` gets linked to the assistant, meaning there's no reason to keep the `file_ids` that came with the initial request, as that's not maintained and could get out of sync. So it's best to remove it after the vector store is created, if it exists.

2024-06-14 21:35 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +                await crud_vector_store.get(filters=FilterVectorStore(id=ids[0]))
Updated :+1:

2024-06-14 21:36 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +                await crud_vector_store.get(filters=FilterVectorStore(id=ids[0]))
Updated :+1:

2024-06-14 21:36 UTC, jalling97 commented
Passing tests from most recent changes
![Screenshot from 2024-06-14 17-36-21](https://github.com/defenseunicorns/leapfrogai/assets/44934218/25c6bb02-8542-48f1-af94-f7ae422240e1)

2024-06-18 04:39 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +                file_ids=vector_stores[0]["file_ids"],
Ok I think that makes sense, a few QoL requests
1) at the start of this elif block, can we set a variable to make it more clear that we are working with a dict, maybe something like `vector_store_dict = vector_stores[0]`
2) It would probably be wise to do some validation on the dict and throw in a `if "file_ids" not in my_dict: raise exception`
   - We have a similar-ish check above, but we would run into an exception before actually calling the `indexing_service.file_ids_are_valid()` function because we'll get a key_error when trying to get the value from the dictionary.
   
   
 3) There is another place above in this file (around line 74) where doing at least `2)` would be useful.

2024-06-18 13:53 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +                file_ids=vector_stores[0]["file_ids"],
Added these :+1:

2024-06-21 19:05 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/assistants.py
There seems to be a lot of duplication between `create_assistant` and `modify_assistant` are you able to pull out the duplicate code to reduce some of the bloat a bit?

2024-07-01 21:08 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +        ids_len = len(ids) if ids is not None else 0
If `request.tool_resources.file_search` exists, then the `vector_stores_ids` field will also exist based on the pydantic typing. But it's likely that the field is going to be set to `None` (in the event you're providing `file_ids` instead). So that `getattr` would see that the field itself exists but set ids to `None`, which is why that check gets made. There's probably a more efficient way to do it but at some point I'm pretty sure you have to check whether that field is a `None` type or not.

2024-07-01 21:20 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +        vector_stores_len = len(list(vector_stores)) if vector_stores is not None else 0
This has the same problem that I mentioned with `ids`, but it's still a more efficient way to do it than I was with the `hasattr` check so I agree that this makes more sense. I still believe you have to check to make sure it's not a `None` type so you don't get a `TypeError`.

Additionally, since the OpenAI [assistant_create_params](https://github.com/openai/openai-python/blob/a33712e161eacdcfead297da3f4a5bc491732e3f/src/openai/types/beta/assistant_create_params.py#L205) `ToolResourcesFileSearch` only states that `vector_stores` is an iterable, the list conversion is just a safety check in case an iterator or another `Iterable` gets passed. In the event it is a list, a list conversion on a list is still thankfully a list so it may be slightly more inefficient but it catches those instances.

2024-07-02 16:36 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/assistants.py
> +        ids_len = len(ids) if ids is not None else 0
Yeah, you're right. Maybe `ids = request.tool_resources.file_search.vector_store_ids or []`, but its not a big deal. You can dismiss this if you want.

2024-07-02 16:59 UTC, CollectiveUnicorn commented on src/leapfrogai_api/routers/openai/assistants.py
> +        vector_stores_len = len(list(vector_stores)) if vector_stores is not None else 0
Probably about the same size wise when accounting for the new try/except block. But I am mostly concerned about readability, so what about swapping this for `0 if vector_stores is None else len(list(vector_stores))` at least so that its affirmative

2024-07-02 18:39 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
I originally pulled out all of the common checks between create and modify and put them as a helper function in `backend/helpers.py`, but that caused a lot of circular import errors so I ended up pulling it out and left it in `assistants.py`. I don't love having a helper function there but aside from making a new utils or helpers file it's currently clearly annotated as a helper function that only applies to `create_assistant` and `modify_assistant`. What do you think?

2024-07-02 19:37 UTC, jalling97 commented on src/leapfrogai_api/backend/rag/index.py
> +            raise exc
Combined :+1:

2024-07-02 19:37 UTC, jalling97 commented on src/leapfrogai_api/backend/rag/index.py
> +            raise exc
Combined :+1:

2024-07-02 19:39 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +        ids_len = len(ids) if ids is not None else 0
I ended up combining the two approaches:
```
ids = request.tool_resources.file_search.vector_store_ids or []
vector_stores = (
    getattr(request.tool_resources.file_search, "vector_stores", []) or []
)
```
Since `vector_store_ids` will always exist but `vector_stores` may not.

2024-07-02 19:40 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +        vector_stores_len = len(list(vector_stores)) if vector_stores is not None else 0
As stated above, I ended up combining the two approaches to testing for `None` types so now I just do a basic length check
```
ids_len = len(ids)
vector_stores_len = len(list(vector_stores))
```

2024-07-08 18:56 UTC, YrrepNoj requested changes

2024-07-08 18:56 UTC, YrrepNoj commented on src/leapfrogai_api/backend/rag/index.py
> +            vector_store.file_counts.in_progress += 1
Does the `in_progress` counter ever get decremented? It seems like this will be a forever growing count.

2024-07-08 18:56 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +    if not validate_tool_resources(request.tool_resources):
```suggestion
    if request.tool_resources and not validate_tool_resources(request.tool_resources):
```

2024-07-08 18:56 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +async def _assistant_request_checks(
I like the spirit of this helper function and think it is in the right direction. I would suggest splitting the logic in this function up more to make it easier to read. It might be worthwhile to put the sections under the `elif vector_store_len == 1` and `elif ids_len == 1` into their own sub-functions.

2024-07-08 18:56 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +    """Performs common checks that occur in both create and modify requests"""
I love the addition of the doc string. This is a pattern we should be doing more often.

I want to challenge this docstring a little though. After reading this docstring (and function name), I expect this function to ONLY perform checks and return a bool/status. I wouldn't expect this function to be modifying the input and returning it back to the caller.

We should make the docstring (and maybe even the function name) a little more clear that this is happening.

2024-07-08 18:56 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/assistants.py
> +            request.tool_resources.file_search.vector_stores = (
I am assuming this is purposeful because of the `with suppress()` in the line above, but are we sure we don't want to be modifying `file_search.vector_store_ids`?

2024-07-08 19:15 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +            request.tool_resources.file_search.vector_stores = (
Good question. So in the event that the request has a `file_search.vector_stores` field, we create a new vector store and link that id to the request instead. This happens on [line 273](https://github.com/defenseunicorns/leapfrogai/blob/b42646f14484d59b330b5657df0d934758543cfd/src/leapfrogai_api/routers/openai/assistants.py#L273) at the moment. So we either start with `vector_stores` and end with `vector_store_ids` or start with `vector_store_ids` and end with the same. The only reason this line to set `vector_stores` to None is outside everything is to ensure nothing sneaks through.

Although I could probably handle that by removing the `vector_stores` within the same portion of code as creating the vector store and just making an `assertion` at the end. Whichever is preferred.

2024-07-09 15:15 UTC, jalling97 commented on src/leapfrogai_api/backend/rag/index.py
> +            vector_store.file_counts.in_progress += 1
After checking with @gphorvath , no, it currently has the initial pass then remains unchanged for the life of the vector store, which is a problem. Would it make sense to open another issue for this bug? Or do you just want me to include a solution in this PR?

2024-07-09 16:27 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +    if not validate_tool_resources(request.tool_resources):
Changed :+1:

2024-07-09 16:28 UTC, jalling97 commented on src/leapfrogai_api/routers/openai/assistants.py
> +    """Performs common checks that occur in both create and modify requests"""
Updated :+1:

2024-07-09 16:33 UTC, jalling97 commented on src/leapfrogai_api/backend/rag/index.py
> +            vector_store.file_counts.in_progress += 1
This will be addressed in the following issue: https://github.com/defenseunicorns/leapfrogai/issues/743

2024-07-09 17:31 UTC, YrrepNoj approved these changes
LGTM. Thanks for the consistent updates.

2024-07-09 19:58 UTC, CollectiveUnicorn approved these changes

2024-07-10 20:57 UTC, YrrepNoj approved these changes

2024-07-10 22:59 UTC, merged