feat(api): long lived api keys
defenseunicorns/leapfrogai pull request #658
Opened 2024-06-18 21:34 UTC by gphorvath

2024-07-02 22:48 UTC, gphorvath commented on packages/api/supabase/migrations/20240618163044_api_keys.sql
> +    api_key text not null,
Currently this is being hashed in python code and stored/accessed to Supabase in the form `lfai_hashed-key_checksum`

2024-07-09 14:57 UTC, gphorvath commented on packages/api/zarf.yaml
> -  - name: EXPOSE_OPENAPI_SCHEMA
reverted

2024-07-09 15:06 UTC, justinthelaw reviewed
Some initial comments for discussion! Great work so far - this will be super helpful for delivery and all customers in general.

2024-07-09 15:22 UTC, gphorvath commented on src/leapfrogai_api/pyproject.toml
> +    "supabase >= 2.5.1",
I think this particular entry is just the latest version of the supabase library. The other two are the result of using this versus the previous less supported library.

2024-07-09 15:56 UTC, CollectiveUnicorn requested changes

2024-07-09 15:56 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/security/api_key.py
> +    one_way_hash = hashlib.sha256(unique_key.encode()).hexdigest()
If this is for security purposes, I would also toss [pgcrypto](https://www.postgresql.org/docs/current/pgcrypto.html) in the running there as well.

Though if its not for security purposes then I think its unnecessary to change the algorithm any encoding will do if it gets the job done.

2024-07-09 15:57 UTC, justinthelaw commented on src/leapfrogai_api/backend/security/api_key.py
> +    one_way_hash = hashlib.sha256(unique_key.encode()).hexdigest()
Yeah, it was mainly for security best practice. It just depends on how secure we want these API keys to be!

You are right though - if we are only looking for functionality, everything here works.

2024-07-09 16:09 UTC, gphorvath commented on src/leapfrogai_api/backend/security/api_key.py
> +    one_way_hash = hashlib.sha256(unique_key.encode()).hexdigest()
Yeah, definitely need security here. I'll look at these options

2024-07-09 19:48 UTC, gphorvath commented on src/leapfrogai_api/backend/security/api_key.py
> +    prefix, key, checksum = (
If it's just a preference thing, I might leave it. JWT's split on `.` which is nice for efficiently differentiating between a JWT and API Key before making a more expensive call.

2024-07-09 19:48 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/vector_stores.py
> +security = HTTPBearer()
nope

2024-07-09 19:49 UTC, gphorvath commented on src/leapfrogai_api/backend/security/api_key.py
> +    one_way_hash = hashlib.sha256(unique_key.encode()).hexdigest()
Think I'm going with pgcrypto here. I will update when I finish the commit.

2024-07-09 19:50 UTC, gphorvath commented on src/leapfrogai_api/backend/security/api_key.py
> +    Should be in the form: `{prefix}_{unique_key}_{checksum}`
If we do this on the database side (see pgcrypto comment) do you think the created_at date is sufficient for this?

2024-07-09 21:45 UTC, justinthelaw commented on src/leapfrogai_api/backend/security/api_key.py
> +    Should be in the form: `{prefix}_{unique_key}_{checksum}`
Yeah, that would definitely work! In the future, we can just use the created_on date to determine key version in case we need to be backwards compatible.

2024-07-11 00:53 UTC, gphorvath commented on src/leapfrogai_api/backend/security/api_key.py
> +    one_way_hash = hashlib.sha256(unique_key.encode()).hexdigest()
moved one way hashing to db side using pgcrypto!

2024-07-11 01:47 UTC, gphorvath commented on src/leapfrogai_api/backend/security/api_key.py
> +    return hashlib.sha256(unique_key.encode()).hexdigest()[:CHECKSUM_LENGTH] == checksum
done

2024-07-11 02:47 UTC, gphorvath commented on tests/integration/api/test_auth.py
> +    assert "api_key" in create_api_key.json(), "Create should return an API key."
good call, added a validate check here

2024-07-11 02:48 UTC, gphorvath commented on src/leapfrogai_api/backend/security/api_key.py
added constants for this

2024-07-11 15:35 UTC, justinthelaw approved these changes
Thanks for making all those changes, and in super-nice, granular commits too so that we can track the changes!

2024-07-11 15:37 UTC, YrrepNoj submitted a review, later dismissed
I mostly only have comments on QoL or pythonic things. All of them can be auto-resolved at your discretion.

2024-07-11 15:37 UTC, YrrepNoj commented on src/leapfrogai_api/backend/security/api_key.py
> +def generate_new_api_key() -> str:
QoL: Feel free to ignore this comment.


What are your thoughts on turning this into the default `__init__(self)` constructor function within the APIKey class? I think that would make this a little more _pythonic_.

2024-07-11 15:37 UTC, YrrepNoj commented on src/leapfrogai_api/backend/security/api_key.py
> +class APIKey(BaseModel):
QoL: Feel free to ignore this comment.

It might be useful to overload the `__repr__()` method to print the APIKey in the `f"{KEY_PREFIX}_{unique_key}_{checksum}"` format.

2024-07-11 15:37 UTC, YrrepNoj commented on src/leapfrogai_api/backend/security/api_key.py
> +def parse_api_key(api_key: str) -> APIKey:
QoL: Feel free to ignore this comment.

If we take the suggestion above for having an `__init__()` constructor for the APIKey class, we can make an optional argument for a string and move this logic into that constructor as well.

2024-07-11 15:37 UTC, YrrepNoj commented on src/leapfrogai_api/data/crud_api_key.py
> +        params = {
Should/could this set of params be a declared class instead of a generic dictionary?

2024-07-11 15:37 UTC, YrrepNoj commented on src/leapfrogai_api/routers/supabase_session.py
> +async def _validate_jwt_authorization(session, authorization: str) -> bool:
Can we typehint `session` and try to handle any red squiggles from optional 'None' returns?

2024-07-11 19:57 UTC, gphorvath commented on src/leapfrogai_api/backend/security/api_key.py
> +def generate_new_api_key() -> str:
Now with more python

2024-07-11 19:57 UTC, gphorvath commented on src/leapfrogai_api/backend/security/api_key.py
> +class APIKey(BaseModel):
Added

2024-07-11 19:58 UTC, gphorvath commented on src/leapfrogai_api/backend/security/api_key.py
> +def parse_api_key(api_key: str) -> APIKey:
made a class method called `generate` which returns the API key model.

2024-07-11 20:12 UTC, gphorvath commented on src/leapfrogai_api/routers/supabase_session.py
> +async def _validate_jwt_authorization(session, authorization: str) -> bool:
I think this is resolved now, feel free to unresolve if you still see an issue.

2024-07-11 20:29 UTC, gphorvath commented on src/leapfrogai_api/data/crud_api_key.py
> +        params = {
done.

2024-07-11 21:50 UTC, YrrepNoj approved these changes
LGTM. Thanks for the updates.

2024-07-11 22:09 UTC, gphorvath commented on src/leapfrogai_api/data/crud_api_key.py
> +    name: str | None = Field(
In this particular case I'm leave the optional parameters because there are cases I need to differentiate between blank and not set for purposes of updating.

2024-07-11 22:14 UTC, CollectiveUnicorn approved these changes

2024-07-11 22:15 UTC, CollectiveUnicorn approved these changes

2024-07-11 23:13 UTC, merged