Fill in package READMEs and update docs
defenseunicorns/leapfrogai pull request #660
Opened 2024-06-20 15:13 UTC by jalling97

- Moves local dev instructions out from the root `README.md` and into each packages' respective `README.md`

2024-06-21 18:01 UTC, CollectiveUnicorn requested changes

2024-06-21 18:56 UTC, jalling97 commented on packages/text-embeddings/README.md
> +uds deploy k3d-core-slim-dev:0.22.2      # if no cluster exists already
Yeah the fewer the places that version number gets referenced the easier it'll be when we have to keep changing it.

2024-07-01 17:03 UTC, justinthelaw approved these changes
Great clean-up!

2024-07-01 20:09 UTC, jalling97 commented on packages/text-embeddings/README.md
> +uds deploy k3d-core-slim-dev:0.22.2      # if no cluster exists already
I ended up linking all the references to the cluster deployment back to the root README

2024-07-01 20:51 UTC, CollectiveUnicorn approved these changes
Looks good!

2024-07-02 13:53 UTC, merged