(feat) Unit Testing for CRUDBase
defenseunicorns/leapfrogai pull request #677
Opened 2024-06-20 19:58 UTC by alekst23

Creates mocks for db session
Creates unit testing for CRUDBase features

Current Errors:
Most sad paths fail because we do not properly process empty return types from the database

2024-06-21 17:24 UTC, jalling97 commented on make-tests.mk
> +test-api-integration:
What's the benefit of adding another makefile as opposed to putting these make targets in the root Makefile?

2024-06-21 17:26 UTC, jalling97 commented on tests/conftest.py
> +
Don't pytest fixtures normally live in `conftest.py` as well?

2024-06-24 01:50 UTC, gphorvath requested changes

2024-06-24 01:50 UTC, gphorvath commented on tests/conftest.py
I believe this conftest.py is causing the Supabase test to fail in the e2e pipeline. If possible we should probably try to limit the scope of mocks to the unit test directory to avoid mocking something that is used in an e2e or integration test.

https://github.com/defenseunicorns/leapfrogai/actions/runs/9617886637/job/26530618578#step:9:113

2024-06-24 01:50 UTC, gphorvath commented on make-tests.mk
> +test-api-integration:
I'm personally a fan of starting to break out the Makefile in this way to avoid a massive Makefile. Although it might be nice if we can move the includes into a directory to avoid cluttering up the root directory.

2024-06-24 01:50 UTC, gphorvath commented on pyproject.toml
I'm also seeing pytest-asyncio as a requirement for the unit tests.

2024-06-24 01:50 UTC, gphorvath commented on make-tests.mk
> +	pytest tests/integration/api
More a point of preference, but I've been starting to add `-vv -s` to get more verbosity and detail when things fail.

2024-06-24 01:50 UTC, gphorvath commented on src/leapfrogai_api/data/crud_base.py
> +            return None
This seems to be causing errors. It looks like we can't access the `data` element by using `[0]` index. I found this works, but maybe you can find a better way? This is similarly an issue in list and delete endpoints. Might be worth running the integration tests periodically to make sure nothing is breaking.

```
        result, _ = await self.db.table(self.table_name).insert(dict_).execute()

        try:
            return self.model(**result[1][0])
        except Exception:
            return None
```

2024-07-01 15:41 UTC, alekst23 commented on make-tests.mk
> +test-api-integration:
@jalling97 The benefit is that we have better organized code instead of a monolithic Makefile.

@gphorvath I like the idea of organizing them by directory. There are two options to do this:
1) One directory for all Makefile includes, like `common` in project root.
2) Keep Makefiles closer to their target, in the relevant component directory.

I think option (2) may be better for Makefiles specific to a module or function, like Testing, Supabase, etc.

2024-07-01 15:51 UTC, alekst23 commented on pyproject.toml
Added to `project.toml`

2024-07-01 15:53 UTC, alekst23 commented on src/leapfrogai_api/data/crud_base.py
> +            return None
That's strange. Is there error somewhere up stream in integration testing or elsewhere?

My unit tests are running OK for this. Perhaps I am not mocking the db response properly.

2024-07-01 16:33 UTC, alekst23 commented on tests/conftest.py
> +
You can have multiple conftest.py files, and they will be included for all tests in that directory and lower. These files usually have the relevant fixtures defined therein.

So this is the root conftest for all tests. The fixtures we define elsewhere in this PR are specifically for unit testing, and I did not want to them to be loaded for all tests like integration and e2e.

2024-07-01 16:36 UTC, alekst23 commented on tests/conftest.py
This is an interesting problem. Our conftest file should be using environment variables where they have been defined, and using mock data where they are not.

I think the problem may be that we don't have ANON_KEY in env? It seems to be resolving this url https://supabase-kong.uds.dev/auth/v1/health but fails with 401

2024-07-01 21:25 UTC, alekst23 commented on make-tests.mk
> +test-api-integration:
I went with option (2) and moved the file to `tests/make-tests.mk`

Let me know if you feel better about a common directory for all makefiles, but this seems to make sense to me for now.

2024-07-01 21:34 UTC, alekst23 commented on src/leapfrogai_api/data/crud_base.py
> +            return None
@gphorvath I think I found the problem. It's related to `table.select` returning a list, wheres all other methods return objects. I have made the relevant fixes to mocks and unit tests, but I am having some trouble running the integration tests right now to verify.

2024-07-08 16:22 UTC, gphorvath approved these changes
Looks good to me now! Can you make sure we have an issue tracking adding these tests to a pipeline?

2024-07-08 21:16 UTC, merged