fix(api): bump max tokens to maximum for Synthia-7B to prevent chopping
defenseunicorns/leapfrogai pull request #699
Opened 2024-07-01 16:56 UTC by gphorvath

This should fix the issue with chopping in the UI when using the default model `TheBloke/Synthia-7B-v2.0-GPTQ`. Bumps the default max tokens to 4096.

2024-07-01 17:01 UTC, justinthelaw approved these changes

2024-07-01 18:17 UTC, YrrepNoj requested changes
One small callout about a bad log statement.

2024-07-01 18:17 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
>                  "max_prompt_tokens is not set or is less than 1, setting to 1024"
The log statement is now incorrect. Maybe we should make a CONST for the default value so that we can use the const in this logged string as well?

2024-07-01 19:11 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
>                  "max_prompt_tokens is not set or is less than 1, setting to 1024"
Good catch, fixed

2024-07-01 19:51 UTC, justinthelaw commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
> +DEFAULT_MAX_COMPLETION_TOKENS = 4096
Now that @YrrepNoj pointed it out, this might be best exposed as a Zarf variable. I assume this really only affects the UI, where we cannot modify or supply this variable via API. If a delivery engineer chooses to use a larger model (like at BeastCode, with Mixtral) with larger context or a specific use-case that requires more generation, then they would want to be able to change this.

2024-07-01 19:53 UTC, justinthelaw commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
> +DEFAULT_MAX_COMPLETION_TOKENS = 4096
At the same time, you can feel free to say that this goes beyond the purpose of the ticket.

2024-07-01 19:56 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
> +DEFAULT_MAX_COMPLETION_TOKENS = 4096
In theory this is only the default value and if a different value is passed in via the API it will be overridden.

2024-07-01 19:59 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
> +DEFAULT_MAX_COMPLETION_TOKENS = 4096
I think for now we can just allow it to be overridden via API and in the future we handle at the time we load a model in via the model registry. We should be creating custom configurations that are loaded with each new model.

2024-07-01 20:08 UTC, justinthelaw approved these changes

2024-07-01 21:52 UTC, CollectiveUnicorn approved these changes

2024-07-02 16:15 UTC, YrrepNoj commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
> +DEFAULT_MAX_PROMPT_TOKENS = 4096
nit; what do you think about moving this to the types file so we can reuse this in the `CompletionRequest.max_tokens` field?

2024-07-02 16:16 UTC, YrrepNoj approved these changes
One small nit; approving and leaving it up to you if you want to resolve or not. 🫶

2024-07-02 16:34 UTC, gphorvath commented on src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
> +DEFAULT_MAX_PROMPT_TOKENS = 4096
I took your suggestion!

2024-07-02 17:01 UTC, YrrepNoj approved these changes

2024-07-02 17:33 UTC, merged