Raise exception on CRUD base fails
defenseunicorns/leapfrogai pull request #748
Opened 2024-07-09 22:31 UTC by alekst23

CRUD operations will now raise exceptions instead of catching them and returning None.
Delete function will only return True/False.

2024-07-10 15:31 UTC, gphorvath requested changes

2024-07-10 15:31 UTC, gphorvath commented on src/leapfrogai_api/data/crud_base.py
@alekst23 now that we are reraising exceptions, we should make sure to catch the index out of range error inside of crud_base and return none or false respectively.

![image](https://github.com/defenseunicorns/leapfrogai/assets/17520730/bb3d6112-2cb2-44c0-97b0-1e08dea329cb)

2024-07-11 16:04 UTC, YrrepNoj approved these changes

2024-07-11 21:33 UTC, alekst23 commented on src/leapfrogai_api/data/crud_base.py
Good idea. This is now implemented.

2024-07-12 16:20 UTC, YrrepNoj approved these changes
LGTM (after conflict is resolved).

2024-07-12 19:58 UTC, gphorvath approved these changes

2024-07-12 20:21 UTC, merged