chore: Proof of concept: Remove model weights from container images
defenseunicorns/leapfrogai pull request #786
Opened 2024-07-16 21:21 UTC by YrrepNoj

This PR is a proof of concept to how we can utilize [Zarf Data Injections](https://docs.zarf.dev/ref/components/#data-injections) to push model weights to a [PVC](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) instead of directly building them into the Docker images themselves.

Pros:
 - Much smaller image size
   - `4.58 GB` -> `0.21 GB`

 - Faster build & deploy time
     - Fresh Build Time: `7m 39s` -> `1m 40s`
     - Cached Build Time: `2m 20s` -> `1m 1s`
     - Deploy Time: `2m - 8m` -> `2m 29s`.     # NOTE: I could not get consistent deploy times with our old approach

Cons:
- Adds a PVC to our deployment. Pretty reasonable, but is an added thing that delivery engineers would have to manage (for the storage class of the PVC)

2024-07-16 21:24 UTC, YrrepNoj commented on packages/llama-cpp-python/zarf.yaml
> +          - cmd: python scripts/model_download.py
I am not completely in love with using a python script here. 

I like the concept of the Zarf package regulating the existence of the model weights (verses the package just assuming the model has already been downloaded and exists in a certain location) but I don't know if a Python script is the best way to do this. This adds a dependency of python at the package creation time.


Any thoughts or spears? Anyone particularly like this approach?

2024-07-16 21:28 UTC, YrrepNoj commented on packages/llama-cpp-python/zarf.yaml
> +          - cmd: python scripts/model_download.py
I kept it as python for now just to reuse what we currently had for the model_download in the Docker build step, but maybe just making this a bash script makes more sense in the long term.

2024-07-16 21:31 UTC, justinthelaw commented on packages/llama-cpp-python/zarf.yaml
> +          - cmd: python scripts/model_download.py
The python script was an artifact of wanting to use `hf_transfer`, the rust plugin for maxing out download bandwidth. `hf_transfer` usually only works for the `hugging_face[cli]` version before latest, so that may be why the model download speed differences aren't apparent. Alos, Synthia-7b is a small sized model, relative to the Mixtral variants we were having trouble downloading in a timely manner (before the HF mirror serving the model download would hang on us).

I don't mind reverting this back to a `wget` or `curl` though, if we want to minimize dependencies to only UDS CLI..

2024-07-22 16:40 UTC, CollectiveUnicorn requested changes

2024-07-22 16:40 UTC, CollectiveUnicorn commented on packages/llama-cpp-python/chart/templates/pv.yaml
> +    name: lfai-llama-pv-claim
Are we going to have separate PVs for llama-cpp and vllm?

2024-07-22 16:41 UTC, YrrepNoj commented on packages/llama-cpp-python/chart/templates/pv.yaml
> +    name: lfai-llama-pv-claim
I think yes

2024-07-22 18:10 UTC, CollectiveUnicorn approved these changes

2024-07-31 15:42 UTC, justinthelaw commented
The Dockerfiles still contain a lot of extra ENVs and ARGs. I recommend removal and an update of the README to reflect the changes made here.

2024-07-31 15:55 UTC, YrrepNoj commented on packages/vllm/vllm-values.yaml
> +  storageClass: "local-path"
@justinthelaw Right now these values are not exposed as a Zarf variable. I set the defaults to what I think should be reasonable for a single node cluster.

From your experience, do you think these would make sense to expose as a Zarf Variable or do you think having future deployers rely on UDS Overrides is good for this configuration?

2024-07-31 15:57 UTC, justinthelaw commented on packages/vllm/vllm-values.yaml
> +  storageClass: "local-path"
There are situations where we have had to create 1 or more custom backends, since we usually do not try to deploy the default model that we publish to GHCR. Exposing these at a Zarf package level allows us more flexibility, while still letting us access create or deploy-time values via UDS overrides.

My opinion is to expose these as Zarf variables to accommodate changes at a package level, as we may need 1 or more changes and models in a given cluster.

2024-07-31 22:57 UTC, justinthelaw approved these changes

2024-08-01 17:28 UTC, merged