feat(backend): add k3d gpu image builder
defenseunicorns/leapfrogai pull request #797
Opened 2024-07-18 20:19 UTC by gphorvath

2024-07-18 22:17 UTC, justinthelaw commented
Do we want to add CI to publish this image or workflow dispatch? Or will this be built locally and used locally (dev) only?

2024-07-19 13:19 UTC, justinthelaw requested changes

2024-07-19 13:26 UTC, justinthelaw commented
Not a mandatory requirement, but we could make this a YOLO Zarf package that uses upstream uds-k3d as one of its sub-component steps. That might make centralized version control easier, as mentioned in my previous review comments, while also simplifying the Make commands into an easy Zarf deploy.

2024-07-19 14:06 UTC, gphorvath commented on .github/workflows/build-images.yaml
> +  pull_request:
This is just here for testing since you can't workflow_dispatch a workflow that isn't on main. Also I didn't finish with this commit because of the GitHub pipelines were down last night, so it might be a little low quality right now

2024-07-19 14:18 UTC, gphorvath commented on packages/k3d-gpu/Makefile
> +REGISTRY_PORT := 5000
fixed

2024-07-19 15:38 UTC, gphorvath commented on .github/workflows/build-images.yaml
> +            --build-arg K3S_TAG=v1.28.8-k3s1 \
done

2024-07-19 15:39 UTC, gphorvath commented on packages/k3d-gpu/Dockerfile
> +FROM nvidia/cuda:$CUDA_TAG
done

2024-07-19 15:39 UTC, gphorvath commented on packages/k3d-gpu/Makefile
> +K3S_TAG := v1.28.8-k3s1
done

2024-07-22 19:45 UTC, CollectiveUnicorn approved these changes

2024-07-23 14:30 UTC, justinthelaw submitted a review, later dismissed

2024-07-23 16:29 UTC, YrrepNoj approved these changes

2024-07-23 17:26 UTC, merged