feat(ui): Flowbite header and sidebar
defenseunicorns/leapfrogai pull request #813
Opened 2024-07-22 18:08 UTC by andrewrisse

First PR for converting to Flowbite. Adds the header and sidebar.

2024-07-22 19:34 UTC, CollectiveUnicorn requested changes

2024-07-22 19:34 UTC, CollectiveUnicorn commented on src/leapfrogai_ui/src/lib/components/LFHeader.test.ts
>      // We cannot test by visibility because carbon components svelte does not give us a way to grab the panel
Is this comment still relevant given the removal of the `bx--header__action--active` code?

2024-07-23 16:10 UTC, BillyFigueroa commented on src/leapfrogai_ui/src/lib/components/AssistantAvatar.svelte
> +    background-color: #393939;
I would try to create css variables for some of these repeated reused values

2024-07-23 16:10 UTC, BillyFigueroa commented on src/leapfrogai_ui/src/lib/components/AssistantAvatar.svelte
> +    border: 2px solid #ffb3b8;
I would try to create css variables for some of these repeated reused values

2024-07-23 16:12 UTC, BillyFigueroa commented on src/leapfrogai_ui/src/lib/components/AssistantForm.svelte
> +      font-size: 2rem;
might help to actually create mixins or some scss related shortcut to get the same results

2024-07-23 16:15 UTC, BillyFigueroa commented
It looks like a good amount of the changes were un-doing a lot of the scss variables provided by carbon. I would likely recommend created some sort of js file you can export those types of values or doing something in scss/ postcss where you are creating your own utility classes, maybe even with the same name, to replace with and remove the problem of repetition as well as when you might need to make a chance in the future, you change it in one place

2024-07-23 18:40 UTC, andrewrisse commented on src/leapfrogai_ui/src/lib/components/LFHeader.test.ts
>      // We cannot test by visibility because carbon components svelte does not give us a way to grab the panel
it sure isn't

2024-07-23 18:43 UTC, andrewrisse commented on src/leapfrogai_ui/src/lib/components/AssistantAvatar.svelte
> +    gap: 0.5rem;
This component will be moved over to Flowbite soon and will be using tailwind css. My understanding is that variables and re-usable styles are less of a thing, even frowned upon sometimes, with Tailwind. I've been using some Tailwind utilities though to have some re-usable stuff, but am limiting those use cases.

Do you have an example of using variables with tailwind? I'm curious if we can find a good pattern for that.

2024-07-23 19:48 UTC, BillyFigueroa commented on src/leapfrogai_ui/src/lib/components/AssistantAvatar.svelte
> +    gap: 0.5rem;
> This component will be moved over to Flowbite soon and will be using tailwind css. My understanding is that variables and re-usable styles are less of a thing, even frowned upon sometimes, with Tailwind. I've been using some Tailwind utilities though to have some re-usable stuff, but am limiting those use cases.
> 
> Do you have an example of using variables with tailwind? I'm curious if we can find a good pattern for that.

Well, tailwind has a bunch of utility classes they have that are re-used. They are not using the actual hex codes for example in their color classes. You can create a utility class for spacing and color I believe. Might need to extend the tailwind config object and include them there

2024-07-23 20:01 UTC, andrewrisse commented on src/leapfrogai_ui/src/lib/components/AssistantAvatar.svelte
> +    background-color: #393939;
expect this to change and likely go away when this component is moved to flowbite, for now this change is to remove the carbon sass pre-processing (caused a lot of performance issues)

2024-07-23 20:03 UTC, andrewrisse commented on src/leapfrogai_ui/src/lib/components/AssistantAvatar.svelte
> +    border: 2px solid #ffb3b8;
will address when this component is moved to flowbite, will change significantly

2024-07-23 20:08 UTC, andrewrisse commented on src/leapfrogai_ui/src/lib/components/AssistantForm.svelte
> +      font-size: 2rem;
will be using flowbite typography when this changes to flowbite

2024-07-23 20:09 UTC, andrewrisse commented
> It looks like a good amount of the changes were un-doing a lot of the scss variables provided by carbon. I would likely recommend created some sort of js file you can export those types of values or doing something in scss/ postcss where you are creating your own utility classes, maybe even with the same name, to replace with and remove the problem of repetition as well as when you might need to make a chance in the future, you change it in one place

Very valid point, but those changes are temporary (like changing tomorrow) as we move to flowbite. They just let the app compile while we remove the carbon sass precompile stuff.

2024-07-23 21:36 UTC, BillyFigueroa commented
> > It looks like a good amount of the changes were un-doing a lot of the scss variables provided by carbon. I would likely recommend created some sort of js file you can export those types of values or doing something in scss/ postcss where you are creating your own utility classes, maybe even with the same name, to replace with and remove the problem of repetition as well as when you might need to make a chance in the future, you change it in one place
> 
> 
> 
> Very valid point, but those changes are temporary (like changing tomorrow) as we move to flowbite. They just let the app compile while we remove the carbon sass precompile stuff. 

Copy 🙌🏽

2024-07-24 17:15 UTC, CollectiveUnicorn approved these changes

2024-07-25 22:34 UTC, merged