chore: make python test dependencies optional
defenseunicorns/leapfrogai pull request #815
Opened 2024-07-22 18:34 UTC by CollectiveUnicorn

- Adds an optional `[dev]` dependency flag to the root `pyproject.toml` for test dependencies

2024-07-22 18:41 UTC, gphorvath submitted a review, later dismissed

2024-07-22 19:06 UTC, CollectiveUnicorn commented
This PR affects and is affected by: https://github.com/defenseunicorns/leapfrogai/pull/808 - will wait on it to go through before updating this PR

2024-07-23 13:50 UTC, jalling97 approved these changes

2024-07-23 14:03 UTC, justinthelaw submitted a review, later dismissed

2024-07-24 17:19 UTC, YrrepNoj requested changes

2024-07-24 17:19 UTC, YrrepNoj commented on src/leapfrogai_api/Makefile
> +	python -m pip install ../../[dev]
As written, this doesn't work with all shell types.
```suggestion
	python -m pip install "../../.[dev]"
```

2024-07-24 17:28 UTC, CollectiveUnicorn commented on src/leapfrogai_api/Makefile
> +	python -m pip install ../../[dev]
Good catch

2024-07-24 17:34 UTC, YrrepNoj submitted a review, later dismissed

2024-07-24 18:50 UTC, gphorvath commented
> This PR affects and is affected by: #808 - will wait on it to go through before updating this PR

It looks like #808 is going to need more work, so maybe retarget to main so it can be merged @CollectiveUnicorn?

2024-07-24 18:54 UTC, CollectiveUnicorn commented
Right now its targeted at [port-load-tests](https://github.com/defenseunicorns/leapfrogai/tree/port-load-tests) since there's load test related dependencies included and readme changes.

2024-07-29 01:59 UTC, gphorvath approved these changes

2024-07-29 17:35 UTC, YrrepNoj approved these changes

2024-07-29 17:54 UTC, merged