chore(api): updating api key endpoint names
defenseunicorns/leapfrogai pull request #817
Opened 2024-07-22 21:56 UTC by gphorvath

2024-07-23 19:13 UTC, andrewrisse commented on src/leapfrogai_api/routers/leapfrogai/auth.py
> +@router.post("/api-keys/{api_key_id}")
recommend change to PATCH

2024-07-24 14:26 UTC, gphorvath commented on src/leapfrogai_api/routers/leapfrogai/auth.py
> +@router.post("/api-keys/{api_key_id}")
changed this in the API

2024-07-24 16:17 UTC, andrewrisse submitted a review, later dismissed

2024-07-24 18:58 UTC, jalling97 commented
Since we haven't pulled the API integration tests into CI yet, are these changes passing those tests?

2024-07-24 19:09 UTC, CollectiveUnicorn requested changes

2024-07-24 19:09 UTC, CollectiveUnicorn commented on src/leapfrogai_api/Makefile
> +	@cd ${MAKEFILE_DIR} && python -m pytest ../../tests/integration/api/test_auth.py -vv -s
Is limiting the scope of these tests intentional?

2024-07-24 19:09 UTC, CollectiveUnicorn commented on .github/workflows/e2e.yaml
> +#          run: |
Are these not working?

2024-07-24 19:11 UTC, jalling97 commented on .github/workflows/e2e.yaml
> +#          run: |
At the moment yes. @andrewrisse and I are looking into it but it appears to be a playwright issue, not that the UI or backend is broken at the moment.

2024-07-24 19:11 UTC, gphorvath commented on src/leapfrogai_api/Makefile
> +	@cd ${MAKEFILE_DIR} && python -m pytest ../../tests/integration/api/test_auth.py -vv -s
no... good catch!

2024-07-24 19:13 UTC, gphorvath commented on src/leapfrogai_api/Makefile
> +	@cd ${MAKEFILE_DIR} && python -m pytest ../../tests/integration/api/test_auth.py -vv -s
fixed!

2024-07-24 19:20 UTC, CollectiveUnicorn approved these changes

2024-07-24 20:11 UTC, merged