(ADR) RAG Evaluations Framework
defenseunicorns/leapfrogai pull request #842
Opened 2024-07-26 19:22 UTC by jalling97

- Adds the ADR for the overal RAG Evaluations Framework
- This will be added to for each component of the [RAG Evals MVP Epic](https://github.com/defenseunicorns/leapfrogai/issues/723) and closed when all pieces are done and all decisions have been documented in the ADR.

2024-09-10 00:37 UTC, barronstone commented on adr/0007-rag-eval-framework.md
> +### Models to Evaluate
Please populate with your initial list of 2-3 models to eval for the MVP. Also indicate that short list represents the initial MVP.

2024-09-10 00:37 UTC, barronstone commented on adr/0007-rag-eval-framework.md
> +  These datasets were created because it filled a gap in the openly available datasets that could have been used. For example, in QA datasets, there did not exist any dataset that had all **4** compo
Explain why we picked the reference documents we used as sources for this data set. It was a mix of technical documentation & DoD policy docs to capture the type of data we generally expect our mission users will be working with.

2024-09-10 00:37 UTC, barronstone commented on adr/0007-rag-eval-framework.md
> +LeapfrogAI uses RAG to provide context-aware responses to users who have specific data they need to reference. In order to make sure RAG is operating at the levels we need it to, we need to get measu
In addition to evaluating and improving our "default" RAG implementation in LeapfrogAI, developing a standard approach to evals will help make delivery folks more efficient at evaluating custom RAG implementations they may build on and around the core LeapfrogAI.

2024-09-10 00:37 UTC, barronstone commented on adr/0007-rag-eval-framework.md
> +  In order to reach an MVP product, a single LLM judge will be utilized for the evaluations that require it. This will be the first stage so that the evaluation framework can begin recieving results.
nit: typo "recieving"

2024-10-01 14:12 UTC, justinthelaw reviewed
This looks excellent so far! Some minor comments and nits.

2024-10-01 14:12 UTC, justinthelaw commented on adr/0007-rag-eval-framework.md
> +  Non-llm-enabled evaluations:
```suggestion
  Non-LLM-enabled evaluations:
```

2024-10-01 14:12 UTC, justinthelaw commented on adr/0007-rag-eval-framework.md
> +  The three models that will initially be evaluated are going to be:
It may be good to provide a small sections about why we chose the quantization and sizes of the models here. For example, reasons like consistency with # of active params or vRAM limitations,  so that it doesn't seem like we selected 4-bit quantization for these model sizes arbitrarily.

2024-10-01 14:12 UTC, justinthelaw commented on adr/0007-rag-eval-framework.md
> +  Claude 3.5 Sonnet was chosen to be used as the first judge due to it's high levels of [performance](https://artificialanalysis.ai/models/claude-35-sonnet), which is crucial when utilizing an LLM ju
Can you provide a little more context on what performance here? Maybe talk about its reasoning scores, like MMLU or GPQA? Might also be good to mention its large context window for digesting and analyzing the in/output for the evaluated models.

2024-10-01 14:12 UTC, justinthelaw commented on adr/0007-rag-eval-framework.md
> +  - These evaluation results will be stored as artifacts in Github so that peformance can be tracked over time across version releases.
```suggestion
  - These evaluation results will be stored as artifacts in GitHub so that performance can be tracked over time across version releases.
```

2024-10-01 17:37 UTC, jalling97 commented on adr/0007-rag-eval-framework.md
> +  The three models that will initially be evaluated are going to be:
Made some updates, let me know what you think!

2024-10-01 17:37 UTC, jalling97 commented on adr/0007-rag-eval-framework.md
> +  Claude 3.5 Sonnet was chosen to be used as the first judge due to it's high levels of [performance](https://artificialanalysis.ai/models/claude-35-sonnet), which is crucial when utilizing an LLM ju
Made some updates, let me know what you think!

2024-10-03 13:37 UTC, justinthelaw approved these changes
I love it!

2024-10-03 15:50 UTC, gphorvath submitted a review, later dismissed

2024-10-03 17:00 UTC, CollectiveUnicorn requested changes

2024-10-03 17:02 UTC, CollectiveUnicorn requested changes

2024-10-03 17:02 UTC, CollectiveUnicorn commented on adr/0007-rag-eval-framework.md
> +  Non-RAG LLM benchmarks:
Given that this is presumably an ADR about RAG these seem a little out of place.

2024-10-03 17:10 UTC, CollectiveUnicorn commented on adr/0007-rag-eval-framework.md
> +  - HumanEval: Evaluates an LLM's code generation abilities (not RAG-enabled, but it useful as an established baseline to compare against)
Same as above, given that this is presumably an ADR about RAG these seem a little out of place.

2024-10-03 17:10 UTC, CollectiveUnicorn commented on adr/0007-rag-eval-framework.md
> +  - A deployed instance of LeapfrogAI will likely always accompany UDS runtime. The evaluation results for a deployment will live in a table under its corresponding UDS runtime page.
Does this mean the specific version of Leapfrog AI that has the eval was run?

2024-10-03 19:47 UTC, jalling97 commented on adr/0007-rag-eval-framework.md
> +  - A series of irrelevant texts of varying context length that have one point of information hidden within
Knowing what we know now about the NIAH dataset when it comes to evaluating RAG systems specifically, it's not "wrong" per say but this description doesn't show the complete picture of what we actually need, which looks more like:

- A collection of documents (the haystack) where one document contains a target piece of information (the needle) hidden somewhere within
    - The documents should be of the same topic (or in other words, be semantically similar) so it's not obvious which document has the right information
    - The needle itself should also be topically related to the rest of the documents but identifiable as unique information (i.e this information should be not obvious and only exists in one location out of all the documents)

If this dataset summary makes sense, I can include it as an "advanced" version of a NIAH dataset specifically for RAG. I don't want to remove the original description because that was the assumption made when making the MVP dataset.

2024-10-03 20:05 UTC, jalling97 commented on adr/0007-rag-eval-framework.md
> +  - HumanEval: Evaluates an LLM's code generation abilities (not RAG-enabled, but it useful as an established baseline to compare against)
I've talked about this a elsewhere but should include in this rationale as well. Mostly it's important that even though these benchmarks don't focus on RAG directly, that we have a few generation-only metrics so we can better diagnose whether issues in performance are happening at which stage. Using pre-existing benchmarks give a known point of comparison and are faster to integrate than building more custom evals as well.

2024-10-03 20:09 UTC, jalling97 commented on adr/0007-rag-eval-framework.md
> +  - A deployed instance of LeapfrogAI will likely always accompany UDS runtime. The evaluation results for a deployment will live in a table under its corresponding UDS runtime page.
Yes, this means that the specific deployed instance of LeapfrogAI was evaluated. This will help with diagnosing potential performance issues in a mission hero's specific environment. This is more of a long-term goal (as mentioned in the rationale) and more than likely means running evals and generating metrics that don't require an LLM-as-judge (assuming we're in airgap we won't have access to those judges).

2024-10-03 20:09 UTC, jalling97 commented on adr/0007-rag-eval-framework.md
> +  Non-RAG LLM benchmarks:
See my other comment, but I'll include more justifications in the rationale.

2024-10-03 20:57 UTC, gregclark-defenseunicorns reviewed
Looks good to me! The only thing I want to point out is the about the model cards living in UDS runtime. That is definitely an assumption and needs validation from the UDS teams in general so maybe it is worth specifying that so it is not misunderstood.

2024-10-03 22:01 UTC, CollectiveUnicorn approved these changes

2024-10-04 15:25 UTC, justinthelaw approved these changes

2024-10-04 15:28 UTC, merged