fix(api): fix indexing files with api key auth
defenseunicorns/leapfrogai pull request #852
Opened 2024-07-29 19:40 UTC by gphorvath

2024-07-31 20:20 UTC, CollectiveUnicorn submitted a review, later dismissed

2024-07-31 20:57 UTC, justinthelaw commented
Are the llama-cpp-python changes in this PR part of getting the file indexing to work locally?

2024-07-31 20:58 UTC, justinthelaw submitted a review, later dismissed

2024-07-31 21:09 UTC, YrrepNoj commented on packages/api/supabase/migrations/20240729193626_api_keys_storage_objects.sql
> +create policy "Individuals can CRUD storage.objects via API key."
Leaving a note to myself to re-read this again tonight/tomorrow with fresh eyes to make sure I understand this. <3

2024-08-01 17:59 UTC, YrrepNoj requested changes
A couple small requests/changes.

2024-08-01 17:59 UTC, YrrepNoj commented on packages/llama-cpp-python/Makefile
> -install:
I agree with @justinthelaw. If the changes to `packages/llama-cpp-python` are not relevant to fixing the issue with the file indexing I would rather not include them in this PR. Especially because this now doesn't match the Make targets names in the other package directories.

2024-08-01 17:59 UTC, YrrepNoj commented on src/leapfrogai_api/backend/rag/leapfrogai_embeddings.py
> +        model_name: str = os.getenv("DEFAULT_EMBEDDINGS_MODEL") or "text-embeddings",
Instead of using `or` we should use the optional param in `os.getenv( ... )`

```suggestion
        model_name: str = os.getenv("DEFAULT_EMBEDDINGS_MODEL", "text-embeddings)
```

2024-08-01 18:11 UTC, YrrepNoj approved these changes

2024-08-01 20:25 UTC, justinthelaw approved these changes

2024-08-01 23:45 UTC, merged