feat(api): better annotations
defenseunicorns/leapfrogai pull request #870
Opened 2024-08-02 22:24 UTC by gphorvath

2024-08-07 19:14 UTC, alekst23 commented
The annotations were not quite working with a simplistic test file that just said "Testing", so I had to augment it a little with some text data, and added a correlated question to the test file.

Perhaps there's better data we can use for this purpose.

2024-08-08 20:19 UTC, alekst23 commented
I created a conformance test method that will evaluate the same feature in a separate call to OpenAI and LeapfrogAI:
`test_conf_chat_files.py > test_file_annotations`

This method tries to evaluate Annotations returned from an Assistant query, but will inherently also evaluate the features that build the Assistant in the process:
- Create VectorStore
- Create Thread
- Create and Poll Runs
- Create Assistant

We should set these up as separate tests on their own to isolate errors.

Presently, the OpenAI call succeeds and returns the proper type structure. 

LeapfrogAI call fails with a number of issues related to the structure of the message object in the _parameter_:
- id, missing
- content, must be list
- created_at, missing
- object, missing
- status, missing
- thread_id, missing

This fails on call to `client.beta.threads.create`

2024-08-16 15:59 UTC, alekst23 commented
I have moved conformance testing for individual components to another PR and removed the code from here.

What's left should be a more minimal test focusing on conformance of file annotations.

Some issues that were identified via testing:
- threads.runs.create_and_poll - This should only attach messages to the run that were generated by the run itself, not any previous messages. 
- OpenAI annotations format is very simplistic and looks like this: 【4:0†source】
- LeapfrogAI annotations format is this: [file-uuid]

2024-08-16 20:01 UTC, alekst23 commented
TODO: 
Reformat annotations:
`src/leapfrogai_api/backend/converters.py:57`

2024-09-23 15:24 UTC, justinthelaw reviewed
Some questions and comments for discussion!

2024-09-23 15:24 UTC, justinthelaw commented on src/leapfrogai_api/backend/converters.py
> +                    text="【4:0†source】",  # TODO: What should these numbers be? Who even knows...
Maybe we should adapt this to our own purpose, even if it is not immediately clear. Let others correct us in open source community or when an OpenAI API-compatible library does end up using this differently or correctly.

My recommendation is:
```python
text=f"【{file_number}:{file_line}†{source}】"
```

Do you think this would still pass the conformance testing? If yes, then maybe we can stuff more demarcations into this format?

2024-09-23 15:24 UTC, justinthelaw commented on tests/conformance/test_chat_files.py
> +    # assert len(messages) == 1
Why is this commented out?

2024-09-23 15:24 UTC, justinthelaw commented on tests/conformance/test_chat_files.py
> +    pattern = r"【\d+:\d+†source】"
Is this always `†source`? I know we talked about this before, and I only remember that this entire field sometimes changes based on the stage at which OpenAI is at internally on the Chat message's RAG response (as observed in the network tab), prior it actually displaying to the UI.

2024-09-23 15:58 UTC, gphorvath commented on src/leapfrogai_api/backend/converters.py
> +                    text="【4:0†source】",  # TODO: What should these numbers be? Who even knows...
I don't think we actually have enough info today to capture file_number or file_line, but we could work on that.

2024-09-23 17:55 UTC, CollectiveUnicorn requested changes

2024-09-23 17:55 UTC, CollectiveUnicorn commented on tests/Makefile
> +	source .env; PYTHONPATH=$$(pwd) pytest -vv -s tests/conformance
Why does this need to source a `.env` file?

2024-09-23 17:55 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/composer.py
> +                rag_responses = await query_service.query_rag(
Why the typing removal?

2024-09-23 18:08 UTC, gphorvath commented on tests/Makefile
> +	source .env; PYTHONPATH=$$(pwd) pytest -vv -s tests/conformance
it doesn't but envs need to be set for API keys, URL, Model, etc. Probably should add some instructions on running conformance tests

2024-09-23 18:16 UTC, gphorvath commented on src/leapfrogai_api/backend/composer.py
> +                rag_responses = await query_service.query_rag(
This is defined earlier now, so this would be redefining it

2024-09-23 21:14 UTC, gphorvath commented on tests/conformance/test_chat_files.py
> +    pattern = r"【\d+:\d+†source】"
So this one took a little fiddling. I modified our implementation to return `filename` or `source` if for whatever reason `filename` isn't saved to the metadata in the vector_content table. OpenAI however doesn't have a predictable way to determine when they will spit out `filename` versus `source`, so I let the test pass if either is received.

2024-09-23 21:15 UTC, gphorvath commented on tests/conformance/test_chat_files.py
> +    # assert len(messages) == 1
Well... it turns out it's because we fail this test. That said, should I fix it as a part of this PR or add an issue?

2024-09-23 21:17 UTC, justinthelaw commented on tests/conformance/test_chat_files.py
> +    # assert len(messages) == 1
I think this can be fixed here since the test was written here too.

2024-09-23 21:19 UTC, gphorvath commented on src/leapfrogai_api/backend/converters.py
> +                    text="【4:0†source】",  # TODO: What should these numbers be? Who even knows...
I managed to squeeze in filename.

Unfortunately, it would require a pretty substantial refactor to get file_number (not actually sure what that means) or file_line (this is hard to extract in complex file types like PDF). That said, we could get to chunk_number fairly easily if we starting saving that info in the chunk metadata.

2024-09-23 21:21 UTC, justinthelaw commented on src/leapfrogai_api/backend/converters.py
> +                    text="【4:0†source】",  # TODO: What should these numbers be? Who even knows...
Okay, maybe we can separate that into a different issue/PR then haha - I didn't mean to take you on a whirlwind, but I was just interested in how we might implement that in the future.

2024-09-23 21:32 UTC, gphorvath commented on tests/Makefile
> +	source .env; PYTHONPATH=$$(pwd) pytest -vv -s tests/conformance
I added a little documentation on conformance tests to the README.md in the test directory.

2024-09-23 21:33 UTC, gphorvath commented on tests/conformance/test_chat_files.py
> +    # assert len(messages) == 1
ahhh, this actually lives in a different test, hence why it's commented here. but it fails there too

2024-09-24 19:25 UTC, gphorvath commented on src/leapfrogai_api/backend/converters.py
> +                    text="【4:0†source】",  # TODO: What should these numbers be? Who even knows...
Issue submitted: https://github.com/defenseunicorns/leapfrogai/issues/1110

2024-09-25 00:03 UTC, CollectiveUnicorn submitted a review, later dismissed

2024-09-25 00:06 UTC, CollectiveUnicorn commented on tests/Makefile
> +	source .env; PYTHONPATH=$$(pwd) pytest -vv -s tests/conformance
This isn't a blocker to merging but do the conformance tests not use `load_dotenv` that would eliminate the need for explicitly sourcing wouldn't it? Also other tests require environment variables but AFAIK they just load them in within the Python code.

2024-09-25 12:40 UTC, jalling97 commented on src/leapfrogai_api/data/crud_vector_content.py
> +    async def get_vector(self, vector_id: str) -> Vector:
I know this wouldn't fall under conformance testing, but should we have a test in place that validates the behavior of this vector endpoint? Perhaps something that just validates the fields we expect?

2024-09-25 15:32 UTC, gphorvath commented on src/leapfrogai_api/data/crud_vector_content.py
> +    async def get_vector(self, vector_id: str) -> Vector:
Sure thing! I'll add an e2e test

2024-09-25 15:34 UTC, gphorvath commented on tests/Makefile
> +	source .env; PYTHONPATH=$$(pwd) pytest -vv -s tests/conformance
for sure. it looks like the unit tests still use load_dotenv, but they could easily just use environment variables

2024-09-29 23:30 UTC, gphorvath commented
Closing in favor of:

https://github.com/defenseunicorns/leapfrogai/pull/1165
https://github.com/defenseunicorns/leapfrogai/pull/1164

2024-09-29 23:30 UTC, closed without merging