wip wip wip: playing around with configs and names
defenseunicorns/leapfrogai pull request #896
Opened 2024-08-09 16:38 UTC by YrrepNoj

2024-08-14 22:25 UTC, justinthelaw requested changes

2024-08-14 22:25 UTC, justinthelaw commented on packages/vllm/zarf.yaml
> -              - LAI_HF_HUB_ENABLE_HF_TRANSFER=1
`LAI_HF_HUB_ENABLE_HF_TRANSFER` and `LAI_QUANTIZATION` need to be transferred over to the Zarf config and the Zarf package manifest, as AppConfig (Confz) requires it.

In the future, quantization can be removed (vLLM automatically detects and optimizes from the model files' config.yaml) and hf_transfer can just be hardcoded to always be on.

2024-08-16 16:34 UTC, YrrepNoj commented on packages/vllm/zarf.yaml
> -              - LAI_HF_HUB_ENABLE_HF_TRANSFER=1
Thanks for reminding me, I added this back.

2024-09-06 14:16 UTC, YrrepNoj commented
This is stale. Will reopen once I pick this up again.

2024-09-06 14:16 UTC, closed without merging