chore(docs): markdown linting and improved documentation
defenseunicorns/leapfrogai pull request #902
Opened 2024-08-12 19:28 UTC by justinthelaw

2024-08-15 17:14 UTC, justinthelaw commented
For seeing the preview of the docs website, and use this every time you see a ref to the docs website during your review: https://deploy-preview-902--leapfrogai-docs.netlify.app/

For viewing the Markdowns uninterrupted: https://github.com/defenseunicorns/leapfrogai/tree/711-754-579-578-571-567-332-markdown-linting-and-improved-documentation

2024-08-15 20:03 UTC, alekst23 commented on packages/vllm/README.md
> +python scripts/model_download.py
This script is actually in `src/`.
This file also does not execute due to some missing required parameters to AppConfig. But maybe that's for another PR.
```suggestion
python src/model_download.py
```

2024-08-15 20:05 UTC, alekst23 commented on packages/vllm/README.md
> +pip install 'huggingface_hub[cli,hf_transfer]'  # Used to download the model weights from huggingface
```suggestion
pip install 'huggingface_hub[cli,hf_transfer]' confz  # Used to download the model weights from huggingface
```

2024-08-15 22:48 UTC, justinthelaw commented on packages/vllm/README.md
> +pip install 'huggingface_hub[cli,hf_transfer]'  # Used to download the model weights from huggingface
Fixed by introducing the install step earlier in the instructions. Fixed makefile to also install the dev dependencies.

2024-08-15 22:48 UTC, justinthelaw commented on packages/vllm/README.md
> +python scripts/model_download.py
Fixed!

2024-08-16 14:35 UTC, andrewrisse commented on README.md
>  The LeapfrogAI repository follows a monorepo structure based around an [API](#api) with each of the [components](#components) included in a dedicated `packages` directory. Each of these package direc
Is "each of these package directories contains the source code" a typo? The section below shows that source code is in the src/ directory, not the packages/ directory

2024-08-16 14:37 UTC, andrewrisse commented on README.md
> +The [repeater](packages/repeater/) "model" is a basic "backend" that parrots all inputs it receives back to the user. It is built out the same way all the actual backends are and it primarily used fo
typo: "and it is primarily"

2024-08-16 14:44 UTC, justinthelaw commented on README.md
> +The [repeater](packages/repeater/) "model" is a basic "backend" that parrots all inputs it receives back to the user. It is built out the same way all the actual backends are and it primarily used fo
Fixed!

2024-08-16 14:45 UTC, justinthelaw commented on README.md
>  The LeapfrogAI repository follows a monorepo structure based around an [API](#api) with each of the [components](#components) included in a dedicated `packages` directory. Each of these package direc
Yes, I forgot to delete that part of this section!

The structure is correctly represented by the diagram and links + footnotes later on.

2024-08-16 14:46 UTC, andrewrisse commented on docs/DEVELOPMENT.md
> +Below are instructions for adding UDS CLI aliases that are useful for deployments that occur in an air-gap where only the UDS CLI binary available to the engineer.
minor typo: "the UDS CLI binary is available to the engineer."

2024-08-16 14:52 UTC, andrewrisse commented on docs/DEVELOPMENT.md
> +    LOCAL_VERSION=dev ARCH=amd64 make build-cpu    # ui, api, llama-cpp-python, text-embeddings, whisper, supabase
I believe the scripts are defaulted to amd64, but if we want to keep these arg in the example so it's more clear you can change it if needed, I think that's fine

2024-08-16 14:57 UTC, justinthelaw commented on docs/DEVELOPMENT.md
> +Below are instructions for adding UDS CLI aliases that are useful for deployments that occur in an air-gap where only the UDS CLI binary available to the engineer.
Fixed (commit soon)

2024-08-16 14:58 UTC, justinthelaw commented on docs/DEVELOPMENT.md
> +    LOCAL_VERSION=dev ARCH=amd64 make build-cpu    # ui, api, llama-cpp-python, text-embeddings, whisper, supabase
Yeah, any commands that use default args are meant to show the reader that they are set-able. Even if the user explicitly sets them, thinking it is necessary, it doesn't hurt anyone necessarily.

2024-08-16 22:25 UTC, CollectiveUnicorn requested changes

2024-08-16 22:25 UTC, CollectiveUnicorn commented on website/hugo.toml
> +  version             = "v0.10.0"
Probably need to bump this again to 0.11.0

2024-08-16 22:25 UTC, CollectiveUnicorn commented on tests/README.md
Do you want to include the integration tests in here?

2024-08-17 16:16 UTC, justinthelaw commented on website/content/en/docs/local-deploy-guide/dependencies.md
> +- After the successful installation off the toolkit, follow the [toolkit instructions](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt)
No, you are right! I meant to use [this link](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-docker) in that spot. I'll also add the "running a sample workload" part too!

2024-08-17 16:22 UTC, justinthelaw commented on docs/DEVELOPMENT.md
> +The model backends are the only components within the LeapfrogAI stack that are not readily accessible via a `VirtualService`. These must be port-forwarded if a user wants to test a local deployment
Ah yeah, good point! I don't explicitly mention that since most of our SUpabase interactions are via UI or API `supabase` module, and also our Makefiles use the correct endpoints. I will add an explicit mention just in case someone wants to interact with Supabase endpoints directly, and not using the Typescript or Python module.

2024-08-17 16:52 UTC, justinthelaw commented on packages/k3d-gpu/README.md
> +This is for development and demonstration purposes, and should not be used to deploy LeapfrogAI in a production environment.
All reference deployments (UDS Prod, Narwhal, PBME, RKE2 Bare Metal, etc.) are in private repositories. I discussed this with @unicorn-kp and I think we still need to strategize on how to present production deployments, if at all.

The goal of the quick start, and developer docs, is for the open source community or potential mission heros to test and use. Productionized deployments with more capability is where they will have to approach us or create their own via a fork or via their own IaC/PaaS.

2024-08-17 16:54 UTC, justinthelaw commented on packages/k3d-gpu/README.md
> +This is for development and demonstration purposes, and should not be used to deploy LeapfrogAI in a production environment.
I _could_ reference my personal UDS RKE2 repository as a starting point, but that would be kind of kind of sacrilegious and not Defense Unicorns official, haha.

2024-08-17 16:57 UTC, justinthelaw commented on website/hugo.toml
> +  version             = "v0.10.0"
Good catch! Also added it to release please automation - forgot about it.

2024-08-17 17:04 UTC, justinthelaw commented on tests/README.md
Yes, I added some more content about the Make targets regarding integration + unit tests instead of only pointing users to the Makefile.

2024-08-19 14:25 UTC, unicorn-kp reviewed
Reviewed documentation, not changes to the makefiles or any of the code.

2024-08-19 14:25 UTC, unicorn-kp commented on packages/k3d-gpu/README.md
> +This is for development and demonstration purposes, and should not be used to deploy LeapfrogAI in a production environment.
I think this is good as is but I will discuss with Flywheel to see how we want to approach it.

2024-08-19 15:26 UTC, jalling97 commented on README.md
> +  - [UI](#ui)
Very pedantic, but it looks like table of contents is out of order as compared to the sections themselves. To match the document itself:
```suggestion
- [Components](#components)
  - [API](#api)
  - [SDK](#sdk)
  - [UI](#ui)
  - [Backends](#backends)
    - [Repeater](#repeater)
```

2024-08-19 17:20 UTC, justinthelaw commented on README.md
> +  - [UI](#ui)
Fixed!

2024-08-19 17:26 UTC, CollectiveUnicorn commented on website/content/en/docs/local-deploy-guide/dependencies.md
> +- Configure Docker to use the `nvidia` runtime by default by adding the `--set-as-default` flag during the container toolkit post-installation configuration step
The changes are good but I should have been more specific. How would someone know that what is written here means `nvidia-ctk runtime configure --runtime=nvidia --set-as-default`? The words "container toolkit post-installation configuration step" don't necessarily map directly to a command or reference to the help files or anything like that as far as I can tell.

2024-08-19 17:31 UTC, justinthelaw commented on website/content/en/docs/local-deploy-guide/dependencies.md
> +- Configure Docker to use the `nvidia` runtime by default by adding the `--set-as-default` flag during the container toolkit post-installation configuration step
I've changed the section to look like the below. The `--set-as-default` is an optional flag. `nvidia-ctk` does come with a lot of extra options and possibilities, but that particular flag is one of the many ones I wanted to point out. I can also remove the mention of the `(OPTIONAL)` steps completely.

---

### NVIDIA Container Toolkit

- Follow the [instructions](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt) to download the NVIDIA container toolkit (>=1.14).
- After the successful installation off the toolkit, follow the [toolkit instructions](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-docker) to verify that your default Docker runtime is configured for NVIDIA.
- Verify that `nvidia` is now a runtime available to the Docker daemon to use:

  ```bash
  # the expected output should be similar to: `Runtimes: io.containerd.runc.v2 nvidia runc`
  docker info | grep -i nvidia
  ```

- [Try out a sample CUDA workload](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/sample-workload.html) to ensure your Docker containers have access to the GPUs after configuration.
- (OPTIONAL) You can configure Docker to use the `nvidia` runtime by default by adding the `--set-as-default` flag during the container toolkit post-installation configuration step
- (OPTIONAL) Verify that the default runtime is changed by running the following command:

  ```bash
  # the expected output should be similar to: `Default Runtime: nvidia`
  docker info | grep "Default Runtime"
  ```

2024-08-19 17:54 UTC, CollectiveUnicorn approved these changes

2024-08-19 18:10 UTC, jalling97 approved these changes

2024-08-19 18:38 UTC, merged