feat(api): initial integration of registry1 api flavor
defenseunicorns/leapfrogai pull request #920
Opened 2024-08-16 19:04 UTC by justinthelaw

## OVERVIEW

Adds the Registry1 flavor of the LeapfrogAI API to the developer workflow. Does not include automated testing yet. Upgrades API manifests to incorporate multi-flavor best-practices from UDS Common and Core.

## CHANGES

- Adds `FLAVOR` flag to the Makefile, defaulting to `upstream`
- Adds `registry1` Zarf package flavoring for the API
- Refactors entire manifest structure to align with UDS Common and Core best practices

2024-08-16 19:47 UTC, justinthelaw commented
Depends on documentation updates from #902, and then one more update on top of that documentation.

2024-08-21 02:41 UTC, justinthelaw commented
The UI tests will fail because of the changes to the API manifests (see the change made in this PR related to UI Helm charts).

2024-08-31 03:09 UTC, CollectiveUnicorn submitted a review, later dismissed

2024-09-03 15:46 UTC, gphorvath commented on packages/api/config.example.yaml
Do we no longer need config.yaml for local (non-k8s) dev?

2024-09-03 16:05 UTC, justinthelaw commented on packages/api/config.example.yaml
It is only required when running from src/leapfrogai_api, not in the packages directory. In local-k8s, the API uses kiwigrid.

2024-09-03 16:12 UTC, gphorvath commented on packages/api/config.example.yaml
ahhh good call!

2024-09-03 16:12 UTC, gphorvath approved these changes

2024-09-03 16:28 UTC, justinthelaw commented
Pending @YrrepNoj approval too! Thanks @gphorvath and @CollectiveUnicorn

2024-09-03 18:26 UTC, CollectiveUnicorn approved these changes

2024-09-03 19:13 UTC, gphorvath approved these changes

2024-09-03 20:04 UTC, YrrepNoj requested changes
One small change request and one pondering on if we should consider this PR a 'breaking' change.

2024-09-03 20:13 UTC, justinthelaw commented on packages/api/zarf.yaml
> +  version: "###ZARF_PKG_TMPL_IMAGE_VERSION###"
I don't believe this is a breaking change from a user's perspective. This _mostly_ is internally used in the Makefile and the API was the only one that didn't use `IMAGE_VERSION` to modify the version on the fly during build.

2024-09-03 20:14 UTC, justinthelaw commented on packages/api/chart/values.yaml
> +    defaultEmbeddingsModel: "###ZARF_VAR_DEFAULT_EMBEDDINGS_MODEL###"
Oh shoot, I meant to, and have been, removing these in other charts - I must have missed this one, will fix now. Thank you!

2024-09-03 20:46 UTC, YrrepNoj commented on packages/api/zarf.yaml
> +  version: "###ZARF_PKG_TMPL_IMAGE_VERSION###"
If the user is a Zarf package creator then this is kind of a breaking change. If they use the Make target then they the break will be abstracted away from them but people who create packages with the Zarf CLI would have to know there is new name to this variable.

At the end of the day I don't want us to do anything different with the PR, but we should make sure we include a bullet in our release notes to be good stewards to anyone who might be building this package themselves.

2024-09-03 20:47 UTC, justinthelaw commented on packages/api/zarf.yaml
> +  version: "###ZARF_PKG_TMPL_IMAGE_VERSION###"
Okay that makes sense, I can add this as a breaking change in the PR title and in the notes

2024-09-03 20:48 UTC, YrrepNoj approved these changes
LGTM. Thanks for the updates.

2024-09-03 20:57 UTC, CollectiveUnicorn approved these changes

2024-09-03 20:59 UTC, gphorvath approved these changes

2024-09-03 20:59 UTC, merged