chore: add containerization manifest lints
defenseunicorns/leapfrogai pull request #937
Opened 2024-08-20 21:08 UTC by justinthelaw

## Description

Adds linting for Helm, Docker, Zarf, and UDS manifests to improve the quality and consistency of all containerization and Kubernetes related logic.

### BREAKING CHANGES

- N/A

### CHANGES

- Adds Dockerfile linitng
- Adds Helm manifest linting
- Adds UDS bundle linting
- Adds Zarf package linting
- Centralizes linting schemas and configs at the root of the project
- Changes all manifests based on linting errors and warnings

## Related Issue

Fixes #365

## Checklist before merging

- [ ] Tests, documentation, ADR added or updated as needed
- [ ] Followed the [Contributor Guide Steps](https://github.com/defenseunicorns/leapfrogai/blob/main/.github/CONTRIBUTING.md)

2024-08-29 20:17 UTC, justinthelaw commented
Instead of using an [outdated and/or sketchy helm-lint action](https://github.com/justinthelaw/repository-template/blob/main/.github/workflows/helm-lint.yaml) use [this](https://github.com/Azure/setup-helm) to manually install helm v3.15.1 and manually perform a `helm lint [sub-directory]`.

2024-09-04 15:01 UTC, justinthelaw commented
Remaining components to fix:
1. vLLM Dockerfile missing variable
2. llama-cpp-python injection failing
3. UI helm chart reorganization
4. Supabase chart reorganization

2024-09-05 01:59 UTC, justinthelaw reviewed
Fix UI UDS package CR for KeyCloak SSO, and test locally again.

2024-09-05 01:59 UTC, justinthelaw commented on bundles/latest/gpu/uds-config.yaml
> +    GPU_RUNTIME_NAME: "nvidia"  # Set to ensure the nvidia runtimeClass is present in case GPU limit is increased
Change to lowercase within the UDS bundle configS.

Change to `GPU_RUNTIMECLASSNAME`.

2024-09-05 17:18 UTC, YrrepNoj requested changes
Looked through most of the changes and heavily agree with the general direction this PR is going.

Have a few questions and tweaks to request though.

2024-09-05 17:18 UTC, YrrepNoj commented on packages/whisper/chart/templates/deployment.yaml
> +    {{- toYaml . | nindent 8 }}
Similar comment here as elsewhere.

Is there a particular reason to use the `{{- with` clause instead of `{{- toYaml listing.the.path.here`?

2024-09-05 17:18 UTC, YrrepNoj commented on packages/ui/values/upstream-values.yaml
> +  tag: ###ZARF_CONST_IMAGE_VERSION###
I'm not going to comment on all of them but I think `###ZARF_VAR/CONST` should be within quotes. Especially in places like this.

I have seen issues in the past where the tag is not able to be templated correctly because the tag is a number when trying to concat with the repository string later in the deployment.

2024-09-05 17:24 UTC, justinthelaw commented on packages/whisper/zarf.yaml
> +  - name: GPU_RUNTIME
I originally wanted to completely match the actual field, `GPU_RUNTIME_CLASS_NAME` but decided that it was too long, so I shortened it to `GPU_RUNTIME`. `CLASS_NAME` is much more vague than `RUNTIME`, since classname could be interpreted as the GPU class (Ada, etc.), whereas runtime is the proper word to define the actual underlying container software (`nvidia`). For example, if you run `docker info` or look at `containerd` config tomls, `runc` and `nvidia` are called `runtimes` and not classes.

2024-09-05 17:26 UTC, justinthelaw commented on packages/whisper/values/upstream-values.yaml
> +  runtimeClassName: ###ZARF_VAR_GPU_RUNTIME###
This was an unintentional removal of the quotes. You are right that these are supposed to be a string, and adding explicit quotes would cast it to a string for sure. Will change!

2024-09-05 17:28 UTC, justinthelaw commented on packages/whisper/chart/values.yaml
> +  runtimeClassName: "###ZARF_VAR_GPU_RUNTIME###"
You are right! I missed these - my bad

2024-09-05 17:30 UTC, justinthelaw commented on .github/workflows/zarf-lint.yaml
> +name: Zarf Lint
I wanted to have the right triggers in each workflow, but I guess we could have `on` triggers per-job - I don't think I have done that before?

2024-09-05 17:30 UTC, justinthelaw commented on .github/workflows/uds-lint.yaml
> +      - "main"
That is true! I think that is an artifact of my copy/paste from my repository-template, where I was experimenting.

2024-09-05 17:32 UTC, justinthelaw commented on packages/api/Dockerfile
> +ENV PATH="/leapfrogai/.venv/bin:$PATH"
That was actually a mistake when I was experimenting! I can revert to reduce this PR's changes

2024-09-05 17:39 UTC, justinthelaw commented on packages/api/chart/templates/migration-job.yaml
> +  namespace: {{ default "leapfrogai" .Release.Namespace }}
1. No, helm installs where `--name` isn't provided will provide a Helm-generated name, so technically it would never default to `leapfrogai`
2. That being said, I still like the idea of providing the default as an indicator to a user that `leapfrogai` is the default (e.g., the UI will not work out-of-the-box if the namespace changes due to the default `LEAPFROGAI_API_BASE_URL`. I will change it back to our original pattern, since it was mostly a preference thing on my part. The functionality of both syntaxes is the same!

2024-09-05 17:40 UTC, justinthelaw commented on packages/vllm/chart/templates/deployment.yaml
> +            {{- toYaml . | nindent 12 }}
The way the values are rendered when using the method you outlined fails to render when using Zarf. I can't explain why, because `helm template --dry-run` works as-is.

2024-09-05 17:41 UTC, justinthelaw commented on packages/vllm/chart/templates/deployment.yaml
> +            {{- toYaml . | nindent 12 }}
I have seen the `with` method used in other OSS charts, and it isn't taboo or wrong in any sense, just a diff pattern

2024-09-05 17:42 UTC, justinthelaw commented on packages/whisper/chart/templates/deployment.yaml
> +    {{- toYaml . | nindent 8 }}
See https://github.com/defenseunicorns/leapfrogai/pull/937#discussion_r1745933590

2024-09-05 17:43 UTC, justinthelaw commented on packages/ui/values/upstream-values.yaml
> +  tag: ###ZARF_CONST_IMAGE_VERSION###
I can do that! This was mostly an inconsistency and my preference - my bad

2024-09-05 20:19 UTC, gscallon commented
Like the UDS overrides pattern with the default values for the component charts 👍

2024-09-05 23:53 UTC, gscallon submitted a review, later dismissed

2024-09-06 01:39 UTC, justinthelaw commented
@YrrepNoj @gscallon some of the changes made for comment resolution, and also the merge with main, broke the tests. Will fix everything early tomorrow morning and ask for re-review.

2024-09-07 16:30 UTC, justinthelaw commented
> Awaiting approval of 0.12.2 on IronBank. Resolving several new CVEs in VAT.
> 
> https://repo1.dso.mil/dsop/opensource/defenseunicorns/leapfrogai/api/-/merge_requests/32
> 
> https://vat.dso.mil/vat/image?imageName=opensource/defenseunicorns/leapfrogai/api&tag=v0.12.2&branch=renovate/defenseunicorns-leapfrogai-0.x

Same as #977

2024-09-09 13:46 UTC, jalling97 commented on .github/workflows/zarf-lint.yaml
> +name: Zarf Lint
Personally I think it's easier to track with all of the linting types being separate, so unless we have an upper limit to the number of workflows we should have (or something else I'm missing), I don't think it makes a huge difference so I think it works as is.

2024-09-09 13:47 UTC, jalling97 commented on .github/workflows/zarf-lint.yaml
> +        if: always()
For my own education, are the `if: always()` necessary? I would assume that excluding them would result in the each `run` command always running, right?

2024-09-09 13:54 UTC, justinthelaw commented on .github/workflows/zarf-lint.yaml
> +        if: always()
I did that on purpose so that all of them run and show all possible errors in minutes edited by the developer. Unless you think it's better to not do that?

2024-09-09 13:56 UTC, justinthelaw commented on .github/workflows/zarf-lint.yaml
> +        if: always()
Failures will still fail the check at any of those steps in the job. I just thought it would be better user experience to show all errors in all manifests instead of stopping the job short when there is one failure.

2024-09-09 14:00 UTC, jalling97 commented on .github/workflows/zarf-lint.yaml
> +        if: always()
Ah I see now. No I think that makes sense, I just didn't understand the purpose at first. Thanks for clarifying!

2024-09-09 14:07 UTC, jalling97 commented on .pre-commit-config.yaml
> +          bash -c 'FILE="zarf-v0.14.0.schema.json"
Hmm is there anyway to easily pin this version somewhere so we don't have to track down each `v0.14.10` when we need to update UDS versions? I haven't used YAML anchors and aliases before but I wonder if we could use an anchor to set the UDS version and alias it throughout? Thoughts?

2024-09-09 14:10 UTC, justinthelaw commented on .pre-commit-config.yaml
> +          bash -c 'FILE="zarf-v0.14.0.schema.json"
Ah yes, I thought about pinning all of our development deps in a YAML and then using `uds zarf tools yq` to read them (e.g., UDS CLI, k3d, PyEnv etc.), but I think that can be a refactor for future dev-experience optimizations.

2024-09-09 14:10 UTC, justinthelaw commented on .pre-commit-config.yaml
> +          bash -c 'FILE="zarf-v0.14.0.schema.json"
Another possibility is the use of `renovate` (like in UDS Core, or our IronBank repositories), but that is a much larger task and refactor.

2024-09-09 14:14 UTC, jalling97 commented on packages/text-embeddings/Dockerfile
> +# NOTE: We are copying the leapfrog whl to this filename because installing 'optional extras' from
Super pedantic lol, why the change from `leapfrogai` to `leapfrog`?

2024-09-09 14:21 UTC, jalling97 submitted a review, later dismissed
Awesome job cleaning things up!

2024-09-09 14:23 UTC, justinthelaw commented on packages/text-embeddings/Dockerfile
> +# NOTE: We are copying the leapfrog whl to this filename because installing 'optional extras' from
Oh good catch! I can change that back. I think this was an artifact of changes I made in a previous PR not being reflected in this forked-branch where I brought all these changes in from.

2024-09-09 14:28 UTC, jalling97 submitted a review, later dismissed

2024-09-09 19:00 UTC, vanakema commented
some awesome cleanup, ty justin. I didn't review the code closely, but thanks for giving the thorough changelog. This is all great stuff in making the "ux" of contributing and deploying lfai better

2024-09-10 17:40 UTC, justinthelaw commented
Merge this one in first: https://github.com/defenseunicorns/leapfrogai/pull/977

Then change e2e registry1 weekly to point to the commit SHA as a result of the above merge.

2024-09-10 20:13 UTC, CollectiveUnicorn approved these changes

2024-09-11 18:54 UTC, merged