Search VectorStore using only last message
defenseunicorns/leapfrogai pull request #939
Opened 2024-08-21 19:39 UTC by alekst23

## Description

We adjust the RAG implementation to search the vector store using the last user message instead of the first.

We add a needle in a haystack test to confirm problem and fix.

2024-08-26 18:47 UTC, jalling97 commented on tests/integration/api/test_rag_files.py
> +    message_content = messages[-1].content[0].text
I don't think we can assume that the response is always going to be the last item in the list of messages. I found that it can occasionally get swapped with the user message, so I've had to search through the messages to find the actual response.

2024-08-26 18:48 UTC, alekst23 commented
There's one issue to call out here, which is the changes to `src/leapfrogai_api/backend/rag/index.py`. I was encountering an error during testing where the file to be attached to an assistant was already in the vector store. In this case, the endpoint was returning error 500. I don't have an OpenAI conformance test for this yet, but it did not have the same problem during testing.

2024-08-26 18:49 UTC, alekst23 commented on tests/integration/api/test_rag_files.py
> +    message_content = messages[-1].content[0].text
This would be a bug with our API that we would need to resolve.

2024-08-27 16:07 UTC, CollectiveUnicorn requested changes

2024-08-27 16:07 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/rag/index.py
> +            # raise FileAlreadyIndexedError("File already indexed")
Can we get rid of these comments?

2024-08-28 13:33 UTC, YrrepNoj requested changes

2024-08-28 13:33 UTC, YrrepNoj commented on tests/integration/api/test_rag_files.py
> +    return Path(os.path.dirname(__file__) + "/../../data/test_with_data.txt")
This function isn't being used and this file isn't a part of this PR. Was this a copy-paste from somewhere else?

2024-08-28 13:33 UTC, YrrepNoj commented on src/leapfrogai_api/backend/rag/index.py
> +        if file_existing := await crud_vector_store_file.get(
I realize this is beyond the scope of the bug fix you are implementing here, I wanted to leave a comment here so I didn't forget, hopefully spark a little conversation to check my assumptions, and then make a new issue for our backlog.

2024-08-28 13:33 UTC, YrrepNoj commented on tests/integration/api/test_rag_files.py
> +def client_config_factory(client_name):
This factory makes it hard to type-hint the returned object (as well as type hint the values that the different keys refer to when they're used later). 

What are your thoughts on a wrapper class our typed-tuple return instead of a dict?

2024-09-04 14:26 UTC, alekst23 commented on src/leapfrogai_api/backend/rag/index.py
> +        if file_existing := await crud_vector_store_file.get(
Not sure if this is the right place for that type of validation, I think it may need to be done upstream. The reason being is that this function simply tries to add the file to the vector store if it does not exist. It can fail for various reasons, and the file will still be in the database with a status like "canceled" or "failed", and returned to caller. If we try to add it again, it will be duplicated without the user/caller being aware.

I think if there are issues with the file status, it needs to be deleted and re-sent (maybe), but that's up to the calling function.

2024-09-04 15:09 UTC, alekst23 commented on tests/integration/api/test_rag_files.py
> +    return Path(os.path.dirname(__file__) + "/../../data/test_with_data.txt")
True. This was part of a simpler test version. Removed.

2024-09-04 15:11 UTC, alekst23 commented on tests/integration/api/test_rag_files.py
> +def client_config_factory(client_name):
That's a good idea.

This factory is actually part of conformance testing PR that I re-used here, so I have consolidated the code in a `tests/utils/client.py` module and refactored all the relevant test files.

2024-09-04 16:53 UTC, justinthelaw approved these changes

2024-09-04 17:12 UTC, CollectiveUnicorn approved these changes

2024-09-04 19:16 UTC, CollectiveUnicorn approved these changes

2024-09-04 21:17 UTC, YrrepNoj approved these changes

2024-09-04 21:17 UTC, merged