chore(api): add background task for processing vectors
defenseunicorns/leapfrogai pull request #942
Opened 2024-08-22 23:02 UTC by CollectiveUnicorn

## Description

### BREAKING CHANGES

### CHANGES

## Related Issue

Fixes #

Relates to #

## Checklist before merging

- [ ] Tests, documentation, ADR added or updated as needed
- [ ] Followed the [Contributor Guide Steps](https://github.com/defenseunicorns/leapfrogai/blob/main/.github/CONTRIBUTING.md)

2024-08-27 19:00 UTC, CollectiveUnicorn commented
Blocked by #830 and the frontend integration with Supabase realtime for retrieving the VectorStore status

2024-08-28 17:15 UTC, gphorvath reviewed
First pass, a few things jumped out.

2024-08-28 18:29 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/rag/index.py
> +        vector_store.last_active_at = last_active_at  # Update after indexing files
I think its acceptable to use the code generated version here. As `last_active_time` will be used down below to determine expiry, we ideally don't want to have any drift between the value we used to determine expiry and the one that is set in the db.

2024-08-28 18:35 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/rag/index.py
> +                    usage_bytes=0,  # Leave blank to have Postgres generate a UUID
Yep, copypasta issue fixed now

2024-08-28 18:35 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/rag/index.py
> +                usage_bytes=0,  # Leave blank to have Postgres generate a UUID
Yep, copypasta issue fixed now

2024-08-28 18:35 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/rag/index.py
> +                usage_bytes=0,  # Leave blank to have Postgres generate a UUID
Yep, copypasta issue fixed now

2024-08-28 18:38 UTC, CollectiveUnicorn commented on tests/e2e/test_api.py
This is a leftover from moving things around, removing the changes.

2024-08-28 18:39 UTC, CollectiveUnicorn commented on tests/e2e/test_text_backend_full.py
Will await the PR being merged in to make changes.

2024-08-30 16:43 UTC, CollectiveUnicorn commented
Check for vector_store_file creation async

2024-08-31 02:44 UTC, CollectiveUnicorn commented on tests/e2e/test_text_backend_full.py
I have updated the test to use the test fixture for the openai client.

2024-08-31 11:44 UTC, justinthelaw requested changes

2024-08-31 11:44 UTC, justinthelaw commented on src/leapfrogai_api/backend/rag/index.py
> +            # Save the placeholder to the database
I may have missed this, but at any point during the exception handling do we end up deleting the placeholder if the operation fails?

2024-08-31 11:44 UTC, justinthelaw commented on tests/e2e/test_text_backend_full.py
> +def download_arxiv_pdf():
To prevent the possibility of rate limiting, I recommend hosting or downloading this file somewhere else - not strictly required though!

2024-08-31 11:44 UTC, justinthelaw commented on tests/e2e/utils.py
> +    except Exception:
Recommend logging the exception in case something else happens besides a repeated user registration.

2024-08-31 11:44 UTC, justinthelaw commented on pyproject.toml
> +    "fastapi",
Is this being installed as a dev dependency for the test workflow? We should use the fastapi within the src/leapfrogai_api directory pyproject. Else, you can pin it here to match with that dep: `    "fastapi == 0.109.1",`

2024-09-03 19:49 UTC, CollectiveUnicorn commented on pyproject.toml
> +    "fastapi",
It doesn't use the api dependency, it uses the one at the root. Initially put it as a dev dependency on the API and it did not work, I'll pin the version here.

2024-09-03 19:52 UTC, CollectiveUnicorn commented on tests/e2e/test_text_backend_full.py
> +def download_arxiv_pdf():
I've used this PDF elsewhere and it was noted that we didn't want to keep large artifacts in the repo. So unless there's somewhere specific that you'd like it to be hosted I am going to leave this here for now.

2024-09-03 19:58 UTC, justinthelaw commented on tests/e2e/test_text_backend_full.py
> +def download_arxiv_pdf():
Makes sense! I know UDS hosts nginx in GHCR to prevent rate limiting, but since this is a straight unstructured file, that might not be an easy solution. I am not too worried about rate limiting, since we don't get as many pulls/runs as UDS does, but I thought I'd mention it for the chat history.

2024-09-03 19:58 UTC, justinthelaw commented on pyproject.toml
> +    "fastapi",
Works for me!

2024-09-03 20:05 UTC, CollectiveUnicorn commented on tests/e2e/utils.py
> +    except Exception:
Yep I've added some logging that will explain that the error is likely due to the user already existing.

2024-09-03 20:06 UTC, CollectiveUnicorn commented on src/leapfrogai_api/backend/rag/index.py
> +            # Save the placeholder to the database
We don't, I've added some cleanup to the catch statement to delete the created placeholder.

2024-09-03 21:13 UTC, merged