fix(ui): delete avatar
defenseunicorns/leapfrogai pull request #978
Opened 2024-09-03 22:49 UTC by andrewrisse

## Description
When removing an avatar from an assistant, the sveltekit backend was not actually deleting the avatar image from Supabase storage. 

### BREAKING CHANGES

### CHANGES

Corrects the file path and adds a Row Level Security policy that allows users to delete their own avatars.

The 0.7.2 migration that was modified was edited because there was a duplicate policy.

## Checklist before merging

- [X] Tests, documentation, ADR added or updated as needed
- [X] Followed the [Contributor Guide Steps](https://github.com/defenseunicorns/leapfrogai/blob/main/.github/CONTRIBUTING.md)

2024-09-04 22:34 UTC, CollectiveUnicorn approved these changes

2024-09-04 22:39 UTC, justinthelaw submitted a review, later dismissed

2024-09-05 14:47 UTC, YrrepNoj requested changes
One general question and one change request 🫶

2024-09-05 14:47 UTC, YrrepNoj commented on src/leapfrogai_ui/supabase/migrations/20240322174521_v0.7.2_ui_sql_schema.sql
> -    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
In general, we should avoid modifying existing migration files whenever possible. We've broken this rule a few times in the past but I would like to avoid breaking it as much as we can. Can you return this block back to the way it was?

2024-09-05 14:47 UTC, YrrepNoj commented on src/leapfrogai_ui/supabase/migrations/20240903204301_v0.12.0_avatars.sql
> +    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
(here and above on line 24): Do we want to 'error' if a policy already has this name?

Migration scripts are only one once so if a database already had a policy with that name (either the drop didn't work or someone was tinkering and added it themselves) then these policies would never be applied.

2024-09-05 14:47 UTC, YrrepNoj commented on src/leapfrogai_ui/supabase/migrations/20240322174521_v0.7.2_ui_sql_schema.sql
> -    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
Also, what was the end goal of removing this policy here?

If someone has an app that was running with a pre v0.12.0 deployment then they would have this policy. Removing these lines would not remove the policy when they updated to a post v0.12.0 deployment. If this policy is no longer relevant we will need to add a `DROP POLICY IF EXISTS` for it.

2024-09-05 14:47 UTC, YrrepNoj commented on src/leapfrogai_ui/supabase/migrations/20240903204301_v0.12.0_avatars.sql
> +    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
Don't think there's a wrong answer for this one, I am mostly pondering how we want error flow to be.

2024-09-05 15:40 UTC, andrewrisse commented on src/leapfrogai_ui/supabase/migrations/20240322174521_v0.7.2_ui_sql_schema.sql
> -    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
It was a duplicate policy, so the policy will still exist, it was in this file twice

2024-09-05 15:41 UTC, andrewrisse commented on src/leapfrogai_ui/supabase/migrations/20240322174521_v0.7.2_ui_sql_schema.sql
> -    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
and the first occurence was mixed with policies for the ol "avatar" bucket, which was misleading

2024-09-05 15:43 UTC, andrewrisse commented on src/leapfrogai_ui/supabase/migrations/20240903204301_v0.12.0_avatars.sql
> +    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
hmm, currently it just follow existing patterns. I remember we added stuff like this initially because we were getting lots of errors, but you are right that if applied correctly, we wouldn't need it. I guess it helps when fixing issues if you are copy pasting migrations manually

2024-09-05 23:08 UTC, andrewrisse commented
@YrrepNoj , Gato has the migration in this PR: https://github.com/defenseunicorns/leapfrogai/pull/985
tagged as v0.11.1, should I update this PR to match?

2024-09-06 17:48 UTC, andrewrisse commented on src/leapfrogai_ui/supabase/migrations/20240322174521_v0.7.2_ui_sql_schema.sql
> -    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
removed that change

2024-09-06 17:58 UTC, CollectiveUnicorn submitted a review, later dismissed

2024-09-06 19:00 UTC, jalling97 submitted a review, later dismissed

2024-09-18 16:10 UTC, andrewrisse commented on src/leapfrogai_ui/supabase/migrations/20240322174521_v0.7.2_ui_sql_schema.sql
> -    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname = 'storage'
@YrrepNoj following up on this and want to make sure we are good with your changes requested

2024-09-18 18:35 UTC, YrrepNoj approved these changes

2024-09-19 15:57 UTC, merged