init
defenseunicorns/leapfrogai pull request #992
Opened 2024-09-06 13:14 UTC by andrewrisse

Small doc update for UI about libreoffice when running locally

2024-09-06 13:21 UTC, justinthelaw reviewed
Please also add this to the quick_start guide within the website documentation. I added the `needs-docs` label to this PR.

EDIT: NVM, that is containerized. Slow morning!

2024-09-06 13:22 UTC, justinthelaw submitted a review, later dismissed

2024-09-06 13:57 UTC, jalling97 submitted a review, later dismissed

2024-09-06 17:22 UTC, jalling97 submitted a review, later dismissed

2024-09-06 17:23 UTC, CollectiveUnicorn submitted a review, later dismissed

2024-09-06 18:22 UTC, justinthelaw requested changes

2024-09-06 18:22 UTC, justinthelaw commented on bundles/dev/cpu/uds-bundle.yaml
> +    ref: registry1
this may be a mistake?

2024-09-06 18:22 UTC, justinthelaw commented on src/leapfrogai_ui/README.md
> +   ex. ```brew install libreoffice``` or ```apk add libreoffice```
`sudo apt install libreoffice` for Ubuntu, but technically you only need `sudo apt install libreoffice-core-nogui`

2024-09-10 19:10 UTC, andrewrisse commented on src/leapfrogai_ui/README.md
> +   ex. ```brew install libreoffice``` or ```apk add libreoffice```
updated, I confirmed on a mac you do need libreoffice, libreoffice-core-nogui does not work

2024-09-10 19:10 UTC, andrewrisse commented on bundles/dev/cpu/uds-bundle.yaml
> +    ref: registry1
fixed, thank you!

2024-09-10 21:18 UTC, merged